### ISSUE TITLE
Quartierportraits: Rang im Tooltip

### ISSUE THREAD

**Issue by grilli73** [StataBS/indikatoren#1]

**Comment by benjaminrosenbaum** [comment]
- [ ] Todo: Edit function pointFormatter in object tooltip in file [dotplot.js](https://github.com/StataBS/indikatoren/blob/master/charts/dotplot.js).

**Comment by jb3-2** [comment]
- [ ] Todo: Edit function pointFormatter in object tooltip in file [dotplot.js](https://github.com/StataBS/indikatoren/blob/master/charts/dotplot.js).
