### ISSUE TITLE
Mehrere Quellen anzeigen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#107]
Indikator I.03.0.0002 hat in der DB mehrere Quellen hinterlegt. Es wird aber nur die oberste angezeigt. Wo liegt das Problem?

**Comment by jb3-2** [comment]
Da wird sicher die zweite Zeile abgeschnitten. Das ging uns beim Testing der neuen Ränder (wegen Befragungen Untertitel) wohl durch die Lappen. Ich löse das baldmöglichst.

**Comment by JE1982** [comment]
👍

Von meinem iPhone gesendet

Am 31.10.2016 um 18:08 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


Da wird sicher die zweite Zeile abgeschnitten. Das ging uns beim Testing der neuen Ränder (wegen Befragungen Untertitel) wohl durch die Lappen. Ich löse das baldmöglichst.

**Comment by jb3-2** [comment]
Das Problem ist in 167e165d9c8a19fc22b0e27b18f6524b0b73cfbc gelöst, bitte auf dem [Testsystem](https://statabs-test.github.io/indikatoren/) prüfen, ob nun alles ok ist. Einige andere Charts haben auch zwei Zeilen Quellenangaben, diese sieht man sofort in der Thumbnail Ansicht. 

Aktuell werden nur 2 Quellen unterstützt. Reicht dies, oder müssen auch 3 und mehr Quellen möglich sein?

**Comment by JE1982** [comment]
Für den Moment reichen zwei, es wird aber in Zukunft sicher einmal 3 oder mehr Quellen geben.

Ich habe noch 5 jsons ersetzt und auf dem Testsystem gemerget (branch: issue-107), aber ich kann die Auswirkungen (noch) nicht sehen…

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Dienstag, 1. November 2016 16:23
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Mehrere Quellen anzeigen (#107)


Das Problem ist in 167e165<https://github.com/StataBS/indikatoren/commit/167e165d9c8a19fc22b0e27b18f6524b0b73cfbc> gelöst, bitte auf dem Testsystem<https://statabs-test.github.io/indikatoren/> prüfen, ob nun alles ok ist. Einige andere Charts haben auch zwei Zeilen Quellenangaben, diese sieht man sofort in der Thumbnail Ansicht.

Aktuell werden nur 2 Quellen unterstützt. Reicht dies, oder müssen auch 3 und mehr Quellen möglich sein?

**Comment by JE1982** [comment]
habs agekuckt. Kann live gehen.
