### ISSUE TITLE
Legislaturplan Print 2018

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#1073]
the new charts need to be published during October. The exact date is yet to be set.

**Comment by JE1982** [comment]
@jb3-2: I have now updated all metadata and 40 tsv-files in 1073. All jsons include the info whether a Chart has to be small or large.

**Comment by JE1982** [comment]
@jb3-2: the Charts no have to be reviewed and corrected concerning the rules of FR and the margins have to be set like in Integration Print. Could you do so?

**Comment by JE1982** [comment]
@jb3-2: the format of large PNG is not correct. It is now: 5.5*15.86cm. It should be (and is in Integration (Print)): 5.5*17.59cm. Could you please correct this?

**Comment by jb3-2** [comment]
@JE1982 I have changed the width of all wide charts in this set to 665px (same as in Integration Print), now it should be fine. Let me know if it is still not perfect.

**Comment by JE1982** [comment]
done
