### ISSUE TITLE
Show maps for Quartierportraits

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#109]
Highcharts now supports Choropleth Maps. We could display a switch that lets the user change between dot-plot and map. 

Map examples: http://www.highcharts.com/maps/demo/geojson

**Comment by JE1982** [comment]
sehr coole Idee

**Comment by JE1982** [comment]
Ich habe die Karte mit RA besprochen. Die folgenden Punkte sind noch zu klären:
- Klassen oder Verlauf: In den Karten des StatA werden die Werte bis jetzt in jeweils 5 Klassen mit derselben Anzahl Nennungen eingeteilt. Der Highmaps-Vorschlag macht keine Klassen, sondern eine "verlaufende" Einfärbung der Wohnviertel. -> Enscheid RA.
- Die Farbe des Rheins soll immer im gleichen Blauton sein wie in den StatA-Karten.
- Die Farbe der Wohnviertelgrenze soll gleich sein wie die Farbe des Kartenhintergrunds
- Die Farbwahl generell ist noch offen. Denkbar sind die folgenden Varianten
       - Die Wohnviertel auf den ersten, zweiten, dritten usw. 5 Rängen haben in allen Karten die gleiche 
          Farbe. 
      - Die ersten Ränge sind hell, die letzten dunkel oder vice versa. Dies erlaubt verschiedene Farbtöne. 
      - Die Farbwahl wird individuell gestaltet.

-> Entscheid RA.

**Comment by jb3-2** [comment]
Ich habe die Kartendarstellung nun angepasst, siehe https://statabs-test-indikatoren-jonasbieri.c9users.io (bitte melden, falls die Website nicht läuft - aus Kostengründen fährt der Server von selbst herunter nach einer gewissen inaktiven Zeit). 

Die Farb-Achse kann sehr frei definiert werden. Es kann entweder eine kontinuierliche Achse (wie aktuell verwendet), oder eine klassifizierte Farbachse verwendet werden (siehe Beispiele unter http://www.highcharts.com/maps/demo. Je nach Indikator kann einmal die eine, einmal eine andere Farb-Achse verwendet werden.

**Comment by jb3-2** [comment]
An Kuno in die Formale Redaktion zur Prüfung gegegeben

**Comment by jb3-2** [comment]
Die Formale Redaktion (vertreten durch ug) ist einverstanden.

**Comment by jb3-2** [comment]
Karten sind erstellt. Warte nun auf @JE1982, der alles mit dem GIS Produktverantwortlichen and den Themenverantwortlichen überprüft.

**Comment by JE1982** [comment]
ich finde diese Beschriftungsart nicht so schön. 
![2017-01-20 13_03_07-mozilla firefox](https://cloud.githubusercontent.com/assets/20972660/22148858/e0733076-df10-11e6-8df0-35af6000e397.png)

gibt's eine andere Möglichkeit? Evtl. die Schrift drehen? Oder zwei Zeilen einfügen?

**Comment by JE1982** [comment]
die Farbgebung in den Farben der Themenbereiche ist zu überlegen. Also R&U = grün, G&S = violett und W&A = blau.

**Comment by JE1982** [comment]
Die Maps sind bei KB in der Formalen, um eine Lösung für das Skalenproblem zu bekommen. Tendenz: Skala muss nicht zwingend bei 90 beginnen.

**Comment by JE1982** [comment]
nach Abschluss der Revision müssen alle json-files sowohl für die dotplots wie auch für die maps nochmals neu geladen werden, damit die Rückmeldungen der TV berücksichtigt sind.

**Comment by JE1982** [comment]
Input BL: Wir sollten Links auf den Basler Atlas setzen, wo immer dies sinnvoll ist. 
Umsetzung: Die Links müssen in den Erläuterungen eingepflegt werden.

**Comment by jb3-2** [comment]
@JE1982 Ich habe bei Chart 5120 die Farbskala geändert, passt es Dir so?

![i 09 1 0034](https://cloud.githubusercontent.com/assets/7261044/22367027/af782e1c-e47f-11e6-9bb6-62861e3e406e.png)

**Comment by jb3-2** [comment]
@JE1982 Andere Charts haben lange Zahlen in der Skala. Bist Du da mit dem "Staggering" (zweizeilige Anzeige der Werte unter der Farbskala) einverstanden, oder soll ich die Werte durch 100 teilen und "in tausend Franken" angeben? Siehe die beiden Bilder weiter unten in diesem Kommentar. 

![i 18 2 0005](https://cloud.githubusercontent.com/assets/7261044/22367118/1fe1f7be-e480-11e6-8056-8a4024e07cc2.png)

![i 18 2 0005 1](https://cloud.githubusercontent.com/assets/7261044/22367177/8038e0fa-e480-11e6-8cd6-6407c94445ca.png)

**Comment by JE1982** [comment]
Sieht gut aus, ja.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Freitag, 27. Januar 2017 11:00
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Mention
Betreff: Re: [StataBS/indikatoren] Show maps for Quartierportraits (#109)


@JE1982<https://github.com/JE1982> Ich habe bei Chart 5120 die Farbskala geändert, passt es Dir so?

[Das Bild wurde vom Absender entfernt. i 09 1 0034]<https://cloud.githubusercontent.com/assets/7261044/22367027/af782e1c-e47f-11e6-9bb6-62861e3e406e.png>

**Comment by JE1982** [comment]
Lieber in tuasend Franken angeben, also Variante 2.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Freitag, 27. Januar 2017 11:06
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Mention
Betreff: Re: [StataBS/indikatoren] Show maps for Quartierportraits (#109)


@JE1982<https://github.com/JE1982> Andere Charts haben lange Zahlen in der Skala. Bist Du da mit dem "Staggering" (zweizeilige Anzeige der Werte unter der Farbskala) einverstanden, oder soll ich die Werte durch 100 teilen und "in tausend Franken" angeben? Siehe die beiden Bilder weiter unten in diesem Kommentar.

[Das Bild wurde vom Absender entfernt. i 18 2 0005]<https://cloud.githubusercontent.com/assets/7261044/22367118/1fe1f7be-e480-11e6-8056-8a4024e07cc2.png>

[Das Bild wurde vom Absender entfernt. i 18 2 0005 1]<https://cloud.githubusercontent.com/assets/7261044/22367177/8038e0fa-e480-11e6-8cd6-6407c94445ca.png>

**Comment by JE1982** [comment]
Feedback KB:
Es gibt Maps (WA-3, WA-5), wo Riehen und Bettingen per Definition denselben Wert aufweisen. Leider haben sie aber nicht denselben Rang (gilt auch fpr die Dotplots). Da müssen wir uns etwas einfallen lassen. 
Das Feedback zur Skaleneinteilung folgt morgen Dienstag.

**Comment by JE1982** [comment]
alle Anmerkungen der TV sind in den Metadaten erfasst.
