### ISSUE TITLE
Upgrade HighCharts to 5.0

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#116]

**Comment by jb3-2** [comment]
Implementation together with Highmaps incorporation in #109, see branch https://github.com/statabs-test/indikatoren/tree/issue-109

**Comment by jb3-2** [comment]
Taken out in its own branch

**Comment by JE1982** [comment]
Bei mehrzeiligen Legendenbeschriftungen ist nur die erste Zeile farbig, alle weiteren sind schwarz. Siehe: 
![2016-12-21 17_13_13-statistik - wohnraumindikatoren](https://cloud.githubusercontent.com/assets/20972660/21396509/d6d2bcf8-c7a0-11e6-9d1d-cb6ef165fc29.png)
Dies ist aber kein neuer Fehler, sondern ist auch bei der Live-Verison bereits so.

**Comment by jb3-2** [comment]
Ich habe dazu ein eigenes Issue erstellt (#138).

**Comment by jb3-2** [comment]
Ist erledigt.
