### ISSUE TITLE
Vorschau-buttons in Access

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#1166]
Idea: the button "Vorschau Entwicklung" could be disabled in cases when no issue-nr. is set and enabled otherwise. @lcalmbach: what do you think? 

![image](https://user-images.githubusercontent.com/20972660/47557463-010b7680-d911-11e8-8e6e-17c9d8921aef.png)

we could do the same with the buttons "Vorschau Aktualisierung" and "Live-Ansicht". They are only enabled when a Chart has already been "live" at least once. @lcalmbach: agree?

**Comment by lcalmbach** [comment]
this has been implemented, there is however an issue with indicators, that are live in the system, but have never been initialized as such in the DB (373). these need to be initialized in the DB. @JB: would it be possible to provide a  list of alle indicators, that are currently live in the portal?
