### ISSUE TITLE
Show all "Unterthema" when one is selected

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#1167]
At the moment one has to click "Unterthema: Alle" to change the "Unterthema" from one to another. It would be better to show all "Unterthema" when one is selected. See: 
![image](https://user-images.githubusercontent.com/20972660/47638506-06f69700-db5f-11e8-9dcb-06730c8a4ddc.png)

**Comment by jb3-2** [comment]
@JE1982 I have implemented this [here](https://issue-1167--statabs-indikatoren-test.netlify.com/), can you please test?

**Comment by JE1982** [comment]
@jb3-2: works!
