### ISSUE TITLE
4129 lacks Quellenangabe

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#1190]
This is the only one that lacks quellenangabe in portal: 

![image](https://user-images.githubusercontent.com/7261044/48316541-73ed4080-e5e5-11e8-8830-1465736eab94.png)

https://statabs.github.io/indikatoren/chart-details.html?id=4129

![image](https://user-images.githubusercontent.com/7261044/48316508-e0b40b00-e5e4-11e8-9908-716dc049cedb.png)

**Comment by JE1982** [comment]
corrected in issue-1190. In review at FR now.
