### ISSUE TITLE
5793 lacks Aktualisierungsdatum

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#1193]
It's the only one in portal view: 

![image](https://user-images.githubusercontent.com/7261044/48316911-160f2780-e5ea-11e8-834a-de892325a437.png)

![image](https://user-images.githubusercontent.com/7261044/48316914-245d4380-e5ea-11e8-8b11-4257798759bb.png)

**Comment by JE1982** [comment]
@jb3-2: I corrected this in the master branch. Please confirm the pull request on gh-pages to set it live.
