### ISSUE TITLE
prevent x-axis label linebreak in Firefox

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#1277]
Firefox wraps the last x-Axis label in this example, IE and Chrome handle it correctly.:

![grafik](https://user-images.githubusercontent.com/20966212/53080067-25aae000-34f8-11e9-9d50-f03983561a3d.png)

https://statabs.github.io/indikatoren/chart-details.html?id=6464&indikatorensetView=true&suppressNumberInTitle=false

Would be good to check if this behaviour can be prevented. 
@dmathys can you try to figure this out? @jb3-2 any experience?

**Comment by jb3-2** [comment]
Here's a solution that works, even though it's not the most beautiful one: 
![image](https://user-images.githubusercontent.com/7261044/53097625-307a6a80-3522-11e9-8c0e-00e587a73314.png)
