### ISSUE TITLE
Gesundheitsindikatoren updaten

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#128]
I.14.1.0002 und I.14.1.0003 updaten

**Comment by JE1982** [comment]
Zahlen 2015 ergänzt, ab 2012 ersetzt. Erläuterungen und Lesehilfen angepasst.

**Comment by jb3-2** [comment]
Go-Live noch ausstehende. JB wartet mit Go-Live auf JE's Auftrag.
