### ISSUE TITLE
Add possibility to add Highstock charts

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#135]

**Comment by jb3-2** [comment]
See first test here: http://issue-135--retailer-seawater-16683.netlify.com/einwohner_bs

**Comment by JE1982** [comment]
sieht für mich schon sehr gut aus!
Idee: Sollen wir die Charts etwas länger (Nord-Süd) machen, weil der Regler auch noch Platz verbraucht.

**Comment by jb3-2** [comment]
Wird in issue-173 (https://github.com/StataBS/indikatoren/issues/173) weiterentwickelt.
