### ISSUE TITLE
Change order of charts to make start page less boring

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#164]
Currently, the start page always looks the same. We should change the order of charts so that e.g. the latest updates are displayed first. 

We could also add a 'new' badge to charts that the user has not opened yet and/or that are younger than e.g. 4 weeks.

**Comment by JE1982** [comment]
good idea. I would prefer a randomly ordered system. Adding a 'new' button (for new generated charts) and a 'update' button (for updated charts (only for new data, not for simple corrections).
