### ISSUE TITLE
Nach Darstellungsart filtern in der Portalansicht

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#171]
Es soll möglich sein, die Darstellungsart (zurzeit: Grafik, Karte, später evtl. Tabelle etc.) auszuwählen.
@grilli73 @jb3-2

**Comment by JE1982** [comment]
haben wir schon Resultate bezüglich Schlagwortsuche?

**Comment by jb3-2** [comment]
Habe noch nicht mit dem Issue begonnen.

**Comment by jb3-2** [comment]
@grilli73 Could you please create a graphical mockup how this should look and work? "Es soll möglich sein, die Darstellungsart (zurzeit: Grafik, Karte, später evtl. Tabelle etc.) auszuwählen."

**Comment by JE1982** [comment]
@jb3-2: Darstellungsart ist ab sofort im json (Testversion)

**Comment by jb3-2** [comment]
@lcalmbach Can you please change the name of the property in the json file to "darstellungsart"? Thanks!

**Comment by jb3-2** [comment]
@JE1982 @grilli73 Should it be named Darstellungsart or Darstellungsform? In case of Wohnviertel maps we create a link that says "Andere Darstellungsform". 

It almost works, see https://issue-171--statabs-indikatoren-test.netlify.com/?Indikatorenset=Wohnviertel&darstellungsart=Karte

What does not work yet is in indikatorenset view when filtered by Karte you cannot jump to the other darstellungsform through the link. .

**Comment by jb3-2** [comment]
@JE1982 @grilli73 Can you please test this feature? It works now for me in Chrome on Mac.

**Comment by jb3-2** [comment]
@JE1982 I have now manually updated the json of the 12 categorial maps so that we can now filter for continuous and categorical maps, see https://issue-171--statabs-indikatoren-test.netlify.com/ 

Please let me know if this can go live.

![image](https://user-images.githubusercontent.com/7261044/45417499-9533be00-b682-11e8-944c-b2cfb492eace.png)

**Comment by jb3-2** [comment]
closed with 1913bc56ba984823c615c268485541119c31f4d2
