### ISSUE TITLE
Charts mit langen Zeitreihen in Highstocks darstellen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#173]
1. Schritt: Identifikation von Indikatoren, die potenziell mit highstocks dargestellt werden könnten
2. Schritt: Definition Prozess Umsetzung / Anpassung sql und evtl. Metainformation
3. Schritt: Umsetzung in highstocks und access

**Comment by jb3-2** [comment]
Programmierung in #135 schon recht weit, siehe Beispiel Chart 9999 hier: 
- Chart alleine: http://issue-135--retailer-seawater-16683.netlify.com/chart.html?id=9999 
- Gesamte Portalansicht: http://issue-135--retailer-seawater-16683.netlify.com

@JE1982 @grilli73: Bitte um Feedback.

**Comment by jb3-2** [comment]
KB's Input habe ich heute mündlich erhalten und schon umgesetzt: 
- Abstand zwischen den Buttons vergrössert
- Leerzeichen zwischen 10 und J (10J --> 10 J)
- Y-Achsen Labels mittig anordnen an horizontale Gridlines

**Comment by jb3-2** [comment]
Todo: Testing in Internet Explorer

**Comment by jb3-2** [comment]
@JE1982 Könntest Du bitte einen ersten Indikator auswählen, für den wir diesen Chart Typ verwenden sollen?

**Comment by JE1982** [comment]
die Zahlen (2005 bis 2015) sind identisch mit ID=4132. Es spricht m.E. nichts dagegen, diesen Indikator zu ersetzen. Wir müssen uns noch überlegen, wie dies in der DB umgesetzt wird.

**Comment by jb3-2** [comment]
@lcalmbach Hier die Daten: https://github.com/statabs-test/indikatoren/blob/issue-135/data/9999.tsv. Bitte auch noch das neue Template "stock001" in der DB auswählbar machen. Danke.

**Comment by lcalmbach** [comment]
@JB: neue Template "stock001" ist erfasst

**Comment by lcalmbach** [comment]
@JB: habe die Daten eingelesen. zwischen 1997 und 2011 gibt es z.T Differenzen mit den Zahlen, die wir im DWH haben. Das stammt daher, dass für das JB jeweils Filter auf den Jahresendbestand angewandt wurden, die wir nicht mehr nachvollziehen können.  Ich fände es besser, wenn wir die Zahlen aus dem DWH verwenden würden, dann sind die Zahlen konsistent egal nach welchen Kategorien (Geschlecht, Nationalität, WV etc.) wir sie ausweisen

**Comment by jb3-2** [comment]
@JE1982 Chart 4132 ist nun auf Stockchart umgestellt, und die Daten wurden erweitert. Bitte die Metadaten anpassen (Lesehilfe, Erläuterungen), sowie den Chart and alles testen (da nun Highstocks überall verwendet wird, könnte theoretisch etwas nicht mehr gleich funktionieren wie vorher). Bitte hier testen: http://issue-173--retailer-seawater-16683.netlify.com/ bzw. http://issue-173--retailer-seawater-16683.netlify.com//chart.html?id=4132 (der angepasste Indikator). Danke.

**Comment by JE1982** [comment]
bei der csv-domwnload-Funktion kommt neben dem Datum auch die Uhrzeit (jeweils 0:00) mit, was keinen Mehrwert bietet. @jb3-2 Kannst du das rausnehmen?
Weiter sind die Datenreihen ab einem gewissen Jahr (ich glaube 1965) jeweils doppelt angezeigt. @jb3-2 wieso?

**Comment by JE1982** [comment]
mir fällt auf, dass die Charts länger als bisher brauchen, bis sie geladen werden (etwa 1 Sek nach Klick)

**Comment by jb3-2** [comment]
Die Netlify Testumgebung ist meinen Beobachtungen nach langsamer als github.io, deshalb wird sich nach dem Go-Live dieses Features die Ladezeit wohl nicht merklich von der aktuellen Ladezeit unterscheiden.

**Comment by JE1982** [comment]
@jb3-2 wo bzw. über welches Feld in der DB wird die Default-Einstellung für die angezeigte Anzahl Jahre gesteuert?

**Comment by jb3-2** [comment]
Im Template: https://github.com/StataBS/indikatoren/blob/master/charts/templates/4132.js#L28

Dort sind die Buttons definiert, weiter unten unter "selected", welcher der Buttons by default ausgewählt ist (dessen Index, bei 0 beginnend), siehe http://api.highcharts.com/highstock/rangeSelector.selected
