### ISSUE TITLE
Add external links to metadata

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#175]
It should be possible to add Links to external resources to the metadata. Currently we need links from the maps to the corresponding map in basleratlas, e.g. 

Bearbeiten Sie diese Karte im [Basler Atlas](https://basleratlas.ch/#i=ru_gruen.gruenflaeche_ant). 

To do this, we need a new field of type array in the chart metadata as follows: 

`"externalLinks": ["Bearbeiten Sie diese Karte im <a href='https://basleratlas.ch/#i=ru_gruen.gruenflaeche_ant' target='_blank'>Basler Atlas</a>."]`

@lcalmbach: Could you please add this functionality to the db system?
@bl99 : As soon as the system allows it, could you please add the links to the db system? 

I will then render the links together with the links to different visualisations of the same data and the link to the chart's Indikatorenset as follows: 

### Links
- [Andere Darstellungsform ](https://statabs.github.io/indikatoren/chart.html?id=4832) dieser Daten
- Dieser Indikator ist Bestandteil des Indikatorensets [Wohnviertel](http://www.statistik.bs.ch/zahlen/indikatoren/sets/wohnviertel.html).
- Bearbeiten Sie diese Karte im [Basler Atlas](https://basleratlas.ch/#i=ru_gruen.gruenflaeche_ant). 

Thanks!

**Comment by JE1982** [comment]
Links auf Basler Atlas sind in den json-files drin, diese sind in branch issue-175 raufgeladen. pull request auf testsystem hat nicht funktioniert. 
@jb3-2 bitte kontrollieren.

**Comment by jb3-2** [comment]
Links sind nun umgesetzt, siehe diese Testversion: http://retailer-seawater-16683.netlify.com/ 

@JE1982: 
-  Link auf andere Darstellungsform noch genau zu diskutieren - aktueller Stand ist wohl noch nicht befriedigend. 
-  Sollen von den Wohnviertel Dotplots aus auch Links auf die Karten des Basler Atlas erstellt werden, oder nur von den Maps aus?
- Nun sollten auch viele weitere Links erstellt werden, z.B. von Basler Index der Konsumentenpreise 4909 auf folgende Pages. Kannst Du dies bitte organisieren?
http://www.statistik.bs.ch/interaktiv/index.html
http://www.statistik.bs.ch/zahlen/tabellen/5-preise/teuerungsrechner.html

**Comment by jb3-2** [comment]
@JE1982 Indikator 4917 hat im json file kein parent oder child, sollte aber mit 5130 verlinkt sein. Kannst Du prüfen, warum das so ist? Ist vielleicht einfach das hochgeladene json file für 4917 nicht aktuell? Danke.
@JE1982 Nun funktioniert das Verlinken auf andere Charts, auch wenn der verlinkte Chart nicht in den Suchresultaten liegt. Suche z.B. im Volltext nach "map", dann untern auf "Andere Darstellungsart" klicken: http://retailer-seawater-16683.netlify.com/

**Comment by JE1982** [comment]
4917 und 5130 sind im System verlinkt. Ich lade die beiden jsons nochmals hoch in branch "issue-175".

**Comment by JE1982** [comment]
done

**Comment by JE1982** [comment]
wie wär's mit diesem Symbol als Aufzählungszeichen für die Links?
![image](https://cloud.githubusercontent.com/assets/20972660/23297170/bf3f1b44-fa78-11e6-8281-580bf4873326.png)
Das wird in magnolia verwendet.

**Comment by JE1982** [comment]
Als Aufzählungszeichen für die Links könnten wir das Symbol aus Magnolia verwneden.
Siehe z. B. hier: http://www.statistik.bs.ch/zahlen/indikatoren/sets/wohnraumentwicklung.html

**Comment by JE1982** [comment]
M. E. sollen die Links zum Basler Atlas nur von den Karten aus möglich sein, von den Dotplots nicht.

**Comment by jb3-2** [comment]
@grilli73 Könntest Du mir das von @JE1982  [vorher](https://github.com/StataBS/indikatoren/issues/175#issuecomment-282241499) referenzierte Bild geben, so dass ich es als Aufzählungszeichen einbauen kann? Ich schaffe es nicht, es von der Magnolie Website herunterzusaugen. Danke!

**Comment by jb3-2** [comment]
@bl99 In der GeoClip Kartenansicht sieht man gar nicht, welcher Indikator aktuell ausgewählt ist. Kann man das noch irgendwie einschalten? siehe z.B. https://basleratlas.ch/#i=bevkonf.anteil_keinereligion 

@grilli73 @JE1982 Die Aufzählungszeichen habe ich nun angepasst. Gleichzeitig habe ich den Grünton der Links bei uns angepasst, so dass nun das gleiche grün verwendet wird wie auf bs.ch. Könnt Ihr bitte dies alles testen und abnehmen? Danke.

**Comment by bl99** [comment]
![basleratlas](https://cloud.githubusercontent.com/assets/20966212/23502565/95060094-ff38-11e6-8183-409cd2838147.png)
ist schon drin, aber halt nicht prominent

**Comment by JE1982** [comment]
nicht alle dotplots haben Lnk auf andere Darstellungsform. Bsp. 4837

**Comment by jb3-2** [comment]
@je1982 Kannst Du Die Daten in der DB ergänzen, so dass alle relevanten Links drin sind, und die json files hochladen in dieses issue, ich builde dann neu. Danke.

**Comment by JE1982** [comment]
@jb3-2: 4837 hat eine child-id im json, aber in den links keine andere Darstellungsform.

**Comment by jb3-2** [comment]
@JE1982 Das Indikatorensystem verwendet die Property "renderLink" für das Rendern eines Links auf eine andere Darstellungsform derselben Daten. Bitte prüfen, warum bei diesen json Files der renderLink leer ist.

**Comment by JE1982** [comment]
alle Wohnviertel-Charts haben nun den Verweis auf die andere Darstellungsart in den Links.
@bl99 kannst du checken, ob überall der Hinweis auf den Basler Atlas drin ist, wo er drin sein muss?
@jb3-2 ich finde die neue Farbgebung der Links nicht so glücklich. Ich fände es schöner, wenn die Titel (Lesehilfe, Erläuterungen, Links) in derselben Farbe wären wie die Links. Ob nun blau oder grün ist mir nicht so wichtig. Tendenz: blau, da dezenter.

**Comment by jb3-2** [comment]
Wie besprochen, die Farben der Links entsprechen denen auf bs.ch. Nun habe ich in #211 (commit b248dac7c0d8f850567b48b0e8fe214d9871077c) auch die Farbe der Links "on hover" angepasst, siehe branch master

**Comment by bl99** [comment]
Bei drei Karten noch die Links entfernt, da Inhalt doch leicht unterschiedlich von Basler Atlas.
