### ISSUE TITLE
Add Maps for 4917 and 4918 

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#187]
@JE1982 Please add the metadata so I know the IDs. Thanks!

**Comment by JE1982** [comment]
metadata is completed. ids: 5130 and 5131;

**Comment by jb3-2** [comment]
@JE1982 Can you please create a branch and upload the json files? Thanks.

**Comment by JE1982** [comment]
done

**Comment by jb3-2** [comment]
Subtitle is wrong, no correct year as suffix. Can you please correct and re-upload? Thx

**Comment by JE1982** [comment]
done; issue-128

**Comment by jb3-2** [comment]
@JE1982 Can you please review the charts on the test system before we go live with them? Thanks! 

- https://statabs-test.github.io/indikatoren/chart.html?id=5130
- https://statabs-test.github.io/indikatoren/chart.html?id=5131
- https://statabs-test.github.io/indikatoren/chart.html?id=4917
- https://statabs-test.github.io/indikatoren/chart.html?id=4918

**Comment by JE1982** [comment]
4918 hat 3 Nachkommastellen, 5131 hat nur 2 Nachkommastellen. 
beide maps sollten in grün gehalten werden, nicht in blau.

**Comment by jb3-2** [comment]
Ok fixed, ready for live?

**Comment by JE1982** [comment]
yes
