### ISSUE TITLE
Link from chart to chart

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#191]
We should have links between charts. Currently, the id of the linked chart is given in the metadata in the "renderLink" array, e.g. : 
`"renderLink": [
			"4839"
		]`

Render the links as described in #175

**Comment by jb3-2** [comment]
@JE1982 Suppose you filter only maps (using fulltext search "map"). Then you open a map and see the that the map has a linked chart (e.g. a dotplot). What happens when you click on the link, are the search results lost and only the linked chart is found (the text on top will say "1 / 1")? Or should the link to the linked chart only appear when it is part of the current search results? Or should the search results be extended with the linked chart? Let's discuss.

**Comment by JE1982** [comment]
in my opinion we should go with alternative 3: the search result should be extended with the linked chart.

**Comment by jb3-2** [comment]
I have now implemented this in [#175](https://github.com/StataBS/indikatoren/issues/175). If a linked chart that is not part of the current search result set is clicked upon, the search terms are cleared (so that all charts are found), and the carousel flips to the linked chart.
