### ISSUE TITLE
Place Chart Id somewhere else

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#200]
People begin reading at the top left corner. The first thing they read is the complicated chart id. That's not good. We should put the chart id somewhere else. How about:

- in the subtitle
- in the sources: "Quelle: Kantonale Bevölkerungsstatistik, I.01.1.0001"
- at the end of the title, but not in bold

Let's discuss.

![image](https://cloud.githubusercontent.com/assets/7261044/22733752/6c46e2c8-edf3-11e6-8817-8083dc15ec51.png)

**Comment by JE1982** [comment]
agree as far as it has not necessarily to take place in front of the indikator title. do not agree on the three proposals. lets think about some other ideas.

**Comment by jb3-2** [comment]
- ID is displayed in html text below chart in blue: "Indikator I.01.1.0003"
- ID is removed from title except in Indikatorenset View, where it stays as it is now: only displayed if "suppressNumberInTitle=false"

**Comment by jb3-2** [comment]
Clickable Title in Preview: Change to Unterhema Kuerzel

**Comment by jb3-2** [comment]
@JE1982 @grilli73 Bitte prüfen, ob das nun so ok ist für Euch: Portalansicht: http://issue-200--retailer-seawater-16683.netlify.com/, Indikatorenansicht: http://issue-200--retailer-seawater-16683.netlify.com/?Indikatorenset=Wohnviertel

**Comment by JE1982** [comment]
Die Portalansicht der SVGs ist für mich so gut gelöst. Die Setansicht macht mich noch nciht restlos zufrieden, aber ich habe keinen besseren Vorschlag.
In der Detailansicht würde ich darauf verzichten, das Unterthema anzugeben und nur das Kürzel unterhalb der Grafik anzeigen.

Mobilversion: Nathi schlägt vor, in der Mobilversion (svg) auf das Unterthema zu verzichten, so würde gar ncihts abgeschnitten. Ich könnte auch damit gut leben.

**Comment by jb3-2** [comment]
- In Detailansicht: "Indikator I.01.1.0001" als Titel. 
- In Setansicht: Titel der Charts: "kuerzelKunde Stufe1" (also andersrum als aktuell). 
- In Mobilversion: Nichts ändern für den  Moment.

**Comment by jb3-2** [comment]
@JE1982 In Detailansicht in einem Indikatorenset habe ich den Titel wie folgt gesetzt: "INDIKATOR 1.2.E".  Ist das ok für Dich, oder soll hier auch Kuerzel statt KuerzelKunde verwendet werden?

**Comment by JE1982** [comment]
Das passt so.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Mittwoch, 24. Mai 2017 15:14
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Mention
Betreff: Re: [StataBS/indikatoren] Place Chart Id somewhere else (#200)


@JE1982<https://github.com/je1982> In Detailansicht in einem Indikatorenset habe ich den Titel wie folgt gesetzt: "INDIKATOR 1.2.E". Ist das ok für Dich, oder soll hier auch Kuerzel statt KuerzelKunde verwendet werden?
