### ISSUE TITLE
Add Umweltbericht Indikatoren

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#205]
The following tasks need to be completed: 
1. Chart configs (incl. data): in the build, use phantomJS to open a website that displays all charts, then get all configs through the `Highchart.charts` array and save them to the file system. Configure the app to load the finished configs instead of merging template and data on load. 
2. Chart metadata: Process to be defined by @bl99 and @lcalmbach 
3. Chart data: Process to be defined by @bl99 and @lcalmbach

**Comment by jb3-2** [comment]
@JE1982 @bl99 See current state of development here in Indikatorenset View: http://issue-205--retailer-seawater-16683.netlify.com/?Indikatorenset=Umwelt or here in Portal View: http://issue-205--retailer-seawater-16683.netlify.com

**Comment by jb3-2** [comment]
@JE1982 @bl99 Let's discuss if and how to remove certain data from the charts.

**Comment by jb3-2** [comment]
JE (via E-Mail): Hier meine grundsätzlichen Rückmeldungen zum Umweltbericht:
-	Lesehilfe/Erläuterungen nicht anzeigen. Nur Link auf Chart von Björn. 
-	Die Quellenangaben sollen gleich formatiert sein wie bei uns.
-	Die Links sollen aktiv sein
-	Die Legendensymbole sollen strukturiert angeordnet sein (nice to have)
-	Die Stock-Charts sollen die gleichen Einstellungen haben wie bei uns (nice to have)

**Comment by jb3-2** [comment]
@lib Why do you add "series.includeInCSVExport: false"to all your charts? In Indikatorenportal, I cannet get the csv export to work with this setting (see e.g. http://issue-205--retailer-seawater-16683.netlify.com//chart.html?id=5800). Why does it work in your environment?

**Comment by JE1982** [comment]
weisst du, weshalb auch BL-Werte angezeigt werden? falscher Branch?

**Comment by jb3-2** [comment]
@JE1982 @larafaelivrin Einzelne Bugs oder Feature Requests bitte als einzelne Issues erfassen, sonst ist es schwierig, den Überblick zu behalten. Danke.

**Comment by jb3-2** [comment]
Merged into master branch with 2815f23124bd25eb3eb43d9266a1cb7e9a406199 and deployed to live.
