### ISSUE TITLE
Add template for pie and area chart

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#209]

**Comment by jb3-2** [comment]
@grilli73 @Nana-Mittelmaier @larafaelivrin 
Für Pie und Area Charts habe ich nun je ein Template und ein Beispiel erstellt, siehe folgende beiden URLs: 
- [Area](http://author-alison-12014.netlify.com/chart.html?id=area)
- [Pie](http://author-alison-12014.netlify.com/chart.html?id=pie)

Ihr findet die Files im branch [issue-209](https://github.com/statabs-test/indikatoren/tree/issue-209/charts/templates), die templates heissen area001.js und pie001.js, und die sample charts heissen area.js und pie.js.

Für die Arbeit an den neuen Indikatoren klont Ihr am besten diesen Branch statt den Master, dann sind die Templates da schon drin.

**Comment by JE1982** [comment]
Feedback zu Area-Chart: 
- Kannst du die 125%-Linie wegnehmen? Die braucht's da ja nie. 
- ist es möglich, dass du die Legendenbeschriftungen strukturiert anordnest?
- bitte daran denken, noch ein Feedback von KB einzuholen.

**Comment by JE1982** [comment]
Feedback zu Pie-Chart: 
- ausgezeichnet.
- bitte daran denken, noch ein Feedback von KB einzuholen.

**Comment by jb3-2** [comment]
@JE1982 @grilli73
- Die Legendenbeschriftung wird durch den Highcharts Entwickler als Tabelle gelayoutet, das kann man noch nicht im Template definieren, da man die Länge der Einträge in Pixel angibt.  
- KB ist zufrieden.

**Comment by jb3-2** [comment]
@lcalmbach Die Templates "area001" und "pie001" sind nun im Master Branch auf Test verfügbar. Kannst Du sie bitte in der DB auswählbar machen?
