### ISSUE TITLE
Ergänzung Erläuterungen 4132

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#226]

**Comment by JE1982** [comment]
Erläuterungen und Lesehilfe erweitert. Json hochgeladen, (branch issue-226). squash und merge fehlgeschlagen. @jb3-2 bitte kontrollieren.

**Comment by jb3-2** [comment]
Merge hat bei Dir schon funktioniert, offenbar hatte travis ein klitzekleines Problem. 
@lcalmbach Kannst Du den aktuellen Zustand des Testsystems (Master Branch) live setzen?
