### ISSUE TITLE
Remove Shrinkpack

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#235]
closed in 10d5db0667b7b0842942356c95ecb64ba7b84fdb

**Comment by JamieMason** [comment]
Sorry to hear this, is there anything you can tell me to help  improve shrinkpack? Thanks 👍

**Comment by jb3-2** [comment]
@JamieMason Thanks for asking. Shrinkpack is great, but it solved a problem we currently do not face. Thus for simplicity's sake I removed it from the project. Keep up the good work! :+1:

**Comment by JamieMason** [comment]
Great, thanks for getting back to me @jb3-2 I appreciate it 👍
