### ISSUE TITLE
Dynamically update n and N in Befragungen

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#240]
![image](https://cloud.githubusercontent.com/assets/7261044/26722084/d0e75128-478e-11e7-8cef-6f3eaa13a1b7.png)

**Comment by larafaelivrin** [comment]
I think you were talking about this issue earlier today. It would be nice if this would be implemented soon. In my opinion this is momentarily more important than the map-tooltip enhancement.

**Comment by jb3-2** [comment]
Implemented in template befragungen001: xAxis label is dynamically changed, tooltip remains. 
@larafaelivrin @JE1982 Is this ok for you guys?

See http://issue-240--retailer-seawater-16683.netlify.com/chart.html?id=4127 

![screen shot 2017-10-05 at 09 00 30](https://user-images.githubusercontent.com/7261044/31214499-af76ce86-a9ab-11e7-859b-107811dd2029.png)

![screen shot 2017-10-05 at 09 00 41](https://user-images.githubusercontent.com/7261044/31214498-af5de5b0-a9ab-11e7-9d4b-4a50745ed819.png)

**Comment by larafaelivrin** [comment]
In which branch is this template implemented?

**Comment by larafaelivrin** [comment]
implement this for issue:328, id: 6178

**Comment by larafaelivrin** [comment]
implement this for issue:328, id: 6133

**Comment by larafaelivrin** [comment]
implement this for issue:328, id: 6213

**Comment by larafaelivrin** [comment]
- [ ] issue:328, id: 6133: Only n appears
- [ ]  issue:328, id: 6213: N and n does not appear
- [ ]  issue:328, id: 6213: Spacing between the columns is too small =>  less apce for legend, more space for chart

**Comment by larafaelivrin** [comment]
ID mit template befragungen001:

- [ ] 6178
- [ ] 6185
- [ ] 6186
- [ ] 6133
- [ ] 6136
- [ ] 6151
- [ ] 6213
- [ ] 6228
- [ ] 6146

**Comment by jb3-2** [comment]
I continued to improve this function in branch issue-328. Functionality in branch issue-240 is old now.
