### ISSUE TITLE
Säulen statt Linien bei Zeitreihen mit Missings

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#247]
OT merkt m. E. zu Recht an, dass Zeitreihen mit Missings i.d.R. nicht mit Linien dargestellt werden sollten, da sie Annahmen über die fehlenden Werte beinhalten. @jb3-2  Bitte das folgende Beispiel (4145) ändern. 
![4145](https://user-images.githubusercontent.com/20972660/27073401-000dcffc-5024-11e7-93b7-ee1018c60f8f.JPG)

**Comment by jb3-2** [comment]
Nach kurzer Diskussion mit KK haben wir festgestellt, dass dies bei weitem nicht der einzige Chart ist, der solche Werte als Linie darstellt. Wir müssen also alle aktuellen und sich in Bearbeitung befindlichen Charts durchgehen und dies dem entsprechend fixen. Kannst Du dies bitte KK in Auftrag geben?
