### ISSUE TITLE
Richtplan Indikatoren 2017

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#248]
In diesem branch werden die Richtplan Indikatoren 2017 bearbeitet.

**Comment by jb3-2** [comment]
I have added printing functionality and the mappie template from issue-241 and issue-244. See: 
- (in Chrome) http://issue-248--retailer-seawater-16683.netlify.com/print.html?Indikatorenset=Richtplan
- http://issue-248--retailer-seawater-16683.netlify.com/chart.html?id=9999

**Comment by jb3-2** [comment]
Todo JB:
- [ ] Add Legend to (at least) print version of map, as done in géoclip: 
![legende](https://user-images.githubusercontent.com/7261044/27374345-b34cc454-566b-11e7-8cd3-914d258a22fc.png)

**Comment by jb3-2** [comment]
Charts need to have the following sizes in word: 
- "Normal" format: 5.5 cm high x 8.5 cm wide
- "Wide" format: 5.45 cm high x 17.5 cm wide

**Comment by larafaelivrin** [comment]
Question regarding "I have added printing functionality and the mappie template from issue-241 and issue-244:"

http://issue-248--retailer-seawater-16683.netlify.com/print.html?Indikatorenset=Richtplan
**=> print.html; where should I use this?**
http://issue-248--retailer-seawater-16683.netlify.com/chart.html?id=9999
**=> Does not seem to work properly; bubbles do not appear**

**Comment by jb3-2** [comment]
Please leave the issue Open until the whole Feature is live on the Website.

**Comment by larafaelivrin** [comment]
http://issue-248--retailer-seawater-16683.netlify.com/chart.html?id=9999
=> Does again not seem to work properly; bubbles do not appear
=> I probably forgot to pull the data :/

**Comment by jb3-2** [comment]
Fixed. Proj4js library was not present in chart.html.

**Comment by jb3-2** [comment]
Todo: The following things need to be done fot the "Richtplan" set:

Pie charts

change colours of pies
sort pies ascending/thematically
label pies
Donought chart

Add template: https://www.highcharts.com/demo/pie-donut
Map

merge correct map template to the richtplan branch: issue-248 or explain KK how to use it correctly
legend for bubble map
in future: time series
Image Export:

Export Highcharts plots with correct StatA size.

**Comment by jb3-2** [comment]
FYI Pie size (are) is proportional to value: 

![image](https://user-images.githubusercontent.com/7261044/28360356-7e056d44-6c75-11e7-8ea0-9a307f76ec31.png)

**Comment by larafaelivrin** [comment]
see To Dos here: https://docs.google.com/document/d/1TmObEA7VrUmgBYr4LABc8iBznMa0s_-zUhnyuIaiywc/edit?usp=sharing
