### ISSUE TITLE
Portalansicht: Keine Unterthemenauswahl zeigen, wenn kein Thema (resp. alle Themen) gewählt ist

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#25]
alternativ: sobald ein Unterthema ausgewählt wird, wird automatisch auch das dazugehörige Thema ausgewählt

**Comment by JE1982** [comment]
Setansicht: Es stellen sich die gleichen Fragen. Ich würde zweimal die gleiche Lösung bevorzugen. Also
a) keine Unterthemen/Unterkapitel anzeigen, solange kein Thema/Kapitel gewählt ist
b) sobald ein Unterkapitel(Unterthema gewählt ist, wird automatisch auch das dazugehörige Thema/Kapitel gewählt.

Präferenz: zurzeit keine.

**Comment by jb3-2** [comment]
Variante A umsetzen, zeitgleich Sortierung ausblenden #29
