### ISSUE TITLE
Cloud9 URL /index.html/chart.html => chart.html

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#251]
Cloud9 Url should not open as https://stata-master-larafaelivrin.c9users.io**/index.html/chart.html?id=5116**&suppressNumberInTitle=true but as  https://stata-master-larafaelivrin.c9users.io/**chart.html?id=5116**&suppressNumberInTitle=true

**Comment by jb3-2** [comment]
If the runner is configured to open the root folder instead of /index.html, the links work flawlessly. Please make sure the runner is configured as described in readme.md.
