### ISSUE TITLE
Exporting plots with StatA size 

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#253]
I am trying to export the plots with the predefined StatA sizes. Unfortunately I have not succeeded so far. 
As changing the width and height paramters in the chart configuration is not optimal (if the size of the chart is changed also other paramters need to be changed; e.g. legend placement and labels),  I tried to change the width and height paramters with help of the exporting configuration. This, however, has so far not let to a satisfying result, mainly for two reasons:

1. The image quality is blurry and thus useless

2. Although I tried to export a plot with the StatA size (8.5*5.5cm)  by manually adapting the pixel size paramters I have so far not been able to generate a plot with the StatA size. I have the feeling that the width and height paramters are somehow connected to each other. 

Here I provide my code: 

 exporting: {
        width: 220,
        height: 80,
        scale:4
        //sourceWidth: 321,
        //sourceHeight: 210,
},

**Comment by jb3-2** [comment]
Charts need to have the following sizes in word:

"Normal" format: 5.5 cm high x 8.5 cm wide
--> in [id].js define chart.height and chart.width as **415 x 641 px**
"Wide" format: 5.45 cm high x 17.5 cm wide
--> in [id].js define chart.height and chart.width as **411 x 1283 px**

You should define chart's dimensions in chart.width and chart.height, not in exporting.width and exporting.height. 

See http://issue-248--retailer-seawater-16683.netlify.com/print.html?Indikatorenset=Test

**Comment by larafaelivrin** [comment]
My thoughts of last Monday summarized: 

Resolution (dpi)  = f(pixel ,inches)
z.B. 100 dpi = 1000*1000pixel, mit 10*10 inches 

Pixel wird durch export width und height definiert
- http://api.highcharts.com/highcharts/exporting.sourceWidth
- http://api.highcharts.com/highcharts/exporting.sourceHeight

Resolution wird durch export scale definiert
- http://api.highcharts.com/highcharts/exporting.scale

Daraus kann man dann, wenn ich alles richtig verstanden haben, die Bilder in der gewünschten Grösse berechnen. Geschafft habe ich dies jedoch noch nicht, aber dies war der Lösungsweg, an den ich am Mo gedacht habe…
