### ISSUE TITLE
Richtplan: To Do

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#254]
The following things need to be done fot the "Richtplan" set:

**Pie charts**
- change colours of pies
- sort pies ascending/thematically
- label pies

**Donought chart**
- Add template: https://www.highcharts.com/demo/pie-donut

**Map**
- merge correct map template to the richtplan branch: issue-248 or explain KK how to use it correctly
- legend for bubble map
- in future: time series

**Image Export:** 
- Export Highcharts plots with correct StatA size.

**Comment by jb3-2** [comment]
Copied text to https://github.com/StataBS/indikatoren/issues/248
