### ISSUE TITLE
Integratives Projekt: Population pyramid

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#255]
As we analyze ages it would be nice to show the results of this projects with help of this template: https://www.highcharts.com/demo/bar-negative-stack

**Comment by larafaelivrin** [comment]
I tried to configure the polulation pyramid in branch issue-303 for 9005.js. So far without success.

**Comment by jb3-2** [comment]
I have created a working first version, see 37546583ef32bdaa289bba24d7b402dae8e6689d

**Comment by jb3-2** [comment]
todo: Move code into populationPyramid001.js
