### ISSUE TITLE
Update Set Wohnraumentwicklung 2017

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#256]
Replaces #250 and #239. 

Input by @JE1982: 
- [x] 4139: Wrong Structure
- [x] 4136: Wrong Structure
- [x] 4153: Scale ends too early

**Comment by JE1982** [comment]
4134 corrected in Access

**Comment by JE1982** [comment]
4136: falsche Struktur
4138: unterschiedliche Farben für Bestand und Quoten
4143: die gelbe Linie ist nicht konsequent ein- oder ausgeblendet. 
4147: Abstand zwischen Methodik und "siehe" in den Links. (Ich weiss nicht, wie ich das selber ändere)
4152: Skala hört zu früh auf
4127: Legendenbeschriftung und Lesehilfe im Acces korrigiert. json neu laden.

**Comment by jb3-2** [comment]
Work item closed with commit 6a6ae569214b88aec5fe55886d224e05228410bb
