### ISSUE TITLE
Quellen Wohnraumentwicklung laden

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#26]
die Quellen in den Indikatoren zur Wohnraumentwicklung sind in der DB erfasst, das neue json ist generiert und am Platz. Bitte live schalten.

**Comment by jb3-2** [comment]
Mache ich voraussichtlich heute Abend ca. 2230.

**Comment by JE1982** [comment]
👍

Von meinem iPhone gesendet

Am 22.08.2016 um 18:14 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


Mache ich voraussichtlich heute Abend ca. 2230.

**Comment by jb3-2** [comment]
Implemented in d55a340b096d915193d702559fc04c0dc748eee4
It's now live.
