### ISSUE TITLE
Umweltbericht Charts Strict Mode Violation

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#265]
@bl99 Indikatorenportal works in [JavaScript Strict Mode](https://www.w3schools.com/js/js_strict.asp). In your code you forget to declare variable max_labels. Can you please add the line 
`var max_labels;`
to your code? Thanks.

![image](https://user-images.githubusercontent.com/7261044/28454608-2900bfb4-6dfc-11e7-8b3e-de9a974fa135.png)

**Comment by bl99** [comment]
JS variable declarations added for several undeclared and tested in strict mode. 
@jb3-2 please test in indikatorenportal.
