### ISSUE TITLE
Umwelt: Only display BS Data

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#266]
(JE) Weisst du, weshalb auch BL-Werte angezeigt werden? falscher Branch? --> (jb) Nein. @bl99 liefert die Daten beider Kantone, obwohl nur BS angezeigt werden sollte. Nur er kann dies fixen. 
Siehe z.B. http://ub.basleratlas.ch/?format=stata&k=bs&i=0101 

![image](https://user-images.githubusercontent.com/7261044/28362249-fc42d268-6c7b-11e7-9c1f-2f204212f07d.png)

**Comment by bl99** [comment]
Fehler behoben. Lag daran, dass nur k=BS statt k=bs akzeptiert wurde
