### ISSUE TITLE
Mappie: Pie size

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#272]
The result of the **pie size** is still not satisfactory as many pies no appear too small and cannot bee seen visually: e.g. 5824 and 5839
Also it should be possible to **control the visibility of the pies**. This is necessary because they sometimes cover up the whole "Wohnviertel" and thus the tooltip of the "Wohnviertel" does not work. 
An additional idea: A **shared tooltip** that shows the value for the given year and the difference between two years for each Wohnviertel would be very nice!

**Comment by jb3-2** [comment]
Have you tried playing around with the size function on line 217 and 220?

E.g. increase pieSizeFactor on line 217, or add a constant number (e.g. 10) to the result on line 220 of this file: https://github.com/statabs-test/indikatoren/blob/issue-248/charts/templates/5824.js

**Comment by larafaelivrin** [comment]
The problem with the pie size is that while **large values** can be seen very good the **small values** are almost hidden as they appear too tiny:

![image](https://user-images.githubusercontent.com/23261816/28518871-ca4d206e-7069-11e7-9800-04a8539c6eaf.png)

**Comment by jb3-2** [comment]
How about this (as implemented in http://issue-248--retailer-seawater-16683.netlify.com/chart.html?id=5824): 


//Increase or decrease default pie size
var pieSizeFactor = 0.35;
//Minimal pie size: a summand added to the calculated size
var pieSizeMin = 5;
//Negative values: return absolute value
var size = pieSizeMin + Math.abs(this.chart.chartWidth / 11 * pieSizeFactor * zoomFactor * data.value / maxNumber); 

![i 03 2 05824](https://user-images.githubusercontent.com/7261044/28559630-9895fef2-7117-11e7-82fb-571dcb6cbbc5.png)
