### ISSUE TITLE
Zielwert fehlt

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#273]
Siehe Chart 5797 (Umwelt Indikator 1504)

![image](https://user-images.githubusercontent.com/7261044/28917703-ccb73cec-7846-11e7-8f60-4cdd1877763f.png)

**Comment by jb3-2** [comment]
Dito Chart 42914 (Umwelt Indiaktor 1512)

**Comment by bl99** [comment]
Solved. Ziel-/Grenzwerte were not handled correctly in the background when using &k=bs
