### ISSUE TITLE
Filter in Portal anpassen

### ISSUE THREAD

**Issue by grilli73** [StataBS/indikatoren#3]
Themenfilter auf single select; als default alle Ind. ungefiltert anzeigen.
Zuätzlich neuer Filter für Unterthemen (Position rechts neben Sortierung, analog Kapitelfilter im Set)

**Comment by jb3-2** [comment]
- [x] Themenfilter auf single select; als default alle Ind. ungefiltert anzeigen. Implemented in 6b891cb7965db5b20aea6a04191313f3ca59aac8
- [ ] Zuätzlich neuer Filter für Unterthemen (Position rechts neben Sortierung, analog Kapitelfilter im Set)
