### ISSUE TITLE
Integratives Projekt 2017

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#303]
In diesem branch werden die Plots für das "integrative Projekt" bearbeitet

**Comment by larafaelivrin** [comment]
Why does this link not work:

**Comment by jb3-2** [comment]
Both links work on my machine.

**Comment by larafaelivrin** [comment]
Yes, the first link works but it does not work properly: It shows all indicators instead of showin gonly the indicators of the set: Int-Proj. So far I have not figured out why.

**Comment by larafaelivrin** [comment]
Indikatorenset has a different name, this link works: 
http://issue-303--retailer-seawater-16683.netlify.com/?Indikatorenset=IntProj

**Comment by jb3-2** [comment]
The private repository is not available on netlify! If you want to look at the results, use the c9.io apache webserver. Let me know if you need help. J.

**Comment by JE1982** [comment]
@larafaelivrin: can this one be closed?

**Comment by larafaelivrin** [comment]
yes, this branch can be closed @JE1982 @jb3-2
