### ISSUE TITLE
Map: Proportional Scaling

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#306]
I am wondering why the **bubble size** of the "big bubble legend" of the ID 5202  and ID 5814 are not equal. The **bubble size** of the "small bubble legend" of these ID visually appear to be equal and the **difference between the values of the bubble legend** are equal: 
- 5202: Difference of small and big bubble legend: 300 (30/0.1)
- 5914: Difference of small and big bubble legend: 300 (3/0.01)

Links to the above mentioned Maps:
5202: http://issue-248--retailer-seawater-16683.netlify.com//chart.html?id=5202&indikatorensetView=true&suppressNumberInTitle=true
5814: http://issue-248--retailer-seawater-16683.netlify.com//chart.html?id=5814&indikatorensetView=true&suppressNumberInTitle=true

I have troubles understanding this formula as I do not understand all variables involved: 
var size = pieSizeMin + chart.chartWidth / 11 * pieSizeFactor * zoomFactor * Math.sqrt(Math.abs(value)) / maxAbsNumber;

**Comment by jb3-2** [comment]
There were several problems with the chart: 
- In the legend, the bubbles had stroke-width 0, whereas on the map they had stroke-width 1. Thus the bubbles in the legends had a diameter that was 2 pixels too small. 
- It was possible to define a minimal bubble size. Now this is fixed to 0. A bubble with double area of another bubble now represents value that is twice as large.
