### ISSUE TITLE
Redesign chart 5888 colors for color deficient people

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#321]
Red and green should not be used as contrasting colors.

**Comment by larafaelivrin** [comment]
Absolutly correct!

**Comment by larafaelivrin** [comment]
How can I use HEX colours in this function: 

//define different colors for positive and negative values
                        var color = function(){
                        	return (data.value >= 0) ? '689199' : 'FABD24';
                        };

?

**Comment by jb3-2** [comment]
Implemented in cfc871b8d779fb6502a810b026fc74f5f31caac5
