### ISSUE TITLE
Wanderung 2017

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#325]
In this branch the set of indicators for "Wanderungen" are being worked on.

**Comment by larafaelivrin** [comment]
To Do List: 

https://docs.google.com/spreadsheets/d/1WfPi1uMtCzyGgZpR8F29Dq1_k_LFQ48d9wE3rzM3IRQ/edit?usp=sharing

**Comment by jb3-2** [comment]
All done from my side.

**Comment by jb3-2** [comment]
Important: Development occurs on the private github repo, not here in the public.

**Comment by jb3-2** [comment]
As of now, development is again on this test server in the open.

**Comment by jb3-2** [comment]
Current state: http://issue-325--retailer-seawater-16683.netlify.com/?Indikatorenset=Wanderungen

**Comment by larafaelivrin** [comment]
Can you document how you transferred the private to the public branch?

**Comment by jb3-2** [comment]
As discussed, I will show you and we'll note it down.
