### ISSUE TITLE
Portal: Thema "50 Regelmässige Befragungen" umbenennen in "50 Befragungen"

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#33]
ist das möglich, ohne dass aus der DB ein anderes Feld mitgeliefert wird? Grund: In der DB können wir es nicht umbenennen, man könnte höchstens ein weiteres Feld anlegen, aber für diese (bis jetzt...) eine Umbenennung ist das etwas übertrieben

**Comment by jb3-2** [comment]
Bei Radio Buttons: Unterscheidung in Text und Value einführen und in diesem Fall den Text anders als den Value definieren.

**Comment by jb3-2** [comment]
Können wir dies niocht besser Datenbankseitig lösen, so dass im json schon der richtige Text erscheint?

**Comment by jb3-2** [comment]
Ist in der DB umgesetzt.
