### ISSUE TITLE
Quellenangabe zum Teil zu Nahe an Achse

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#34]
![2016-08-25 11_20_43-statistik - indikatorenportal](https://cloud.githubusercontent.com/assets/20972660/17963590/8d279bec-6ab6-11e6-9f62-94800dea7e3e.jpg)

Bei den meisten andern Charts ist der Abstand i.O. Kannst Du das einzeln beeinflussen? Oder was ist da passiert?

**Comment by jb3-2** [comment]
Nicht reproduzierbar bei mir. Bei mir werden in allen 3 Browsern die x-Achsen Labels horizontal geschrieben, dann bleibt automatisch genügend Platz für die Quellenangaben.

**Comment by jb3-2** [comment]
Bitte in neustem Firefox austesten. Habe in Chart I.2.01.0015 den marginBottom erhöht, damit dort genügend Platz besteht, siehe Commit 99048c72d0a8012e6cf19e28b651cf251eccb253
