### ISSUE TITLE
x offset of the legend when legend position is on top of the chart

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#347]
The x offset of the legend should be at the start of the x-Axis when the legend position is on top of the chart.

**Comment by larafaelivrin** [comment]
Example: branch issue-328, ID: 6160

**Comment by jb3-2** [comment]
OK I start implementing this in the branch and chart you have named above.

**Comment by jb3-2** [comment]
Implemented in 2e13cd0

**Comment by jb3-2** [comment]
Moved function to base template: if legend is top-left, and no x is given, the x is set. 
Implemented for the following templates: 
- [x] template001
- [x] line001

Todo: implement for all other templates, remove x from chart config where necessary.
