### ISSUE TITLE
Mappie: shared tooltip

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#355]
I argue that it would be nice if the tooltips of the maps are shared: E.g. when hovering over Kleinbasel the choropleth value as well as the point value (circle or bar) should be shown together in one tooltip.

**Comment by jb3-2** [comment]
How about this one: http://issue-341--retailer-seawater-16683.netlify.com/chart.html?id=9997

![image](https://user-images.githubusercontent.com/7261044/31017440-bf362f56-a528-11e7-9865-f719d50b38fb.png)

**Comment by jb3-2** [comment]
Added to branches issue-341 and issue-325 in chart 9997.

**Comment by JE1982** [comment]
@jb3-2 is there something missing here?

**Comment by jb3-2** [comment]
@larafaelivrin has already used this technique in chart 6022 (see https://statabs.github.io/indikatoren/chart-details.html?id=6022), thus I close this issue now.
