### ISSUE TITLE
Separate thumbnails für Portal- und Indikatorenset-Ansicht

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#36]
bis jetzt sieht man in der Setansicht das "Bild" aus der Portalansicht und somit das falsche Kürzel. Anstelle des Kundenkürzel sieht man das Kürzel aus der DB.

**Comment by jb3-2** [comment]
Das ist nicht trivial. Aktuell gibt es für jeden Indikator ein SVG Bild. Darin ist der Titel gespeichert. Sollten wir den Titel dynamisch machen müssen (abhängig davon, ob der Indikator in der Portal- oder Indikatorenset-Ansicht dargestellt wird), so müssten wir vor der Darstellung im Browser noch den Titel im SVG ändern. Das ist möglich und sollte nicht viel Performance im Browser kosten. 

Ist dies unabdingbar für den Go-Live, oder kann das ein wenig warten?

**Comment by JE1982** [comment]
Das kann mit Sicherheit warten. Kein Problem.

Von meinem iPhone gesendet

Am 17.09.2016 um 17:08 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


Das ist nicht trivial. Aktuell gibt es für jeden Indikator ein SVG Bild. Darin ist der Titel gespeichert. Sollten wir den Titel dynamisch machen müssen (abhängig davon, ob der Indikator in der Portal- oder Indikatorenset-Ansicht dargestellt wird), so müssten wir vor der Darstellung im Browser noch den Titel im SVG ändern. Das ist möglich und sollte nicht viel Performance im Browser kosten.

Ist dies unabdingbar für den Go-Live, oder kann das ein wenig warten?

**Comment by jb3-2** [comment]
Da ich nun die Thumbnails beim automatischen build Prozess erstelle, kann ich sie auch gleich doppelt erstellen.
