### ISSUE TITLE
Portalansicht: Indikatoren aus dem Set "Übrige" sollen keine Setzugehörigkeit mehr angezeigt haben

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#38]
Bei allen Indikatoren des Sets "Übrige" soll der Hinweis "Dieser Indikator ist Bestandteil des Indikatorensets "Übrige"" ausgeblendet werden.

**Comment by jb3-2** [comment]
Wie wäre es, wenn im json das Geld Indikatorenset leer bliebe für diese Indikatoren? Dann wäre es für mich einfacher, den Satz "...gehört zum Indikatorenset xy" wegzulassen
