### ISSUE TITLE
Link to Indikatorenset on every Chart

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#390]
Till now we show the link "Dieser Indikator ist Bestandteil des Indikatorensets "xyz" only in the portal-view. I would like to show it in the set-view too. 

And in the set-view I would like to have the possibility to add the "Kapitel" to this sentence. 
@jb3-2: where is it generated an can we add  "Kapitel"-Info?

**Comment by jb3-2** [comment]
In Indikatorenset View: Add same text as in portal view regarding (Indikatorenset), plus add <br/> plus contents of variable "stufe1".

**Comment by jb3-2** [comment]
@JE1982 How about this?

![image](https://user-images.githubusercontent.com/7261044/32104713-ead9842e-bb25-11e7-94a4-4445897aad54.png)

**Comment by JE1982** [comment]
I would prefer a break and no brackets. And I think we should add something (e.g. "Bereich") to the chapter number in Access in the set "Wohnviertel". In all other sets the chapters are titled by names not only numbers. I will do this.

**Comment by jb3-2** [comment]
JE: Now this way it's OK: 
![image](https://user-images.githubusercontent.com/7261044/32891980-0000759c-cad5-11e7-881c-ae9de699c73f.png)

**Comment by jb3-2** [comment]
JE has to update all metadata so that no Stufe1 starts with a number. Then uplaod and rebuild by JB.

**Comment by jb3-2** [comment]
@JE1982 I have checked all metadata and corrected some small mistakes. Todo: Re-Upload metadata of a certain kennzahlenset, where the space after '1'in stufe1 is missing.

**Comment by jb3-2** [comment]
@JE1982 Here you can check all changes between the current master branch and the issue-390 branch: https://github.com/statabs-test/indikatoren/compare/master...statabs-test:issue-390?expand=1 

If you want to see all charts, click here: http://issue-390--retailer-seawater-16683.netlify.com/
To check the newly formed link to the Indikatorenset, use the Indikatorenset view, e.g. like this (see screenshot below): http://issue-390--retailer-seawater-16683.netlify.com/?Indikatorenset=Gesellschaftlicher-Zusammenhalt 

![image](https://user-images.githubusercontent.com/7261044/32938811-b3356200-cb7d-11e7-82ad-f218c410553a.png)

**Comment by jb3-2** [comment]
@JE1982 This still waits for your feedback, see comments above.

**Comment by JE1982** [comment]
checked all jsons. Some of them have to be uploaded again. Where shall I put them?

**Comment by jb3-2** [comment]
Just put them somwehere on P: and send me the link, thanks!

**Comment by jb3-2** [comment]
@JE1982 Some stufe1 Texts are still less than ideal: 
- Richtplan: "Siedlung - Wohnen", "Siedlung - Wirtschaft"
- Wohnraumenticklung: "Leitgedanke"

![screen shot 2017-11-23 at 14 51 37](https://user-images.githubusercontent.com/7261044/33176018-dacec95c-d05d-11e7-8ccd-90664c7fbf1b.png)

![screen shot 2017-11-23 at 14 52 26](https://user-images.githubusercontent.com/7261044/33176062-06b67876-d05e-11e7-9dea-253e2b630162.png)

**Comment by JE1982** [comment]
i have to check how we should name stufe 1 in Richtplan-Set. In Wohnraumentwicklung-Set we stay with Leitgedanke because it's an exeption. the other stufe 1 names start with "Ziel".
