### ISSUE TITLE
OGD Landing Page

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#396]
Create a landing page for indicators from opendata.swiss. The chart should be nicely embedded into the bs.ch CI/CD, contain Lesehilfe / Erläuterungen, a link to the tsv data file, and a link to the indikatoren portal.

**Comment by jb3-2** [comment]
@grilli73 @JE1982 Here's my first version: http://issue-396--retailer-seawater-16683.netlify.com//chart-details.html?id=5822 

Please comment! J.

**Comment by grilli73** [comment]
Looks good, but Indikatoren in the top navigation should rather link directly to the portal view:
http://www.statistik.bs.ch/zahlen/indikatoren/portal.html

Thx, N.

**Comment by OTHODO** [comment]
Hi Jonas  Von meiner Seite gibt's nix zu beanstanden. thx! LG Oli

**Comment by JE1982** [comment]
tiptop. it should be possible to have this option in the hamburger-menu too.

**Comment by jb3-2** [comment]
How about the menu points "Einzelansicht" --> chart-details.html and "Einbetten" --> chart.html
