### ISSUE TITLE
Scalebar doesn't appear correctly on image on phone

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#397]
![screenshot_20171029-095205](https://user-images.githubusercontent.com/23261816/32142471-a0b6f0be-bc8f-11e7-89f2-6589e4109451.png)

**Comment by jb3-2** [comment]
Reproducible in Chrome on iPhone eith iOS 11, not reproducible in Mobile Safari. 

Problem does only appear for pre-created svg, not Highcharts chart. 

![e39b15cd-d616-4fa1-8071-642602baaaa2](https://user-images.githubusercontent.com/7261044/32143378-a455d01e-bca8-11e7-9c93-fd730d3a4fb4.png)


![edcf5445-1bcd-4731-bb5f-af76bb8bafc0](https://user-images.githubusercontent.com/7261044/32143361-774dd436-bca8-11e7-9945-a1bc6b2647bb.png)
