### ISSUE TITLE
Define order of chapters in indikatorenset view

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#398]
The chapters of the set "Legislaturplan" are not ranked in the correct order here (http://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Legislaturplan). Chapter 10 is shown previous to chapter 2. The order seems to be alphabetic and not in order of the "orderKey" out of the json-file. @jb3-2: Will this be shown correctly in the live-system?

**Comment by jb3-2** [comment]
That was easy. 

@JE1982 Can you please help with testing if this reordering has any side effects in Portla View or other Indikatorensets?

- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Legislaturplan
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Gesellschaftlicher%20Zusammenhalt
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Integration%20kompakt
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Richtplan-kurz
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Umwelt
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Wohnraumentwicklung
- [ ] https://issue-328--retailer-seawater-16683.netlify.com/?Indikatorenset=Wohnviertel

- [ ] https://issue-328--retailer-seawater-16683.netlify.com

**Comment by JE1982** [comment]
it works for all sets except for the Wohnviertel-Set. Is there an order-key in the json-file or do we have to renew them?
and in the Portal-view we have all the themes (of the

**Comment by jb3-2** [comment]
@JE1982 What do you mean with "and in the Portal-view we have all the themes (of the Umweltbericht)"? Is that something that should not be the way it currently is?

@JE1982 We probably have to re-import the Wohnviertel Metadata in order to make it work. Can you please upload the json files to branch issue-328 (or send the files to me via email)?

![image](https://user-images.githubusercontent.com/7261044/32834807-3b07c4aa-ca04-11e7-8505-ea758910f4e1.png)

**Comment by jb3-2** [comment]
Je mentioned: Richtplan in Indikatorenset View is ordered incorrectly

**Comment by jb3-2** [comment]
Has been implemented in Branch 328 (Legislaturplan), thus closing this issue for now.

**Comment by jb3-2** [comment]
See Screenshot above: Kapitel 'Siedlung - Wohnen' should be above the 2nd Kapitel.

**Comment by jb3-2** [comment]
This now works after merging master and rebuilding.
