### ISSUE TITLE
Set Legislaturplan-Print

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#399]
@jb3-2: Build charts and check which ones have to get a bigger size

**Comment by JE1982** [comment]
- 6275: engere Skalierung
- 6276: engere Skalierung
- 6277: Komma als Dezimaltrennzeichen
- 6279: Kommas als Dezimaltrennzeichen
- 6280: engere Skalierung
- 6281: Skalierung rechte Achse an Gitterlinien anpassen
- 6282: engere Skalierung
- 6283: engere Skalierung
- 6290: Legende: Umbruch nach "/"
- 6294 engere Skalierung
- 6295: engere Skalierung
- 6296: engere Skalierung
- 6297: kein Scrollbar; engere Skalierung; keine Zeitraum-Beschriftung
- 6298: engere Skalierung
- 6302: engere Skalierung
- 6303: keine bullets; engere Skalierung
- 6307: engere Skalierung
- 6310: Legednebeschriftung anpassen: tCO2 raus
- 6313: engere Skalierung
- 6314: engere Skalierung; Prozentangaben in Achsenbeschriftung runden (auf 5 resp. 10-er Schritte)
- 6315: engere Skalierung; 2 Dezimalstellen in Achsenbeschriftung
- 6316: engere Skalierung
- 6318: engere Skalierung
- 6319: engere Skalierung
- 6320: engere Skalierung
- 6324: engere Skalierung
- 6326: engere Skalierung
- 6327: engere Skalierung
- 6328: engere Skalierung
- 6330: engere Skalierung
- 6338: engere Skalierung; Legendenbeschriftung zweispaltig
-

**Comment by jb3-2** [comment]
Merged into branch issue-328, thus closing this issue.
