### ISSUE TITLE
Umwelt-charts in Portal-View

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#402]
in the portal view there should be only Umwelt-Charts with Lesehilfe and Erläuterungen. All other Umwelt-Charts should not be showed. 

The list with the Charts to be part of the portal-view is here: \\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\4_Monitoring_Controlling\Kennzahlensysteme\Umweltberichterstattung_BS_BL\Admin\UB_Indikatorenliste_für_Separierung_BS.xlsm  

@jb3-2: could you please delete the other ones from portal-view?

**Comment by jb3-2** [comment]
@JE1982 Implemented here, please test if ready for go live: 

- http://issue-402--retailer-seawater-16683.netlify.com/
- http://issue-402--retailer-seawater-16683.netlify.com/?Indikatorenset=Umwelt-

**Comment by JE1982** [comment]
there is no Chart from Umwelt in the Portal-view now. is this done on purpose and the ones with Lesehilfe and Erläuterungen will follow?

**Comment by JE1982** [comment]
@jb3-2, @bl99: hier meine Rückmeldungen. Bitte nochmals alle raus, bis wir das Gröbste bereinigt haben.  

4323: Fehler in Quelle
4230: Rubrikenbeschriftungen ohne "BS", Quelle unvollständig
4223: Rubrikenbeschriftungen ohne "BS", Quelle unvollständig
4229: Rubrikenbeschriftungen ohne "BS", Quelle unvollständig
4275: Der Untertitel ist überflüssig
4321: Quelle unvollständig
4254: "BS" in der Rubrikenbeschriftung überflüssig
4322: Rubrikenbeschriftungen ohne "BS", Quelle unvollständig
4249: "BS" in der Rubrikenbeschriftung überflüssig
4299: Quelle unvollständig
4269: "BS" in Rubrikenbeschriftung weg
4224: Quelle unvollständig
4221: Quelle unvollständig
4281: falsche Anführungszeichen in Erläuterungstext
4279: falsche Anführungszeichen in Erläuterungstext
4325: Rubrikenbeschriftungen ohne "BS", Quelle unvollständig
4318: raus, weil Kind von einem anderen. -> visible in Portal = false setzen.

Generell: 
1. Wenn nur eine Datenreihe angezeigt wird, ist diese mit "Kanton Basel-Stadt" angeschrieben. Das ist eigentlich nicht nötig, weil es ja nix anderes zu zeigen gibt. 
2. Ich würde jeweils ein "in" zu Beginn des Untertitels vorziehen. Ich weiss, wir hattens mal mit KB davon, ich bin jetzt einfach schon mehrfach darüber gestolpert. (nice-to-have)

**Comment by jb3-2** [comment]
@JE1982 Umwelt charts are now hidden in portal, please test for go-live: 
http://issue-402--retailer-seawater-16683.netlify.com/

**Comment by JE1982** [comment]
@jb3-2 ready for go live

**Comment by jb3-2** [comment]
@JE1982 "Bitte nochmals alle raus, bis wir das Gröbste bereinigt haben." --> Umwelt charts are now invisible in portal view on live system.

**Comment by bl99** [comment]
@JE1982: _kursives_ ist erledigt bzw. bereit zum erneuten import:

_4323: Fehler in Quelle_
4230: _Rubrikenbeschriftungen ohne "BS",_ Quelle unvollständig
4223: _Rubrikenbeschriftungen ohne "BS",_ Quelle unvollständig
4229: _Rubrikenbeschriftungen ohne "BS",_ Quelle unvollständig
4275: Der Untertitel ist überflüssig
4321: Quelle unvollständig
4254: _"BS" in der Rubrikenbeschriftung überflüssig_
4322: _Rubrikenbeschriftungen ohne "BS",_ Quelle unvollständig
4249: _"BS" in der Rubrikenbeschriftung überflüssig_
4299: Quelle unvollständig
4269: _"BS" in Rubrikenbeschriftung weg_
4224: Quelle unvollständig
4221: Quelle unvollständig
4281: _falsche Anführungszeichen in Erläuterungstext_
4279: _falsche Anführungszeichen in Erläuterungstext_
4325: _Rubrikenbeschriftungen ohne "BS", _Quelle unvollständig
4318: raus, weil Kind von einem anderen. -> visible in Portal = false setzen.
Generell:
_1.	Wenn nur eine Datenreihe angezeigt wird, ist diese mit "Kanton Basel-Stadt" angeschrieben. Das ist eigentlich nicht nötig, weil es ja nix anderes zu zeigen gibt._
2.	Ich würde jeweils ein "in" zu Beginn des Untertitels vorziehen. Ich weiss, wir hattens mal mit KB davon, ich bin jetzt einfach schon mehrfach darüber gestolpert. (nice-to-have)

Quellen und Untertitel: sind auf der Pendenzenliste

@lcalmbach und @jb3-2: bitte Daten und Grafiken der Umweltbericht-Indikatoren neu importieren

**Comment by jb3-2** [comment]
Merged #395 into this branch, now data download links to tsv file on server.
