### ISSUE TITLE
Richtplan is not equal to Richtplan-kurz

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#403]
@jb3-2: please delete the following Charts:
- 5205
- 5831
- 5902
- 6237
- 5827
- 5828
- 5824
- 5804
- 6219
- 5812
- 5903
- 5807
- 5829

**Comment by jb3-2** [comment]
- [ ] - 5205
- [ ] - 5831
- [ ] - 5902
- [ ] - 6237
- [ ] - 5827
- [ ] - 5828
- [ ] - 5824
- [ ] - 5804
- [ ] - 6219
- [ ] - 5812
- [ ] - 5903
- [ ] - 5807
- [ ] - 5829

**Comment by jb3-2** [comment]
@JE1982 The mentioned indicators are now removed from live.
