### ISSUE TITLE
Portalansicht: Unterthema zurücksetzen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#41]
Wenn man in der Übersicht ein Thema wählt, das nur ein Unterthema hat (Bsp. Landwirtschaft) und danach wieder auf "Alle" klickt, bleibt der Filter auf dem Unterthema von Landwirtschaft stehen, was zur Folge hat, dass nicht alle Indikatoren, sondern immer noch nur diejenigen von Landwirtschaft angezeigt werden. 

Kannst Du implementeiren, dass wenn man in der Themenauswahl auf "Alle" klickt, dann automatisch der Unterthemenfilter deaktiviert wird und auch effektiv alle Indikatoren angezeigt werden?

**Comment by jb3-2** [comment]
Bitte um Testing, ob das Verhalten von Stufe1/Stufe2 und thema/unterthema nun überall sauber funktioniert.

**Comment by JE1982** [comment]
Funktioniert perfekt!

**Comment by jb3-2** [comment]
👍

JE1982 <notifications@github.com> schrieb am Fr., 16. Sep. 2016, 15:05:
