### ISSUE TITLE
Indikator 4921

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#413]
- is member of Indikatorenset "Übrige"
- Metadata says "visibleInPortal" = true
- can't find him in Portal-view on live-sytem 
@jb3-2: can you check the history of this Chart?

**Comment by JE1982** [comment]
same goes for ID = 4923

**Comment by jb3-2** [comment]
@JE1982 Chart 4921 was never in the system. I found this using the following command lines: 

git log --full-history -- data/4921.tsv
git log --full-history -- images/portal/4921.svg
git log --full-history -- charts/templates/4921.js
git log --full-history -- metadata/single/4921.json    

see https://stackoverflow.com/questions/7203515/git-how-to-search-for-a-deleted-file-in-the-project-commit-history
