### ISSUE TITLE
Similar Indicators

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#416]
Based on metadata (e.g. keywords), the link list should contain a link to similar charts.

**Comment by JE1982** [comment]
this already exists for Dotplots/Maps by "andere Darstellungsform dieser Daten". What is needed besides this?

**Comment by jb3-2** [comment]
The idea was that the system points to charts that are similar based in Schlageort and other metadata. Now that schlagwort is gone we need to re-evaluate if this is possible and makes sense.
