### ISSUE TITLE
Gliederung Gesellsch. Zusammenhalt live setzen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#42]
Gliederung ist angelegt und hinterlegt. Neues json ist upgeloaded. Bitte live setzen.
Danke und Gruss
J.

**Comment by jb3-2** [comment]
Ist gemacht. Sollte man die Unterkapitel anders nummerieren, z.B. 1.1, 2.1 etc.?

**Comment by JE1982** [comment]
Ja, das ist eine gute Idee. Ich mache das morgen früh.

LG und gute Nacht
J.

Von meinem iPhone gesendet

Am 14.09.2016 um 21:16 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


Ist gemacht. Sollte man die Unterkapitel anders nummerieren, z.B. 1.1, 2.1 etc.?

**Comment by JE1982** [comment]
ist gemacht und neues json geladen
