### ISSUE TITLE
Richtplan: Improvement

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#421]
In this branch the set of indicators for "Richtplan" are improved

**Comment by larafaelivrin** [comment]
- [ ] Templates: Replace "tickColor": "#FFFFFF" with"tickLength": 0 
- [ ] 5891: tickInverval: 2
- [ ] 5203 & 5816: plotLines: zIndex =

**Comment by jb3-2** [comment]
KK via EMail: 

Lieber JB,

Danke für die Anpassungen der Wanderung-Indikatoren. Es sieht alles sehr gut aus. 
Die Anpassungen im branch issue-421 sind gemacht:
https://github.com/StataBS/indikatoren/issues/421
Ich habe viele, aber nicht alle der 125 neu generierten Bilder durchgesehen. Es scheint, als ob die tickLength Anpassung keine unerwartete Auswirkung hat.
Somit ist dieser Branch bereit veröffentlicht zu werden.
LG, KK
