### ISSUE TITLE
Integrating Cercle Indicateurs

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#426]
Add 12 indicators from 'Cercle Indicateurs' to the portal (no separate indicators-set, as only a subset is added).

**Comment by JE1982** [comment]
- Where does the Link "Indikatoenset Cercle Indicateurs" goes to? We won't have e Set on our page. Or should we?
- Stufe 1 has to be renamed. Addition of a terminus like "Bereich" or something like that. 
- U01: Rename either in "Brutvogelindex Stadt Basel" or simply "Brutvogelindex".
- UO7: is there less water used in Basel area? or just less water cleaned in the ARA?

**Comment by bl99** [comment]
Concerning the questions of @JE1982 :
Where does the Link "Indikatoenset Cercle Indicateurs" goes to? We won't have e Set on our page. Or should we? 
@lcalmbach can you handle this via database? e.g. by adding a checkbox which says "no set page existing" and triggers that the Set-Link will not be displayed?

Stufe 1 has to be renamed. Addition of a terminus like "Bereich" or something like that.
@jb3-2 Can you discuss this with @JE1982 ?

**Comment by bl99** [comment]
@jb3-2 Cercle Indicateurs set is ready for beeing published. 
Please coordinate with me, as the magnolia-set-page has to be published too.

**Comment by jb3-2** [comment]
To be merged into master and onto live tomorrow, 22.12.2017 together with @grilli73
