### ISSUE TITLE
Änderungen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#43]
Gesellsch. Zusammenhalt: Ich habe überall wo sie fehlten, im csv die Ns ergänzt und einmal falsche Werte ersetzt. 

Übrige: Indikator I.17.3.0002 (Übrige) ist identisch mit I.17.3.0001 (GesZus). Ich habe beim I.17.3.0002 das Häkchen beim json entfernt in der Hoffnung, dass er so rausfällt. 

Ich habe 2 neue Indikatoren im Thema Gesundheit angelegt. Nana macht morgen Freitag die Grafiken dazu.

**Comment by jb3-2** [comment]
Ja, so wird der Indikator nicht mehr angezeigt. ich lösche auch gleich das csv und js file dazu.
