### ISSUE TITLE
I.11.1.0041: Jahresangabe fehlt

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#44]

**Comment by jb3-2** [comment]
Bitte im Titel angeben, für welches Jahr die Daten angegeben sind.

**Comment by JE1982** [comment]
Ist umgesetzt. Aber nicht im Titel, sondern in den Erläuterungen. Grund: Der Kunde darf durchaus das Gefühl haben, dass er die aktuellsten Daten sieht (was ja auch stimmt). Und wenn es ihn wundernimmt, von wann sie stammen, kann er in den Erläuterungne nachschauen.

**Comment by jb3-2** [comment]
Bei vielen anderen Indikatoren ist die Jahreszahl im Titel zu finden. Sollten wir dies einheitlich handhaben?

**Comment by JE1982** [comment]
Eine gute Frage. Müssen wir mal in Ruhe kurz diskutieren.

**Comment by jb3-2** [comment]
Du hast ja die meisten Jahresangaben in diesem Commit schon eingefügt: 70fa8652006f0bd6ba3205af597015b6add236f8 

Lass uns prüfen, ob noch eine Jahresangabe irgendwo fehlt.

**Comment by jb3-2** [comment]
Alle Jahresangaben durch JE in Erläuterungen bzw. Lesehilfe eingefügt.
