### ISSUE TITLE
Only display stufe1 close to kennzahlenset if stufe1 is defined

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#446]
See e.g. 4905 in kennzahlenset view (Integration-kompakt)

**Comment by jb3-2** [comment]
![screen shot 2017-11-23 at 15 47 46](https://user-images.githubusercontent.com/7261044/33178219-b01f8676-d065-11e7-9604-9d4234156d9b.png)

**Comment by jb3-2** [comment]
@JE1982 Some charts do not have a stufe1 defined. For those I beautify the output. Is it correct that some charts need not have a stufe1 defined, even though others in the same kennzahlenset have stufe1 defined? Please verify.

**Comment by JE1982** [comment]
no. If one chart has a stufe 1 defined, then every chart in the same set should have a stufe 1.

**Comment by jb3-2** [comment]
@JE1982 Ok can you please check them through?

**Comment by JE1982** [comment]
done. a single one has to be changed.

**Comment by jb3-2** [comment]
ok will implement this in #450
