### ISSUE TITLE
17.3.0003: Wie kann es mehr gewählte Frauen als Kandidatinnen geben 2008?

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#45]

**Comment by JE1982** [comment]
Es gibt nicht mehr gewählte Frauen, sondern der Frauenanteil an den Gewählten ist höher als an den Kandidierenden. Heisst: Es wurden tendenziell eher Frauen gewählt.

**Comment by jb3-2** [comment]
Danke!
