### ISSUE TITLE
Zusammensetzung von Quellen

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#46]
Es gibt den seltenen Fall (der aber in Zukunft auch noch öfter auftreten kann), dass ein Indikator 2 Quellen hat. Kannst Du für diesen Fall ein Seikolon (;) als Trennzeichen einführen?

**Comment by jb3-2** [comment]
Das geht schon seit 18. August (Commit 5c62775271c98a699fc299299a24cb56de3338fc), siehe Bild.

![chart 1](https://cloud.githubusercontent.com/assets/7261044/18608972/36cae7ec-7cf7-11e6-8ede-df033002fe2c.png)

**Comment by JE1982** [comment]
Bestens, danke.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Samstag, 17. September 2016 16:56
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Zusammensetzung von Quellen (#46)


Das geht schon seit 18. August (Commit 5c62775<https://github.com/StataBS/indikatoren/commit/5c62775271c98a699fc299299a24cb56de3338fc>), siehe Bild.

[Das Bild wurde vom Absender entfernt. chart 1]<https://cloud.githubusercontent.com/assets/7261044/18608972/36cae7ec-7cf7-11e6-8ede-df033002fe2c.png>
