### ISSUE TITLE
37 oder 28 Indikatoren beim Set Gesellschaftlicher Zusammenhalt?

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#47]
[Hier](http://www.statistik.bs.ch/zahlen/indikatoren/sets/gesellschaftlicher-zusammenhalt.html) steht "38 Indikatoren", ich finde aber nur 37 charts. 

[Hier](http://www.statistik.bs.ch/zahlen/indikatoren/sets/integration-kompakt.html) steht 20, ich finde aber 21 charts.

**Comment by JE1982** [comment]
GesZus: Text auf der Website war falsch. Wird korrigiert. Danke!
Integration: Das liegt daran, dass wir aus einem Indikator 2 gemacht haben. Ich werde den Text auf der Website ebenfalls anpassen.
