### ISSUE TITLE
Optimize Population Pyramid

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#479]
branch issue-325 (private; Wanderung)

- [x]  Zoom does not behave as expected: 
![image](https://user-images.githubusercontent.com/23261816/33427003-0970c4de-d5c4-11e7-9c0c-5facf46cdae4.png)

- [x] Black columns are not equally centered and smaller than red and blue columns:
![image](https://user-images.githubusercontent.com/23261816/33427029-2dc01f2e-d5c4-11e7-945a-35c2dd9e0726.png)

**Comment by jb3-2** [comment]
Here's probably the solution, I will check it. 

plotOptions: {
        column: {           
          grouping: false
        }
    }

https://stackoverflow.com/a/14368441
