### ISSUE TITLE
update legislaturplan print

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#488]
@jb3-2: the following ids are not yet done:
-  6372
-  6371
-  6370
-  6369
-  6368

**Comment by jb3-2** [comment]
Bitte alle TSVs von Mutter übernehmen. 

- [ ] 6279: Komma in Achsenbeschriftung
- [ ] 6281: Achsenbeschriftung analog Mutter-Indikator
- [ ] 6282: engere Skalierung
- [ ] 6283: engere Skalierung
- [ ] 6285: Akslierung bis 500 000 000 reicht
- [ ] 6289: engere Skalierung
- [ ] 6294: engere Skalierung
- [ ] 6295: engere Skalierung
- [ ] 6296: engere Skalierung
- [ ] 6297: Regler weg
- [ ] 6298: engere Skalierung
- [ ] 6302: engere Skalierung
- [ ] 6303: engere Skalierung
- [ ] 6307: engere Skalierung
- [ ] 6310: Rubrikenbeschriftung von Mutter übernehmen, engere Skalierung
- [ ] 6313: engere Skalierung
- [ ] 6314engere Skalierung
- [ ] 6315: engere Skalierung
- [ ] 6316: Rubrikenbeschriftung von Mutter übernehmen, engere Skalierung
- [ ] 6318: engere Skalierung
- [ ] 6319: engere Skaleirung
- [ ] 6320: engere Skalierung
- [ ] 6324: engere Skalierung
- [ ] 6326: engere Skalierung
- [ ] 6327: engere Skalierung
- [ ] 6328: engere Skalierung¨
- [ ] 6330: engere Skalierung
- [ ] 6338: engere Skalierung

**Comment by jb3-2** [comment]
- [ ] 6316: co2 tief stellen
- [ ] 6334: Skalierung bis 250 000
- [ ] 6369: engere Skalierung

**Comment by jb3-2** [comment]
- [ ] yAxis.label must be properly aligned to grid lines

**Comment by JE1982** [comment]
6291, 6343 and 6344 should look the same. Please take the layout of 6291 (legend on top on one single line) and make 6343 and 6344 look the same.

**Comment by JE1982** [comment]
6290: please put some more space on top of the chart.

**Comment by jb3-2** [comment]
@JE1982 This issue is closed, and the respective branch is deleted after its go-live. I will create a new issue and copy your text there.
