### ISSUE TITLE
Export chart-details.html as pdf

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#494]
Implementation idea: see https://stackoverflow.com/questions/39171077/export-multiple-highcharts-with-custom-text-into-pdf

**Comment by jb3-2** [comment]
Other ideas: 
- https://github.com/eKoopmans/html2pdf
- http://www.html2pdf.it/

**Comment by jb3-2** [comment]
@JE1982 Here's a first attempt: http://issue-494--retailer-seawater-16683.netlify.com/ -- Let me know what you think. And maybe also ask OT for feedback. 

![screen shot 2017-12-10 at 20 59 08](https://user-images.githubusercontent.com/7261044/33808829-0124bff2-dded-11e7-8108-31cfec5e5f9f.png)

**Comment by JE1982** [comment]
Looks very good to me. One question: do I get "stufe 1" after "Indkatorenset" when I open it in the set view?
We have to discuss about the notations.

**Comment by jb3-2** [comment]
To get Indikatorenset view you have to add the parameter "Indikatorenset=" and an existing indikatorenset name to the url, e.g. http://issue-494--retailer-seawater-16683.netlify.com/?Indikatorenset=Legislaturplan

Does that answer your question?

**Comment by jb3-2** [comment]
I'm happy to change all titles in the hamburger menu, please provide input!

**Comment by JE1982** [comment]
have you got an idea why it does not work? It's not only "stufe 1" that is not displayed but also "Kürzel Kunde". On top of "Lesehilfe" "Kürzel" is shown instead of "Kürzel Kunde" (which is correct in the portal view but not in the set view).

**Comment by JE1982** [comment]
maybe we should a brief brainstorming on wednesday concerning the titles in hamburger menu, maybe together with OT.

**Comment by jb3-2** [comment]
It doesn't work because I forgot to implement it ;-) 

Will do asap.

**Comment by JE1982** [comment]
that's a good reason though...

**Comment by jb3-2** [comment]
Will implement this in #536

**Comment by JE1982** [comment]
@jb3-2: is this running in any branch at the moment?

**Comment by jb3-2** [comment]
Here's the current state: http://issue-494--retailer-seawater-16683.netlify.com//chart-details.html?id=6348 then click the PDF button, and wait for 5 seconds or so.

**Comment by jb3-2** [comment]
We will have complete freedom how to lay out the pdf, it need not look identical to the html page. But some work is still required.

**Comment by jb3-2** [comment]
After discussing the options we decided that this feature less important than we initially thought, because most browsers / Operating systems can already create pdf files from a web page (e.g. iOS 11, Chrome, Print to PDF in Windows 10, PDF24 in Windows 7, Create PDF in MacOS X). 

Creating PDF files from SVG in the Browser creates huge PDF files since SVG has to be rasterized on a canvas (e.g. jsPDF, html2pdf.js). Alternatively, using a server component like html2pdf.it (which uses headless chrome) creates an additional runtime dependency, and has its own problems, e.g. fonts.

**Comment by jb3-2** [comment]
Chart-details.html is now printer-friendly (see #762), thus this issue loses its importance. Let's close it for the moment and re-open it once it is really necessary to create pdf files from within the web app.
