### ISSUE TITLE
bug: from "tourismus" to "verkehr" the chapter does not change correctly

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#496]
when you click the Thema "Tourismus" the Unterthema switches automatically to "Hotellerie" because there is only 1 chapter. When you change the Thema to "Verkehr" the Unterthema "Hotellerie" still stands. This leeds to mistakes. It does not seem to occur in other combinations... do we have a indicator with Thema "Verkehr" and Unterthema "Hotelleire"? (this should not be possible).

**Comment by JE1982** [comment]
yes we do: 3104. I change it in DB.

**Comment by JE1982** [comment]
done. json is in the correct folder on P.

**Comment by JE1982** [comment]
@jb3-2: can you please update json of chart 3104. It is in the LPI-folder on P.

**Comment by jb3-2** [comment]
@JE1982 3104 is in Thema Verkehr and Unterthema Mobilitätsverhalten. That's different than you state above. Please clarify.

**Comment by JE1982** [comment]
3104 should have Thema Verkehr and Unterthema Mobilitätsverhalten but used to have Thema Verkehr and Uterthema Hotellerie (which was wrong).

**Comment by jb3-2** [comment]
Fixed by uploading new metadata for 3104.
