### ISSUE TITLE
Pdf_Map

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#498]
In this branch the new version of the pdf maps are developed.

**Comment by larafaelivrin** [comment]
Discussion with RA

**For continuous and categorical maps:** 

- [ ]  When downloading a map as *png, *jpeg, *pdf or *svg the image should always contain the whole map (zoom level = 0). E.g. when zooming in to zoom level 2 the downloaded image should be at zoom level 0. 
- [ ] When zooming in all legend items (including legend title and subtitle which contains information about Kt. BS) should disappear as this makes the map less noisy.
- [ ] Some maps (e.g. Reineinkommen and Reinvermögen) have predefined colours.  

**categorical maps:**

- [ ] When the choropleth categories are greyed out the wohnviertel should also be greyed out. Momentarily the wohnviertel are coloured white when the choropleth categories are greyed out.

**Comment by larafaelivrin** [comment]
Discussion with JB

**Improve Map legend for continuous and categorical map legends**

- [ ] Dynamically update the bubble legend text instead of hiding the bubble legend when zooming in 
- [ ] Add a button with which the user can display/hide legend items.
- [ ] Add a white bounding box around the legend items so that legend items and the map items don't get confused when zooming in.

Addutuibak Input from KK

**Subtitle (No inserted as LegendLabel)** 

- [ ] Is there a way to add numbers to the LegendLabel which contains information from the tsv. E.g. the tsv should contain a column names "Kt. Basel-Stadt" which contains the cantonal data:

Kt. Basel-Stadt
38 873
16,6 %

The LegendLabel should then be:

"Kanton Basel Stadt:" + **38 873** + "unter 20-Jähriger(" **16,6%**+ ")"

**Comment by larafaelivrin** [comment]
For a meeting tomorrow I would like to know if it is realistic that we implement the above mentioned changes until end of February? @JE1982

**Comment by jb3-2** [comment]
Yes, I think that is possible.

**Comment by larafaelivrin** [comment]
Perfect, I communicated this yesterday. Let me know, if I can help you with something.

**Comment by jb3-2** [comment]
@larafaelivrin @bl99 @JE1982 Regarding the bubble legend on zoom: How about this implementation: http://issue-498--retailer-seawater-16683.netlify.com/chart-details.html?id=6379 - Please let me know.

**Comment by JE1982** [comment]
looks good to me!

**Comment by larafaelivrin** [comment]
looks good to me too, the legend in basleratlas is similar.

**Comment by larafaelivrin** [comment]
Until when can this issue be completed? It momentarily does not have a high priority but it would be good to have an estimate so that I know what I can communicate to the web and GIS team. @jb3-2

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Are you happy with this implementation? Clicking on the legend frame toggles visibility of legend AND pies on map. Legend cannot be independently hidden, which makes sense from my point of view. 

http://issue-498--retailer-seawater-16683.netlify.com/chart-details.html?id=6379

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Regarding your request to add data for Kanton BS (and maybe also Basel = Wohnviertel 1-19) (see screenshot below: It is currently not possible to add rows that do not match a Wohnviertel. At the moment you have to manually add the number into the title text in the js file. Let's discuss if and how we could / should optimize this. 

![image](https://user-images.githubusercontent.com/7261044/37963333-4167f8ca-31be-11e8-8f4e-001331f1061e.png)

**Comment by larafaelivrin** [comment]
**@larafaelivrin @JE1982 Are you happy with this implementation? Clicking on the legend frame toggles visibility of legend AND pies on map. Legend cannot be independently hidden, which makes sense from my point of view.**

I am not sure weather an unexperienced user understands that the bubbles can be dis- and enabled via a click the legend box. But I guess that an unexperienced user will try to click on the bubbles to see what happens. Thus, I think that this solution is ok. What confuses me personally a bit is that the bubbles are also dis-and enabled when I click on "Leerwohnungsquote in %" (see screenshots 1 and 2). Another problem is that the legend does not seem to display the correct value (see blue outlined bubbles in screenshot 3)

Screenshot 1
![image](https://user-images.githubusercontent.com/23261816/38295260-b59a0d7a-37ed-11e8-8ace-86c59f63807f.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/23261816/38295269-bb27a7c0-37ed-11e8-8e67-de5275be3384.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/23261816/38295095-2d4f8288-37ed-11e8-9e29-498069d37195.png)

**@larafaelivrin @JE1982 Regarding your request to add data for Kanton BS (and maybe also Basel = Wohnviertel 1-19) (see screenshot below: It is currently not possible to add rows that do not match a Wohnviertel. At the moment you have to manually add the number into the title text in the js file. Let's discuss if and how we could / should optimize this.**
Yes, lets discuss this in a meeting.

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Thanks for reporting the error in calculating the bubble value when zooming. I'll fix that asap. Regarding hiding the legend when clicking on the colorAxis: Actually the bubble legend is hidden when clicking on bubble legend, legend value, legend title, or the grey box. Let me know if this is acceptable.

**Comment by larafaelivrin** [comment]
@jb3-2 I will come by today to discuss the legend.

**Comment by larafaelivrin** [comment]
As discussed with @grilli73 the legend of the maps should be formatted as follows:
@ jb let me know if you have questions:

![image](https://user-images.githubusercontent.com/23261816/38924787-21978a14-42fe-11e8-869e-c63f02ab0e1a.png)

**Comment by larafaelivrin** [comment]
@jb3-2  do you think that this issue can be implemented until beginning of June? That would be really great as some work depends on it. If it is not possible please let us know until when it can be implemented so that we can plan the work accordingly.

**Comment by jb3-2** [comment]
@larafaelivrin Visuals and click behavior is now implemented in 6379 (branch issue-498). I now start fixing the legend values on zoom. 
http://issue-498--retailer-seawater-16683.netlify.com/chart-details.html?id=6379

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982  I think I have solved the problem with wrong legend numbers on zoom: I must wait for the zoom animation to finish before calculating the current zoom level and recalculating the legend value. Now it should work. Can you please test? I have set up chart 9995 where you can change the numbers in the tsv so that they match the legend values of a certain zoom level, then you can compare if the circles have really the same size. 

http://issue-498--retailer-seawater-16683.netlify.com/chart-details.html?id=9995 

Chart 6379 should now also work fine. Please let me know if there are any remainingerrors. If there are, I will next disable zoom on mouse wheel scroll, so that you can only zoom via the +/- buttons. 

http://issue-498--retailer-seawater-16683.netlify.com/chart-details.html?id=6379

**Comment by larafaelivrin** [comment]
it looks correct to me! :)

**Comment by larafaelivrin** [comment]
The legend fonts do not seem to match although the font styles match (e.g. 6391). Have you observed this behaviour before @jb3-2 ?

![image](https://user-images.githubusercontent.com/23261816/40920972-6b37283e-680e-11e8-81cc-32a1c59c99e9.png)

mappie001:

![image](https://user-images.githubusercontent.com/23261816/40920949-58c757c8-680e-11e8-9c29-634a0c20a559.png)

![image](https://user-images.githubusercontent.com/23261816/40920989-79a80cda-680e-11e8-9a65-0ffb6a3d8bdf.png)

**Comment by jb3-2** [comment]
I think what's missing is fill this in the style: 

rgb(51, 51, 51); 

Let me fix this quickly.

**Comment by bl99** [comment]
The problem is that the left part of the legend exists twice in the source code

**Comment by larafaelivrin** [comment]
6375

- [ ] When klicking on the legend to turn it off the numbers stay. The numbers should not be visible:
![image](https://user-images.githubusercontent.com/23261816/40976195-94e9c1ea-68cd-11e8-8f3c-94e04b4985b2.png)

- [ ] When zooming in the upper grey legend box doesn ot disappear. It should also disappear:
![image](https://user-images.githubusercontent.com/23261816/40976244-ce46e102-68cd-11e8-91b9-2bdcf48c5710.png)

**Comment by larafaelivrin** [comment]
6392

- [ ] RA: Wenn ich die Kategorien / Choroplethen einzeln in der Legende ausschalte und danach die Kreissymbole ausschalte erscheinen die Kategorien in der Legende wieder. Dann muss ich die Kategorien in der Legende nochmals einzeln ausschalten um diese danach wieder in der Karte sichtbar machen zu können:

- [ ] RA: •	Ist es möglich die Legende rechts auszurichten. Also hier meine ich dass das 20 beim 2000 rechtsbündig sein sollte:  
![image](https://user-images.githubusercontent.com/23261816/40982741-496d9302-68de-11e8-8387-56ae4379fd60.png)

**Comment by jb3-2** [comment]
@larafaelivrin Please let me know if you need any help finishing this publication.

**Comment by jb3-2** [comment]
@larafaelivrin As you see in #939, I would prefer if you put all maps into one indikatorset, and e.g. added two chapters (stufe1) for cat and cont. It does not really make sense to separate the cat and cont charts into separate sets since they belong together from my point of view. Can you do this?

**Comment by jb3-2** [comment]
- [ ] PNG-Export: Text nicht linksbündig bei Sesshaftigkeit nach Wohnviertel, Reinvermögen nach Wohnviertel…  JB: ‚legend.useHTML = false‘ (oder noch besser Zeile, in der useHTML true gesetzt wird, löschen) löst dieses Problem @larafaelivrin : Kannst du dies bitte überall umsetzen?
![image](https://user-images.githubusercontent.com/7261044/42825040-72d5619c-89e1-11e8-83ed-854f7e9ffa81.png)

**Comment by jb3-2** [comment]
- [ ] Tooltip wird von Legendenschrift überlappt: JB: ‚legend.useHTML = false‘ (oder noch besser Zeile, in der useHTML true gesetzt wird, löschen) löst dieses Problem @larafaelivrin : Kannst du dies bitte überall umsetzen?
![image](https://user-images.githubusercontent.com/7261044/42825256-e5ec722e-89e1-11e8-87ca-c25a9801383c.png)

**Comment by jb3-2** [comment]
- [ ] Wieso nicht um alle Legenden einen Rahmen? Kat & Kont, egal ob Kreis oder Fläche @larafaelivrin: OK ich habe die Funktion auch den Templates map001 und map002 hinzugefügt. Fehlt sie noch irgendwo?
![image](https://user-images.githubusercontent.com/7261044/42826738-70e1073e-89e5-11e8-933c-cffb56aa8c26.png)

**Comment by jb3-2** [comment]
- [ ] Maus-Pointer für ausblendbare Kreis-Legenden ändern zu Hand (statt Strich), analog
  
![image](https://user-images.githubusercontent.com/7261044/42827276-4ac04fb4-89e6-11e8-90c2-2d925abd57fb.png)

JB: Ist gemacht via CSS: .pieLegend { cursor: pointer;}

**Comment by jb3-2** [comment]
- [ ] Nach wieder einblenden von Kreislegenden erscheint Zahl statt leer (bsp. 0 000 bei Wohnungsdichte):

![image](https://user-images.githubusercontent.com/7261044/42827357-74e212aa-89e6-11e8-8fa3-755655032f52.png)

**Comment by larafaelivrin** [comment]
As I do not have the rights to check the checkboxes I marked the currents status with help of emoties.

**Comment by jb3-2** [comment]
- [ ] Export (alle Formate) bei ausgeblendeten Kreisen (links) ergibt rechts:
![image](https://user-images.githubusercontent.com/7261044/42949913-2fe9cec0-8b73-11e8-93df-bf5a1675c8d5.png)
JB: Highcharts Forum Anfrage erstellt: https://forum.highcharts.com/topic40838/?sid=cc9a1ca5ba13a5c27bbb211b7829ac96

**Comment by larafaelivrin** [comment]
and: 
use html = false in addLegendLabel:
fn.addLegendLabel(e.target.chart, v.text, v.x, v.y, v.cssClass, v.**useHtml**, v.align)

**Comment by larafaelivrin** [comment]
@jb3-2  I changed the colour of the legend boxes and it does not look much nicer now! Great idea.

**Comment by larafaelivrin** [comment]
Input from JE:

This link should not be shown for the set "Häufig gefragte Karten" (as for the set "Übrige")

![image](https://user-images.githubusercontent.com/23261816/44665737-f3bc3380-aa16-11e8-84e3-695c39b5bf46.png)

**Comment by jb3-2** [comment]
@JE1982 From my point of view, this is now ready for go-live. Here's the netlify preview url: 

https://issue-498--statabs-indikatoren-test.netlify.com/?Indikatorenset=Gefragte%20Karten

**Comment by jb3-2** [comment]
This is now live with commit 4c21f5ecb5a7155feb3b9cdd3e508a7aa6c94a25
