### ISSUE TITLE
Legislaturplan Print Change Requests

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#499]
By @JE1982 (see #488): 

- [x] 6333, 6334 and 6287 should look the same. Please take the layout of 6287 (legend on top on one single line) and make the others the same. 
- [x] 6290 and 6292 and 6331 and 6332: please put some more space on top of the chart.
- [x] 6308: there is some data missing. thee should be the same data like the mother-chart 6156.

**Comment by jb3-2** [comment]
@JE1982 Chart 6308: OK like that?
![i 11 6 06308](https://user-images.githubusercontent.com/7261044/33664136-dc948274-da92-11e7-809b-5e5509972418.png)

**Comment by JE1982** [comment]
👍

Am 06.12.2017 um 14:36 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


@JE1982<https://github.com/je1982> Chart 6308: OK like that?
[i 11 6 06308]<https://user-images.githubusercontent.com/7261044/33664136-dc948274-da92-11e7-809b-5e5509972418.png>

**Comment by JE1982** [comment]
6299: please put some more space on top

**Comment by JE1982** [comment]
@jb3-2: 
[] 6304, 6340, 6341, 6344 should all look the same. But 6304 and 6341 seem to have less space on top than the other two. please put more space on top of 6304 and 6341.

**Comment by jb3-2** [comment]
As discussed, we have serious space constraints, so please addmore space in Word.

**Comment by JE1982** [comment]
we have feedback from Formale Redaktion, Barbara Sasshofer. Several Charts do have a achsis marking that is to large (means: more than 7 Pt). 
- 6283
- 6372
- 6273
- 6294
- 6288
- 6297
- 6298
- 6310
- 6314
- 6316
- 6319
- 6320
- 6281
- 6330

6340 should have the addition "J." right behind the written years in the y-achsis. 

@larafaelivrin: could you fix this?

**Comment by jb3-2** [comment]
Ok will do on wednesday. Please create a new issue, do not reuse old issues.

**Comment by larafaelivrin** [comment]
I can do this. Should I create a new branch or do we already have a branch wehre the Legislaturplan-Print indiactors are being worked on?

**Comment by jb3-2** [comment]
Please create a new branch. Branches are free, ee can have as many as we need. I usually delet them when a feature branch is merges into master.

**Comment by larafaelivrin** [comment]
Perfect, then I assume that the current state of the Legislaturplan-Print indicators is already merged into the master branch.
