### ISSUE TITLE
Make tooltips for chart-preview-imgs quicker

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#50]
Tooltips (popup-informations) via HTML-title tags are comparatively slow. Could be enhanced by using a js/jquery tooltip solution (similar to tooltips in highcharts).

**Comment by jb3-2** [comment]
Good idea! 
Problem: The reader should be able to see the title of the chart in order to understand what is being displayed. 
Solution: Have an instant tooltip instead of the delayed default tooltip.

**Comment by jb3-2** [comment]
Currently no problem, let's do that some time later on.
