### ISSUE TITLE
"Plot Line" overlaps data

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#512]
**Example:** issue-325, ID 6011
**Descrition:** ["Plot Line"](https://api.highcharts.com/highcharts/yAxis.plotLines) overlaps data ("Zuzugsort: unbekannt") as the values of latter are very small compared to the total.

**Comment by jb3-2** [comment]
Problem: zIndex of all series is 3. Idea: Add plotLine as a series, see https://github.com/highcharts/highcharts/issues/1687 and http://jsfiddle.net/highcharts/r3Lzjjz6/1/

**Comment by larafaelivrin** [comment]
It seems to work nicely but I have troubles understanding why you implemented a function and what this function does.
