### ISSUE TITLE
Dynamic Axis vs. setting min/max of axis

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#513]
When setting the min/max of an axis the dynamic ayis disappears. Is there a way to set min/max of an axis and keep the dynamic axis?

**Comment by jb3-2** [comment]
When you set min or max, you cannot zoom. Usually setting max is not necessary, but playing around with [yAxis.tickAmount](https://api.highcharts.com/highcharts/yAxis.tickAmount) or (rarely necessary) [yAxis.tickInterval ](https://api.highcharts.com/highcharts/yAxis.tickInterval)creates very satisfactory results. 

Combine this with dynamic number of decimals on axis labels (#785), and we're good I think . 

Please close the issue if you're happy with the response.
