### ISSUE TITLE
template map001

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#514]
I just realized that map001 is slightly untidy. For example the attribute "Wohnviertel name" is not next to "Wohnviertel id". This is not convenient when downloading the data. Also the tooltip for Rang is set in map001 and this tooltip will not be used for every map of this type. I think it is better to move the tooltip specification to the id.js? Do we already have a template to plot this kind of data (Wohnviertel_id, Wohnviertel_name, data)? I could not find it:

wohnviertel_id	wohnviertel	MeanReineinkommen
1	Altstadt Grossbasel	98117
2	Iselin	99422
3	St. Johann	75841
4	Altstadt Kleinbasel	56292
5	Clara	100470
6	Wettstein	55575
7	Hirzbrunnen	115298
8	Rosental	77778
9	Matthäus	63532
10	Klybeck	51788
11	Kleinhüningen	52273
12	Vorstädte	61193
13	Riehen	49702
14	Am Ring	73498
15	Bettingen	59376
16	Breite	51788
17	St. Alban	50044
18	Gundeldingen	42281
19	Bruderholz	45955
20	Bachletten	90865
30	Gotthelf	122319

**Comment by jb3-2** [comment]
I have created a new template for simpler Wohnviertel Choropleth Maps: map002. To see how you use it, check out 9999.js (https://statabs.github.io/indikatoren/chart-details.html?id=9999).
