### ISSUE TITLE
Documentation of current print indicator procedure

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#515]
Where can I find the documentation of the current print indicator procedure? As I understand a new procedure was developed for the indicator set "Legislaturplan"?

**Comment by jb3-2** [comment]
Yes: "Legislaturplan (Print)". There's no documentation about this. What do you need to know? You can find the current sets in metadata/sets/ (one file per set). Theae files are generated by "npm run build".

**Comment by larafaelivrin** [comment]
I thought you wrote a new script to simplify the creation of the print indicators for the "Legislaturplan (Print)" set?

**Comment by jb3-2** [comment]
Yes, you are right! I have created a script that copies js und tsv data for print kennzahlensets from the respective parent (if the file does not exist yet). 

1. Upload Print kennzahlenset metadata 
2. Run `node build/createMissingPrintChartsFromMetadata.js`
3. Profit.
