### ISSUE TITLE
Legenden überlappen inhalt, zB I.01.6.0001.js

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#53]
Bei versch. charts mit Template line001.js überlappt die Legende den Plotbereich der Charts. Bei den Integrationsindikatoren z.B.: 1-6, 2-1, 2-4

Ist die Legenden-Grösse fix definiert? Weiss nicht, wo das am sinnvollsten angepasst werden sollte: Allgemein, template oder einzelne charts?

**Comment by jb3-2** [comment]
Bitte um Screenshot, kann dies nicht nachvollziehen.

**Comment by bl99** [comment]
[cid:image001.png@01D21292.CBB30D00]
Mittel- und Südamerika überlappt oberste Gitterlinie

**Comment by bl99** [comment]
![2016-09-19 16_37_04-statistik - integrationsindikatoren](https://cloud.githubusercontent.com/assets/20966212/18635955/549e47dc-7e87-11e6-949b-ff318137dc0c.jpg)

**Comment by jb3-2** [comment]
Lösung: chart.marginTop von 120 auf 130 erhöht. Idealerweise sollte HighCharts selbst schauen, dass die Legende nicht in die chart "Wall" lappt. Ich werde prüfen, ob wir dies irgendwie einrichten können.
