### ISSUE TITLE
How does the ID.js file know that it plots the ID.tsv file

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#534]
Which scripts tells the ID.js file to use the ID.tsv file? I assume there has to be a script as we never use the data option, eg: 

series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]

**Comment by jb3-2** [comment]
https://github.com/statabs-test/indikatoren/blob/0f5e2e7ae48b84de8c3ae10dce6c014da11cfdd1/assets/js/indikatoren-highcharts.js#L151
