### ISSUE TITLE
I.01.2.0003: Anteil Personen in Einpersonenhaushalten

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#54]
Im Quartierradar ist nicht der Anteil Einpersonenhaushalte angegeben, sondern der Anteil Personen in Einpersonenhaushalten an der Gesamtbevölkerung. Ich fände den Anteil Einpersonenhaushalte aber eigentlich die bessere Zahl. Schauen wir am besten morgen kurz mit CM und LC an. Deshalb erhalten wir unterschiedliche Werte. Falls wir die ursprüngliche Zahl behalten wollen, muss m.E. der Titel angepasst werden, weil er etwas anderes suggeriert.

**Comment by jb3-2** [comment]
Du hast dies in commit 6c53afc844dc2c0a4bdbb1e4c5a8fd6501f90841 im json umformuliert.

**Comment by jb3-2** [comment]
Kannst Du dies noch NM und LM ausrichten, denn dies sollte auch in den Quartierportraits nachgeführt werden, denke ich.

**Comment by JE1982** [comment]
Wir haben entschieden alles so zu lassen wie in den Quartierportraits. Ich habe deshalb den Titel in der DB angepasst.

**Comment by JE1982** [comment]
Nana ist bereits im Bild.
LG, J.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Dienstag, 20. September 2016 15:23
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] I.01.2.0003 (#54)


Kannst Du dies noch NM und LM ausrichten, denn dies sollte auch in den Quartierportraits nachgeführt werden, denke ich.

**Comment by JE1982** [comment]
Ja, ich weiss. Muss ich noch etwas machen?

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Dienstag, 20. September 2016 15:23
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] I.01.2.0003 (#54)


Du hast dies in commit 6c53afc<https://github.com/StataBS/indikatoren/commit/6c53afc844dc2c0a4bdbb1e4c5a8fd6501f90841> im json umformuliert.

**Comment by jb3-2** [comment]
@Nana-Mittelmaier Muss man den Titel im Tableau [hier](http://www.statistik.bs.ch/interaktiv/quartiere.html) und im Web (PDF etc.) auch noch anpassen?
