### ISSUE TITLE
template mappie002: how can I add more than two pie slices to the pie chart

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#542]
I tried to add more than two pie slices to the pie chart in the template mappie002 but have not succeeded:
issue-498, id: 6381

**Comment by jb3-2** [comment]
![image](https://user-images.githubusercontent.com/7261044/33997374-6f5054e2-e0e4-11e7-9774-702c38b24649.png)


![image](https://user-images.githubusercontent.com/7261044/33997360-616f8eb0-e0e4-11e7-95ce-60cf1a50a517.png)


![image](https://user-images.githubusercontent.com/7261044/33997309-3936ebbe-e0e4-11e7-97fe-caba2fc6442c.png)

**Comment by larafaelivrin** [comment]
aaargh, I forgot to add the column for the pie size... that was the problem. Thank you!
