### ISSUE TITLE
template mappie002: increase pies on zoom

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#545]
The pies dont increase when zomming in.

**Comment by jb3-2** [comment]
You can change this behavior yourself, as you see in [6025](https://statabs.github.io/indikatoren/chart-details.html?id=6025): In function 'sizeFormatter', return zoom * pieSize(....): 

![image](https://user-images.githubusercontent.com/7261044/35519251-04df9de4-0514-11e8-9158-99ef4e67e6dd.png)
