### ISSUE TITLE
LP-Print: changes requested by formale Redaktion

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#551]
we have feedback from Formale Redaktion, Barbara Sasshofer. Several Charts do have a achsis marking that is to large (means: more than 7 Pt).

    6283
    6372
    6273
    6294
    6288
    6297
    6298
    6310
    6314
    6316
    6319
    6320
    6281
    6330

6340 should have the addition "J." right behind the written years in the y-achsis.

@larafaelivrin: I think you should create a new branch.

**Comment by jb3-2** [comment]
@larafaelivrin works on this in issue #554, thus I close this issue.
