### ISSUE TITLE
Indikatorenset Integration: create charts

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#552]
in about 6 weeks we need to publish some indicators out of the indikatorenset "Integration" (not "Integration kompakt", which is already live) and show them to the media. I guess there should be around 20 indikators, but I don't know all of them yet. 

@jb3-2 @larafaelivrin: could one of you please create the following ones as they are shown in the pdf located on P ( \\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\4_Monitoring_Controlling\Kennzahlensysteme\Integration\2017\Bericht_2017\Integrationsindikatoren_2018_171208_v2.pdf)? Please use the same colors as in the pdf, the codes are here (\\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\4_Monitoring_Controlling\Kennzahlensysteme\Integration\2017\Indikatoren\Grafikvorgaben.xlsx, sheet "RGB-Farben"). Other charts to be built will follow. We have to discuss with @lcalmbach how to get the tsv-Files, at the moment the data is available only in Excel.  

- 6059
- 6064
- 6065
- 6066
- 6067
- 6070
- 6077
- 6078
- 6080
- 6081
- 6082
- 6083
- 6090

**Comment by jb3-2** [comment]
@larafaelivrin Works on this in issue #555, thus I close this issue.
