### ISSUE TITLE
iframe is to short

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#553]
with new order of charts with only two rows in the set view the iframe is to short. Users have to scroll while looking to one single chart. I would like to change this.

**Comment by JE1982** [comment]
@jb3-2: NG had the idea of a "grey-box" that is larger than the iframe.

**Comment by jb3-2** [comment]
@grilli73 @JE1982 Unfortunately no div can be bigger than its parent iframe. If the chart carousel view is too high, we need to make the iframe higher (e.g. show an additional row of charts), or make it shorter by reducing its space consumption. I'm open to ideas.
