### ISSUE TITLE
LP-Print

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#554]
In this branch the LP-Print indicators are being worked on.

**Comment by larafaelivrin** [comment]
Improve font size of axis of these ID:

- [ ] 6283
- [ ] 6372
- [ ] 6273
- [ ] 6294
- [ ] 6288
- [ ] 6297
- [ ] 6298
- [ ] 6310
- [ ] 6314
- [ ] 6316
- [ ] 6319
- [ ] 6320
- [ ] 6281
- [ ] 6330

- [ ] 6340:

 should have the addition "J." right behind the written years in the y-achsis.

**Comment by JE1982** [comment]
@larafaelivrin: 6301: please add 0% on the y-achsis.

**Comment by larafaelivrin** [comment]
6301: Done; I cannot check the checkbox.

**Comment by JE1982** [comment]
@larafaelivrin can you put the image in the correct folder please?

**Comment by larafaelivrin** [comment]
The image 6309 is now here: \\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\4_Monitoring_Controlling\Kennzahlensysteme\Strategisches Controlling\LP_2017-2021\Bericht\Printindikatoren
