### ISSUE TITLE
Indikatorenset Integration

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#555]
In this public branch the indicator set "Integration" is being worked on.

**Comment by larafaelivrin** [comment]
- [ ] 6059
- [ ] 6064
- [ ] 6065
- [ ] 6066
- [ ] 6067
- [ ] 6070
- [ ] 6077
- [ ] 6078
- [ ] 6080
- [ ] 6081
- [ ] 6082
- [ ] 6083
- [ ] 6090

**Comment by JE1982** [comment]
@larafaelivrin: I think we have to be ready to publish all charts of integration by february 27th. is this realistic?
They should all be ready in Access-App by the end of today, but data is still only available in Excel.
