### ISSUE TITLE
Tooltip overlaps axis-text

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#56]
![2016-09-20 15_42_24-statistik - indikatoren zum gesellschaftlichen zusammenhalt](https://cloud.githubusercontent.com/assets/20966212/18672566/e9ac7abc-7f48-11e6-8bd8-62ad95ce1f79.jpg)

**Comment by bl99** [comment]
Entsteht durch Verwendung von useHTML = true in
 "xAxis": {
        "labels": {
            "useHTML": true

Scheint ein css z-index problem zu sein, konnte es aber nicht lösen...
Habe versucht:
.highcharts-tooltip  {
	z-index: 9999 !important; 
}

Siehe auch:
http://stackoverflow.com/questions/15130311/highcharts-labels-visible-over-tooltip

**Comment by jb3-2** [comment]
Problem: Apparently html elements are always positioned above svg. 
Solution: If axis has enableHTML set to true, doe the same for the tooltip. Then in the CSS define the z-axis and some more (see 6cf22eb).

**Comment by jb3-2** [comment]
Alternative solution: replace placeholder for empty label text with spaces before rendering, this way enableHTML is not necessary.
