### ISSUE TITLE
Umwelt-charts in portal-view

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#567]
some of the umwelt-charts should be children (or parents) of other charts. I'm checking this at the moment. 
@bl99: what is the difference between 4221 and 6161?
- 4231 and 6164 should be mother/child 
- 6159 and 4269 should be mother/child 
- 4132 and 4318 are similar but not equal
- 4320 and 4140 are similar but not equal
- 4323 and 6124: do they use the same source?
- 4325: only "private" cars or business used cars included?

**Comment by JE1982** [comment]
the cleaning-up of the umwelt-charts will take some days. @jb3-2: please unpublish them for another time.

**Comment by JE1982** [comment]
@bl99: 4320 has BFS as source, but this does not fit with our own data. I think this is nessessary due to comparison with BL. But I don't think we should show this one in portal-view.

**Comment by JE1982** [comment]
@bl99 
- 4323 and 6124: do they use the same source?
- 4325: only "private" cars or business used cars included?

**Comment by bl99** [comment]
@JE1982  4325: includes all cars, according to t11.1.01
