### ISSUE TITLE
Linebreak between different Quellen or not?

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#568]
In cases where there are several short "Quellen", it would be better to show them on one line instead of adding linebreaks. 
@jb3-2 / @JE1982 what do you think?

example 4348:
![grafik](https://user-images.githubusercontent.com/20966212/34252862-8fd6a200-e645-11e7-8fff-274a092f53c8.png)

**Comment by JE1982** [comment]
I agree that it's more beautiful not to have a automatical line break. But what is the case if all the "Quellen" do not have enough space on one single line? Can we have a linebreak at the point where the next "Quelle" to be shown is to large to be shown on the same line than the previous one?
