### ISSUE TITLE
4318: Link is broken

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#574]
http://www.umweltberichtbeiderbasel.bs.ch/indikatoren-17-1702

![image](https://user-images.githubusercontent.com/7261044/34266217-b43a20e4-e678-11e7-9017-2045eeadc13a.png)

![image](https://user-images.githubusercontent.com/7261044/34266245-be85f528-e678-11e7-8dbe-0cb54b67e2ab.png)

**Comment by bl99** [comment]
solved
