### ISSUE TITLE
CI: Kernindikatoren

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#578]
@bl99: the terminus "Kernindikatoren" is used in analyses like Wanderungsanalyse to identify yearly updated indicators that are laos shown in Indikatorenportal. It would be better to use another terminus for the indicators of cercle indicateurs. 
![2017-12-22 11_18_07-statistik - indikatorensets](https://user-images.githubusercontent.com/20972660/34294670-ea1b839c-e709-11e7-8303-85ccafe0a0fa.png)

**Comment by bl99** [comment]
will be changed to 
![grafik](https://user-images.githubusercontent.com/20966212/34295051-8f0b639e-e70b-11e7-99ea-cc74e0e9d098.png)
