### ISSUE TITLE
Create change log for sets and portal-view

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#582]
@jb3-2: it would be nice to see what changes occured from an update compared to the previous live-status. Which ids are new in which set resp. in portal-view and which ids are no more in set resp. portal-view.

**Comment by jb3-2** [comment]
@JE1982 How about a file that contains the following table, which describes the current state? Via diffing with the previous state you can see the differences. 

id | visible | visibleInPortal | indikatorenset
---|---|---|---
1234 | true | false | Umwelt
9995 | false
9994 | true | false | Test

**Comment by jb3-2** [comment]
@JE1982 Now you can check the current state of all charts in file 

metadata/all/all.md 
(https://github.com/StataBS/indikatoren/blob/master/metadata/all/all.md). 

Changes can be displayed via github diff tool.

**Comment by larafaelivrin** [comment]
I acccidantally commited something in this branch instead of in issue-587. As this branch is not active anymore (changes are implemented in the master) I assume that this branch can be deleted (including my changes which do not belong in this branch). @jb3-2 is that correct?

**Comment by jb3-2** [comment]
Yes, you can go ahead and delete this branch (on github and ideally also on your c9 vm using git branch -D, I think).
