### ISSUE TITLE
Check "Anzahl Gewaltstraftaten pro 100 000 Einwohner"

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#584]
@JE1982 "Anzahl Gewaltstraftaten pro 100 000 Einwohner" needs to be cleaned reagrding Mother-Child-Relationships (and Thema/Unterthema, Verantwortlichkeit)
6323
5188
4923

**Comment by JE1982** [comment]
done. 
- changed title an Thema/Unterthema of 6323 and changed Unterthema of 4923.

**Comment by jb3-2** [comment]
Will be changed in issue #585 Nachhaltigkeit
