### ISSUE TITLE
Nachhaltigkeit

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#585]
In this branch the indicator set "Nachhaltigkeit" is being worked on.

**Comment by JE1982** [comment]
@bl99: maybe we need to add "Bereich" to our "Stufe 1" in "Gliederung" for better understanding of the note "Dieser Indikator ist Bestandteil des Indikatorensets Nachhaltigkeit, Wirtschaftliche Entfaltung." at the end of the chart.

**Comment by bl99** [comment]
@JE1982 Good idea. Can this be implemented for all Sets? And then maybe even "Nachhaltigkeit (Bereich Wirtschaftliche Entfaltung)" instead of ","?

**Comment by JE1982** [comment]
@bl99: we discussed this some months ago I think and decided to do it as set for some (?) reason. @jb3-2: do you know more?

**Comment by bl99** [comment]
done in database. @larafaelivrin as you are working on NE right now, can you - when it suits - re-generate all NE json files and upload them to issue-585? Thank you

**Comment by JE1982** [comment]
@bl99, @larafaelivrin: what is the current state of development here? Access says that the status of most indicators is "unbekannt". Are we going to be ready by the end of february?

What I saw in the issue-branch is that most charts seem not to have the correct sortkey. It has to be set in menu "Indikatoren-Set", column "Sortierung".

**Comment by larafaelivrin** [comment]
The status is the following

- *.js: prepared (see: http://issue-585--retailer-seawater-16683.netlify.com/?Indikatorenset=Nachhaltigkeit) 
- *.tsv: prepared but needs to be updated (I think LC is working on this? @bl99  do you know more?)
- *.json: prepared but needs to be updated (It is probably best to update the *.json when the updated *.tsv are available)

**Comment by bl99** [comment]
- ***.tsv:** @lcalmbach is working on database to .tsv processes. In this context, some issues need to be clarified by me. As soon as we are ready we will ask people to update their indicators (next week)
- **sortkeys** have been set in access
- lost **Gliederung** has been re-entered

**Comment by JE1982** [comment]
@larafaelivrin: when do we get feedback by formale Redaktion?

**Comment by larafaelivrin** [comment]
@JE1982  we already got feedback on Wednesday afternoon. I will start implementing the corrections today.
