### ISSUE TITLE
Add 6437 and 6438 to indicator set "Legislaturplan"

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#586]
Add 6437 and 6438 to indicator set "Legislaturplan"

**Comment by jb3-2** [comment]
@larafaelivrin Wouldn't it be better if the legend was horizontal on top?

**Comment by larafaelivrin** [comment]
Thank you for your feedback. I realized that it nicer to plot Note in the legend as this is identical to the plots we already published with the same legend. E.g.: https://statabs.github.io/indikatoren/chart-details.html?id=6151&indikatorensetView=true&suppressNumberInTitle=true

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Is this completed, can I go live with this?

**Comment by larafaelivrin** [comment]
This is not completed. @JE1982 is still working on the metadate.

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Is this completed, can I go live with this?

**Comment by JE1982** [comment]
not yet

**Comment by jb3-2** [comment]
This is about to go live with Nachhaltigkeit in #585
