### ISSUE TITLE
update Set Wohnraumentwicklung

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#587]
Most of the charts of Wohnraumentwicklung have to be updated. Monday 8th the automatic Mail-Reminders are pushed, so people can update data and metadata. @jb3-2, @larafaelivrin: the updated charts should be published till the end of January. can someone please take care of?

**Comment by larafaelivrin** [comment]
Where do people store the updated data? This folder is empty:  \\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\4_Monitoring_Controlling\Indikatorensets\Wohnraumentwicklung\2018\tsv @JE1982

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Is this completed, can I go live with this?

**Comment by JE1982** [comment]
I'm not sure if there is something to go live with in this branch. I think most of these charts have been set live individually or are still under construction. @jb3-2: maybe we should compare this branch to master and check the differences together?

**Comment by jb3-2** [comment]
@JE1982 Could you please get the overview over these charts? Some are live, some not, and I somehow do not trust the status in the db.

**Comment by JE1982** [comment]
I think we can close this one, because the charts are updated individually. @jb3-2: do you agree?

**Comment by larafaelivrin** [comment]
In my opinion we can also close this branch for the same reasons as JE mentions above @jb3-2 @JE1982

**Comment by jb3-2** [comment]
Ok
