### ISSUE TITLE
List of Themen in portal view

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#589]
@jb3-2: how is the list of "Themen" in portal view generated? And: I guess you match the charts to the "Thema" by the number of the Thema in metadata. Correct?
background of that question: in a few days we publish two charts with "Thema" = 85 "Statistik" but I want them to be shown in Thema 50 "Befragungen". Is this possible or causes this any problems?

**Comment by JE1982** [comment]
@jb3-2: the two charts with Thema 85 are shown in portal view. The system builds a new Thema without a name. See #586

**Comment by jb3-2** [comment]
@lcalmbach Please change the DB Code so that charts with thema >= 50 have "thema":"50 Befragungen" defined in their json file.

**Comment by lcalmbach** [comment]
all themes > 50 now appear as "Befragungen" and "50 Befragungen" in the view [indikatoren_app].[dbo].[vwIndikatorenWeb] used for generating the json file. tested indicators 3437/38 and both now are assigned to "Befragungen"

**Comment by JE1982** [comment]
@jb3-2: does this work now?

**Comment by jb3-2** [comment]
@JE1982 Yes, see http://issue-586--retailer-seawater-16683.netlify.com/

![image](https://user-images.githubusercontent.com/7261044/34866303-784a3942-f77c-11e7-8202-ca6da00cf104.png)
