### ISSUE TITLE
Excel-Download funktioniert nicht immer

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#59]
Die Excels lassen sich in IE und in Firefox nicht öffnen, ohne dass eine Fehlermeldung kommt. In Chrome kommt die Fehlermeldung, dass das Format von demjenigen in der Dateierweiterung abweiche. Wenn man dann zustimmt, dass die Datei nciht beschädigt ist, wird sie geöffnet. 

Sagt dir das was?

**Comment by jb3-2** [comment]
Ja, das ist wie bei SAS auch ein Problem von Excel: der Inhalt der Datei ist nicht im Excel Format, die File Endung aber schon. 

Machen kann man da nichts, höchstens die Option "xls" ausblenden. Soll ich dies tun?

**Comment by JE1982** [comment]
Noch nicht

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. September 2016 09:23
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Excel-Download funktioniert nicht immer (#59)


Ja, das ist wie bei SAS auch ein Problem von Excel: der Inhalt der Datei ist nicht im Excel Format, die File Endung aber schon.

Machen kann man da nichts, höchstens die Option "xls" ausblenden. Soll ich dies tun?

**Comment by JE1982** [comment]
JH testet noch etwas. Ich melde mich wieder

**Comment by JE1982** [comment]
Antwort JH: * Wenn man ein Excel-File von der Indikatoren-Website http://www.statistik.bs.ch/zahlen/indikatoren/portal.html
gibt es folgende Probleme:
 
* Wenn nan die Datei mit Chrome herunterlädt, dann kann Excel die Datei öffnen. Es gibt allerdings eine Warnung
"Sie versuchen eine Datei zu öffnen, <name>, deren Format von dem in der Dateierweiterung angegebenen abweicht. Stellen sie sicher, dass die Datei nicht beschädigt ist und aus einer vertrauenswürdigen Quelle stammt, bevor sie die Datei öffnen."
Der Grund ist, dass die Excel-Datei die Endung *.xls hat, aber eigentlich XML enthält, siehe.
https://blogs.msdn.microsoft.com/vsofficedeveloper/2008/03/11/excel-2007-extension-warning-on-opening-excel-workbook-from-a-web-site-2/
 
* Wenn man die gleiche Datei mit Internet Explorer herunterlädt, dann kann Excel die Datei nicht öffnen. Es gibt aber keine Fehlermeldung.
 
* Es gibt zwei Unterschiede zwischen mit Chrome und mit IE heruntergeladenen Dateien:
1) - Die Chrome-Datei enthält Zahlenwerte (tag <number>) formatiert mit Komma als Dezimatrennzeichen
     - Die IE-Datei enthält Zahlenwerte (tag <number>) formatiert mit Punkt als Dezimatrennzeichen
     dieser Unterschied scheint jedoch nicht der Grund für das Excel-Problem zu sein. Ersetzt man in der IE-Datei alle Punkte durch Kommas, 
     oder umgekehrt, dann hat dies keine Änderung in der Reaktion von Excel zur Folge.
2) - Die IE-Datei enthält einen alternate data stream mit dem Namen  Zone.Identifier
    - Die Chrome-Datei enthält keinen alternate data stream
     https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/
    https://technet.microsoft.com/en-us/sysinternals/bb897440.aspx
 
    Löscht man in der IE-Datei den alternate data stream, dann lässt sie sich Datei öffen.

**Comment by jb3-2** [comment]
Danke für die Analyse. Ich kann das Problem in IE nachvollziehen und schlage vor, wir verstecken den XLS Button, bis dieses Problem von HighCharts gelöst ist.

**Comment by JE1982** [comment]
Einverstanden

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. September 2016 10:39
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Excel-Download funktioniert nicht immer (#59)


Danke für die Analyse. Ich kann das Problem in IE nachvollziehen und schlage vor, wir verstecken den XLS Button, bis dieses Problem von HighCharts gelöst ist.
