### ISSUE TITLE
Arbeitsmarktmonitoring

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#590]
The Set "Arbeitmarktmonitoring" is going to be published March 13th. TSV-files are going to be produced out of SAS by LM and are ready February 20th latest. 
@jb3-2, @larafaelivrin: Could you reserve some time for setting up the charts?

**Comment by larafaelivrin** [comment]
How many charts are in this indicator set? @JE1982

**Comment by JE1982** [comment]
about 40 to 50 I think. Most of them are line-charts

**Comment by jb3-2** [comment]
This set is now live, thus I close the issue.
