### ISSUE TITLE
Charts with heights bigger than ususal overlap text below chart

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#591]
Charts with heights bigger than ususal overlap text below chart, see http://issue-585--retailer-seawater-16683.netlify.com/chart-details.html?id=5178&indikatorensetView=true&suppressNumberInTitle=true

Solution: remove fixed div height for .highcharts-wrapper
![grafik](https://user-images.githubusercontent.com/20966212/34773925-ad1a6dce-f60d-11e7-9df2-52575c564753.png)

**Comment by jb3-2** [comment]
@bl99 @larafaelivrin @JE1982 Charts can now define their own height. To use: 
`git checkout master`
`git pull`
`git checkout issueXYZ`
`git merge master`
Define height here: https://api.highcharts.com/highcharts/chart.height

**Comment by larafaelivrin** [comment]
Automatic merge failed; fix conflicts and then commit the result.
Can we look at this together after lunch?
