### ISSUE TITLE
Radio buttons do not vertically align with label

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#6]
Will only be fixed by bootstrap in V4, see [issue](https://github.com/twbs/bootstrap/issues/16426).

**Comment by ismailarilik** [comment]
@jb3-2, everyone cannot migrate to Bootstrap 4 in the short time. What are the difficulties about this issue not being fixed in a next minor version of Bootstrap 3?

**Comment by jb3-2** [comment]
No problem, I have worked around it. Thanks for asking, I appreciate that! J.

**Comment by ismailarilik** [comment]
So, what is the work-around?

**Comment by jb3-2** [comment]
I added some padding to the bottom of my radio buttons, see https://github.com/StataBS/indikatoren/commit/20d89210da3eef4dc9cdad7058df370a025677fd

**Comment by ismailarilik** [comment]
It is good for a change to font size only, but if we changed line height attribute as well? Maybe there should be a formula for margin of radio and checkboxes, which respects to font size and line height?
