### ISSUE TITLE
Anzeige Legende in Firefox 2.1.02

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#60]
Ich habe ein Mail mit Scrrenshot geschickt. Kannst Du da noch was machen?

**Comment by jb3-2** [comment]
Bitte Screenshot gleich hier im Issue anhängen.

**Comment by JE1982** [comment]
![2016-09-21 09_45_12-statistik - indikatoren zum gesellschaftlichen zusammenhalt](https://cloud.githubusercontent.com/assets/20972660/18702097/6651bbc6-7fe0-11e6-888d-d5c30f75a3c1.png)

**Comment by jb3-2** [comment]
Dieses Problem kommt auch in anderen Grafiken in Firefox vor. Mir ist nicht klar, warum in Firefox (nur unter Windows) die Schriften mehr Platz benötigen.

Idee: Wir machen es so wie aktuell bei [I.50.1.0005](https://statabs.github.io/indikatoren/chart.html?kuerzel=I.50.1.0005): 

Wir ändern das CSV, so dass keine Prozente, sondern Anzahl Antworten angegeben werden, und es wird das Template "Befragungen001" (statt befragungenProzent001) verwendet. So sieht man im Tooltip die Anzahl Antworten und die Prozente pro Segment. Das N pro Jahr kann man dann selber zusammenzählen, wenn man möchte. 

Was meinst Du?

**Comment by JE1982** [comment]
Mit der Anzeige von absoluten Werten bin ich absolut einverstanden. (Anmerkung: Dies ist m.E. genrell die bessere Art, weil so bei Ein- und Ausblenden von Datenreihen die Prozentwerte angepasst werden.) Die Ns könnten wir analog 
![2016-09-21 10_03_17-statistik - indikatorenportal](https://cloud.githubusercontent.com/assets/20972660/18702639/e3ac36bc-7fe2-11e6-99db-de112dea8fa0.jpg) 
in die Erläuterungen verpacken, dann braucht niemand manuell nachzurechnen. Ich mache das jetzt wie besprochen.

**Comment by JE1982** [comment]
BL sagt: template anpassen: Xaxys lable rotation = 0 setzen. So wird die Beschriftung immer horizontal angezeigt. Wurde lokal getestet und hat funktioniert. Kannst Du das template anpassen?

**Comment by jb3-2** [comment]
Ok mache ich heute ca. 1400.

**Comment by jb3-2** [comment]
Sind Deine letzten Commits deshalb überflüssig, oder soll ich diese übernehmen?

16d6c2f2fbb1aae6097b11e18ba9b5646cfe42e4
cec7e4a522b3105312c0e576a1d4f059b07ce4d3

**Comment by JE1982** [comment]
Danke

**Comment by JE1982** [comment]
16d6c2f<https://github.com/StataBS/indikatoren/commit/16d6c2f2fbb1aae6097b11e18ba9b5646cfe42e4> Ns löschen ist überflüssig.
cec7e4a<https://github.com/StataBS/indikatoren/commit/cec7e4a522b3105312c0e576a1d4f059b07ce4d3> Daten ersetzen bitte übernehmen

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. September 2016 11:45
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Anzeige Legende in Firefox 2.1.02 (#60)


Sind Deine letzten Commits deshalb überflüssig, oder soll ich diese übernehmen?

16d6c2f<https://github.com/StataBS/indikatoren/commit/16d6c2f2fbb1aae6097b11e18ba9b5646cfe42e4>
cec7e4a<https://github.com/StataBS/indikatoren/commit/cec7e4a522b3105312c0e576a1d4f059b07ce4d3>

**Comment by jb3-2** [comment]
@bl99 Hat das Issue gefixt in cec7e4a522b3105312c0e576a1d4f059b07ce4d3

**Comment by jb3-2** [comment]
@bl99 Super Idee, herzlichen Dank fürs Mitdenken!
