### ISSUE TITLE
automatic upload of json files

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#611]
@jb3-2: a request by UG: can we install an automatic upload of the tsv- and json-files, so that changes in data or metadata could be displayed right away using the "Vorschau"-Button?

**Comment by jb3-2** [comment]
Yes, I think this is possible. 

Idea: When clicking "Vorschau" in Access, Access Code creates metadata json file and copies it along with the tsv file to a local webserver, then opens the following address in the browser: http://local-web-server/indikatoren/chart-details.html?id=XYZ

**Comment by jb3-2** [comment]
@lcalmbach Can you please add a new button "Vorschau lokal" that does the following: 
- Create the chart's json and copy it to \\PDSTATASVSQL2\indikatoren\metadata\single
- Copy the chart's tsv to \\PDSTATASVSQL2\indikatoren\data
- Open a browser with this address (replace the id in the address with the chart's id): http://pdstatasvsql2:8089/indikatoren/chart-details.html?id=6203

**Comment by jb3-2** [comment]
I'm very happy: this works now!

**Comment by JE1982** [comment]
@jb3-2: The local preview seems not to work for internet explorer. Do you know why?

**Comment by jb3-2** [comment]
@JE1982 IE11 tried to open the page in IE7 mode. I added a html header that tells IE to open in Edge Mode, now it should work. `<meta http-equiv="x-ua-compatible" content="IE=edge"> `
