### ISSUE TITLE
Anzeige Anzahl beim Blättern

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#62]
DIe Anzaeige einer Anzahl im Stile von 1/6, 2/6 etc. wäre trotz allem hilfreich beim Blättern. Grund: So weiss man, wann man wieder am Anfang angekommen ist. Ansonsten klickt man je nachdem die ganze Auswahl mehrfach durch.

**Comment by jb3-2** [comment]
Fixed in branch issue-62, commit a4a3b965f417465df4457854d757ce3318db174f, currently on test.

**Comment by JE1982** [comment]
aus meiner Sicht in der Portalansicht ok. Die Set-Ansicht konnte ich noch nicht testen.

**Comment by jb3-2** [comment]
OK sobald Du es auch in der Setansicht getestet hast, kann ich es live setzen. Siehe z.B. 
https://statabs-test.github.io/indikatoren/?Indikatorenset=Wohnraumentwicklung

**Comment by JE1982** [comment]
Passt! Kann live gehen.

Von: Jonas Bieri [mailto:notifications@github.com]
Gesendet: Montag, 31. Oktober 2016 17:28
An: StataBS/indikatoren
Cc: Eckenfels, Jonas; Author
Betreff: Re: [StataBS/indikatoren] Anzeige Anzahl beim Blättern (#62)


OK sobald Du es auch in der Setansicht getestet hast, kann ich es live setzen. Siehe z.B.
https://statabs-test.github.io/indikatoren/?Indikatorenset=Wohnraumentwicklung

**Comment by jb3-2** [comment]
😎👍
