### ISSUE TITLE
 numbers >= 1 000 are written on two separate lines

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#624]
In the text which describes the plot of the indicators (Lesehilfe und Erläuterungen und methodische Hinweise) it is fairly often the case that numbers >= 1 000 are written on two separate lines if a line break occurs. Here an example where 840 000 is written on two separate lines.:

![image](https://user-images.githubusercontent.com/23261816/35215612-14151bc2-ff65-11e7-93e1-48833651e319.png)

Is it possible to somehow find these cases and add a line break at the beginning of the number. E.g. ig more than 6 numbers follow each other add a line break before the first number?

**Comment by jb3-2** [comment]
Try `&nbsp; ` instead of a space character. It means No Break Space, a space where no line break should occur. See https://de.wikipedia.org/wiki/Gesch%C3%BCtztes_Leerzeichen

**Comment by larafaelivrin** [comment]
Is it possible to automate the ` &nbsp;` insertion? If notit would mean that we would have to add ` &nbsp;` in each comment field in the Access database because people who write the comments are not aware of this problem.

**Comment by JE1982** [comment]
because we work on automatic generation of word-documents out of access-app it makes more sense to put the html code in the access-app instead of fixing the problem while building the chart.
