### ISSUE TITLE
integration of tableau-wohnviertel-charts in indikatorenportal

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#625]
@Nana-Mittelmaier, @jb3-2 : what is the current state concerning these tableau-charts? http://www.statistik.bs.ch/haeufig-gefragt/wohnviertel/vergleich/grafiken.html

**Comment by jb3-2** [comment]
We plan to create them as charts. I will create the template for spider (the rest of the used templates already exist in the indikatoren portal), @Nana-Mittelmaier will create the charts in the database and organize chart creation.

**Comment by jb3-2** [comment]
We work on this in #637
