### ISSUE TITLE
update indicator 4823 and children and 4834 and children

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#626]
@jb3-2:  5121 (child of 4834) and 5110 (child of 4823) are shown on our website as Einzelansicht (not only in Indikatorenportal). Now that new data is available, they have to be updated. But as they are part of the Set Wohnviertel, they can not be updated running the normal process. and we cannot wait until, the last indicator of the Set Wohnviertel is ready to be updated.

There are also other indicators in the Set Wohnviertel that could be updated, especially the ones concerning "Bevölkerung". 

How do we solve this?

**Comment by jb3-2** [comment]
@JE1982 Please call me or find me at my desk so that we can solve this.

**Comment by JE1982** [comment]
we do not need this issue anymore because the mentioned charts are live.
