### ISSUE TITLE
Replace Tableau Vizzes of Quartierportraits / Wohnviertel with Highcharts

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#637]
- [x] Create spider template --> spider001

- [ ] Replace existing Tableau-based charts --> to be done by @Nana-Mittelmaier with help of @larafaelivrin

**Comment by jb3-2** [comment]
I started creating the spider template, see http://issue-637--retailer-seawater-16683.netlify.com/chart.html?id=9996

**Comment by jb3-2** [comment]
Here's the current Tableau Spider/Radar: https://public.tableau.com/shared/XH6N9W3WM?:display_count=yes

**Comment by JE1982** [comment]
looks good to me and to formale Redaktion.

**Comment by jb3-2** [comment]
Pre-generated SVG does not look good in Chrome or IE (Firefox is ok) if HTML is used to control line breaks in xAxis labels: 

![image](https://user-images.githubusercontent.com/7261044/37974403-2532fb90-31dd-11e8-9975-a215867c9352.png)

Highcharts Forum Entry created, waiting for reply: https://forum.highcharts.com/post140072.html

This is actually very similar to the problem we have with chart [6363 ](https://statabs.github.io/indikatoren/chart-details.html?id=6363)- there we just made in visibleInPortal:false so that its SVG File is never used.

**Comment by jb3-2** [comment]
Idea about controlling line breaks in labels: do not use html, but use "\u00a0" as nbsp character, as stated here: https://github.com/StataBS/indikatoren/issues/544#issuecomment-353566243

**Comment by jb3-2** [comment]
Line breaks now work in interactive chart and also in SVG without resorting to html: In tsv, we use `&nbsp;`, at runtime, this is replaced by non-break-space unicode sign `\u00A0`: 

![image](https://user-images.githubusercontent.com/7261044/38666761-05143dbe-3e40-11e8-822b-a58938fe2b21.png)

**Comment by jb3-2** [comment]
Pleas do not forget the subtitle, otherwise the grey area gets too big.

**Comment by JE1982** [comment]
@jb3-2: could you please update the jsons because we did some changes in metadata.

**Comment by jb3-2** [comment]
@JE1982 Metadata updated, see https://issue-637--retailer-seawater-16683.netlify.com/?Indikatorenset=Wohnviertel

**Comment by JE1982** [comment]
@jb3-2: this set can go live as soon as @Nana-Mittelmaier has updated the magnolia-page.

**Comment by jb3-2** [comment]
@Nana-Mittelmaier @JE1982 Please go live with the magnolia page using this url for the iFrame: 

http://issue-637--retailer-seawater-16683.netlify.com/?Indikatorenset=Wohnviertel

After this is live, I will merge this branch into master and put it into live. Then you can change the iFrame url to:
https://statabs.github.io/indikatoren/?Indikatorenset=Wohnviertel
