### ISSUE TITLE
New template bubble001

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#644]
2d bubbles. 

![image](https://user-images.githubusercontent.com/7261044/35628429-2bed316a-069c-11e8-9205-37ed49150085.png)

**Comment by jb3-2** [comment]
dataLabel position: See https://github.com/highcharts/highcharts/issues/2705

Maybe this only works fine with latest Highcharts version?

**Comment by jb3-2** [comment]
@JE1982 @larafaelivrin Bubble chart is now available, use template 'bubble001' and see how to code a chart by copying from 9997, see https://statabs.github.io/indikatoren/chart-details.html?id=9997 
![image](https://user-images.githubusercontent.com/7261044/35728551-33e08b1c-080c-11e8-8e83-77a9ab628648.png)

**Comment by larafaelivrin** [comment]
What does the size of the bubble represent? I find the labeling of the points a bit confusing. Why do we only label the points with the value of the x-Axis and not with the values of the bubble size? I would only label them with their name (country name in this case) as this makes the plot a bit "calmer" in my opinion. I also think that the tooltip needs to be improved. The colouring of the bubbles also confuses me a bit. I guess Switzerland is coloured blue and foreign contries red?

**Comment by jb3-2** [comment]
Go ahead and configure the chart as you please when you implement a bubble chart. 9997 is a reference implementation that is pretty close to the original from Excel (see screenshot at the top of this issue's page).
