### ISSUE TITLE
Downloading *.tsv of indicator sets

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#646]
It would be nice if it would be possible the download all *.tsv of an indicator set of the master branch from github automatically. 

Momentarily one can download the *tsv via the indicator dropdown:

![image](https://user-images.githubusercontent.com/23261816/35632199-5507b282-06a6-11e8-9c12-46745699977b.png)

**Comment by jb3-2** [comment]
Download the whole repo as a zip and load the required tsv files form folder data/[setname]: 

e.g. https://github.com/StataBS/indikatoren/tree/master/data/sets 

Alternatively use a Chrome extension like GitZip to download only a subfolder of the repo. 

See #803
