### ISSUE TITLE
Add indicator for population by 20 year age classes and wohnviertel for LOD pilot

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#649]

**Comment by jb3-2** [comment]
@JE1982 Could you please create an indicator with metadata in the db (template: template001) so that this guy here (http://issue-649--retailer-seawater-16683.netlify.com/chart-details.html?id=9996) has a correct id and I can publish it? Thanks!

**Comment by JE1982** [comment]
I will do so. We need CM to complete it.
@jb3-2: I think you should build the chart the other way round. Means: people from 0 to 19 are on the bottom, the oldest ones on top of the bars.

**Comment by jb3-2** [comment]
OK will do. I have created the chart in the db: 6502.
