### ISSUE TITLE
same data format in charts/maps and tsv (e.g. 40% vs. 0.4)?

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#665]
@jb3-2: I think it would be good if the data that can be downloaded as tsv has the same format as the data shown in charts and maps (see e.g. 5119, where % in map and 0.xx in tsv).

**Comment by jb3-2** [comment]
I agree. This needs to be checked and corrected. @JE1982: Let's see who wants to check all charts for consistency and correct the chart template where necessary so that metadata fits data.
