### ISSUE TITLE
Indikatorenset Tourismus

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#672]
we need 13 charts out of the Indikatorenset "Tourismus" to be published on feb 15th. @jb3-2: could you please take care of the charts? The metadata is managed by DZ, the data is only available in Excel. The Excel-Files are in this folder:  \1_Arbeitsbereiche\2_Wirtschaft_Arbeit\10_Tourismus\02-Hotels\Daten\Produktion_MM\2017\Jahresbericht\Grafiken\KÜRZEL-KUNDE_TITEL.xlsx

**Comment by jb3-2** [comment]
@JE1982 Please add orderKey.

**Comment by jb3-2** [comment]
@JE1982 You can check the current state here: http://issue-672--retailer-seawater-16683.netlify.com/?Indikatorenset=Tourismus

**Comment by jb3-2** [comment]
Multiple legend titles and different alignment within line: Created Highcharts forum support call here: https://forum.highcharts.com/topic40194/

**Comment by jb3-2** [comment]
@JE1982 Can I push these charts into the portal by merging branch issue-672 into master branch?
