### ISSUE TITLE
6549: Add Country Name to Tooltip

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#677]
- [ ] 6549: why does the formatter: function() not work?

**Comment by jb3-2** [comment]
@larafaelivrin I cannot find chart 6549, in which branch should I find it?

**Comment by larafaelivrin** [comment]
Tourismus (issue-672): Let's discuss this tomorrow

**Comment by jb3-2** [comment]
I think you have solved this, thus I close the issue.
