### ISSUE TITLE
Reatailer-seawater does not seem to update

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#678]
Retailer-seawater does not seem to update changes in branch issue-555. Eg. for ID 6059 the title and subtitle do not match: 

**Retailer Seawter**
![image](https://user-images.githubusercontent.com/23261816/36385895-4de65ec0-1594-11e8-945c-e4b4049a3dc2.png)
https://issue-555--retailer-seawater-16683.netlify.com//chart-details.html?id=6059
- "title":"Ausländer nach Staatsangehärigkeit (Ländergruppe) 1997-2016",
- "subtitle":"",

**Github**
https://github.com/statabs-test/indikatoren/blob/issue-555/metadata/single/6059.json
https://github.com/statabs-test/indikatoren/blob/issue-555/metadata/sets/Integration.js

- "title":"Ausländer nach Staatsangehörigkeit (Ländergruppen)",
- "subtitle":"Ländergruppen",

**Comment by jb3-2** [comment]
Have you run npm run build, then git add, commit, push?

**Comment by larafaelivrin** [comment]
yes.

**Comment by jb3-2** [comment]
Netlify had problems, now it seems to work again. 

I have deleted the netlify build cache, merged the master branch into branch issue-555 to get the latest updates into this branch, ran npm run build, and pushed the changes. 

@larafaelivrin It seems some charts do not work yet, are you aware of that? See Screenshot: 
http://issue-555--retailer-seawater-16683.netlify.com/?Indikatorenset=Integration 

- 6512
- 6513
- 6516
- 6517

![image](https://user-images.githubusercontent.com/7261044/36422615-1639f7b2-163d-11e8-8cd4-be8c8d938863.png)

**Comment by larafaelivrin** [comment]
The above mentioned IDs do not work as the data is not yet prepared. 

how to you  deleted the netlify build cache?
