### ISSUE TITLE
xAxis round problem

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#689]
When using **return Highcharts.numberFormat((this.value*100),0)+'%';** the axis label values are rounded:
Eg: branch: 683; ID: 6460 

"yAxis": {
  	//"min": 0,
  	//"max": 0.5,
    "labels": {
    rotation: 0,
    "formatter": function(){
        **return Highcharts.numberFormat((this.value*100),0)+'%';** 
      }, 
      tickInterval: 2,
     "format": "{value}*100%" ,
     style: { 
			textOverflow: 'none' // prevents ellipsis
		} 
    }    
  },

See  x-Acis: 0,3,5,8,10,13,15:
![image](https://user-images.githubusercontent.com/23261816/36673773-2933a8ec-1b04-11e8-900f-a7de1178f01b.png)

Have we already encountered this problem and how did we fix it?

**Comment by jb3-2** [comment]
Branch issue-689, chart 6460

**Comment by larafaelivrin** [comment]
Solution: tickInterval: 0.02
