### ISSUE TITLE
spacing in chart

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#692]
There is a lot of space left and right of the plot (see black circles in image below). Any idea which paramter reduced this space?

http://issue-585--retailer-seawater-16683.netlify.com//chart-details.html?id=5141&indikatorensetView=true&suppressNumberInTitle=true

![image](https://user-images.githubusercontent.com/23261816/36782535-8b4080b6-1c79-11e8-87a4-719209eb96bc.png)

**Comment by jb3-2** [comment]
![image](https://user-images.githubusercontent.com/7261044/36787188-8199b91e-1c89-11e8-90d9-abb6bb712fc7.png)
