### ISSUE TITLE
Tooltip: add x-axis value

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#693]
http://issue-585--retailer-seawater-16683.netlify.com//chart-details.html?id=5137&indikatorensetView=true&suppressNumberInTitle=true

This part of the tooltip does not lead to the expected result:  "headerFormat": '{point.x}: "I want to print the year Eg: 

1997
Gesamtbevölkerung: 194 253
Ausland: 51 974
....

**Comment by jb3-2** [comment]
![image](https://user-images.githubusercontent.com/7261044/36787624-127456aa-1c8b-11e8-9cf2-6851e3933b64.png)


![image](https://user-images.githubusercontent.com/7261044/36787605-03f248c6-1c8b-11e8-95a7-9b8fee5797d7.png)
