### ISSUE TITLE
npm run reinstall before npm run build

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#694]
Oftentimes I have to run "npm run reinstall" before running "npm run build" as a blank page appears when I run "npm run build" on its own. I do not understand why this is sometimes the case and sometimes not. It seems to me that this is a bug.

**Comment by jb3-2** [comment]
This is not a bug. It stems from the fact that different branches have different dependency versions, or different version of the build script. It is always good to go to master branch, git pull, then checkout your branch, then merge master into your branch: git merge master. Sometimes you have to fix unmerged paths, but most of the time you just run npm run build and everything is fine.
