### ISSUE TITLE
Tooltip: Display categorical axis value

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#707]
http://issue-585--retailer-seawater-16683.netlify.com//chart-details.html?id=5198&indikatorensetView=true&suppressNumberInTitle=true

The header of the tooltip should display the name of the Wohnviertel. How can I accomplish this?:

![image](https://user-images.githubusercontent.com/23261816/36797275-d8397b56-1ca7-11e8-91b0-d8d10e76e91f.png)

**Comment by larafaelivrin** [comment]
@jb3-2 I could not solve the above mentioned problem

**Comment by jb3-2** [comment]
Probably best use template dotplot, and check how to use is e.g. in chart 4827 (make sure to also check how the tsv is structured): 

https://statabs.github.io/indikatoren/chart-details.html?id=4827 

![screen shot 2018-03-06 at 17 13 49](https://user-images.githubusercontent.com/7261044/37043807-f712e88c-2161-11e8-9b8a-cd493ea377ea.png)


![screen shot 2018-03-06 at 17 15 40](https://user-images.githubusercontent.com/7261044/37043835-0c252b0e-2162-11e8-9952-19da68549fe3.png)

**Comment by larafaelivrin** [comment]
I don't unerstand your function. I could use a hand. @jb3-2

**Comment by jb3-2** [comment]
ok bi schon unterwägs.

**Comment by jb3-2** [comment]
I have fixed it. How to to this easily: add `console.log(this);` into the formatter function, in Chrome press F12 and check the "this" object, than use the variables in the "this" object in the formatter function: 

![image](https://user-images.githubusercontent.com/7261044/37096677-ae940d6c-2219-11e8-9cf8-cdbe5d75761f.png)

![image](https://user-images.githubusercontent.com/7261044/37096699-c0747990-2219-11e8-8890-a7368551768a.png)
