### ISSUE TITLE
Einzelansicht: Texte und Header konfigurierbar machen via URL Parameter

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#708]

**Comment by jb3-2** [comment]
@grilli73 @Nana-Mittelmaier @JE1982 Here's how you can control which parts should be hidden, check this example link: 

https://statabs.github.io/indikatoren/chart-details.html?id=4132&hideHeader=true&hideTitle=true&hideLesehilfe=true&hideErlaeuterungen=true&hideLinks=true

- hideHeader=true
- hideTitle=true
- hideLesehilfe=true
- hideErlaeuterungen=true
- hideLinks=true

**Comment by JE1982** [comment]
thanks!
@jb3-2: maybe it would be good to have the possibility of hiding the headers of "lesehilfe" and "Erläuterungen und methodische Hinweise" but displaying the bodies. @grilli73, @Nana-Mittelmaier: what do you think?

**Comment by jb3-2** [comment]
OK I have implemented this, see the new parameters:

- hideLesehilfeTitle=true
- hideErlaeuterungenTitle=true
- hideLinksTitle=true

E.g. https://statabs.github.io/indikatoren/chart-details.html?id=6156&hideTitle=true&hideLesehilfeTitle=true&hideErlaeuterungen=true&hideLinks=true

**Comment by JE1982** [comment]
@jb3-2: it does not work i think. Lesehilfe and LesehilfeTitle are shown/hidden via "hideLesehilfe" still. "hideLesehilfeTitle" seems to have no function.

**Comment by jb3-2** [comment]
We have to be patient, github currently has problems publishing the latest commit to gh-pages.

**Comment by jb3-2** [comment]
In the meantime you can check the functionality on my vm: 

https://statabs-test-indikatoren-jonasbieri.c9users.io/chart-details.html?id=6156&hideTitle=true&hideLesehilfeTitle=true&hideErlaeuterungen=true&hideLinks=true

**Comment by jb3-2** [comment]
Jetz goht's.

**Comment by larafaelivrin** [comment]
The header should not be visible:

https://statabs.github.io/indikatoren/chart-details.html?id=6156&hideTitle=true&hideLesehilfeTitle=true&hideErlaeuterungen=true&hideLinks=true

![image](https://user-images.githubusercontent.com/23261816/36965264-75b88534-2059-11e8-9f0e-a1a714bcf055.png)

**Comment by grilli73** [comment]
@JB: Hiding the header works fine, but the chart width doesn't fit the
iframe properly. There seems to be a 40px blank space on the left margin...




2018-03-05 9:42 GMT+01:00 larafaelivrin <notifications@github.com>:

**Comment by jb3-2** [comment]
You forgot hideHeader, try this link: 

https://statabs.github.io/indikatoren/chart-details.html?id=6156&hideHeader=true&hideTitle=true&hideLesehilfeTitle=true&hideErlaeuterungen=true&hideLinks=true

**Comment by jb3-2** [comment]
@grilli73 The 40px left of the chart have always been like that, e.g. if you use the Hamburger Menu item "Einbetten".  Must this be changed before Wednesday?

**Comment by grilli73** [comment]
@jb3-2 as discussed on the phone earlier, please try to get rid of the left margin space if the Header is hidden. Necessary to have by Friday March 9

**Comment by jb3-2** [comment]
@grilli73 I have now decreased the left margin by 40px if hideHeader=true is set, see e.g. the link below. Does that work for you?

https://statabs.github.io/indikatoren/chart-details.html?id=3051&hideHeader=true&hideLesehilfeTitle=true&hideTitle=true&hideErlaeuterungenTitle=true&hideLinksTitle=true

**Comment by grilli73** [comment]
@jb3-2  works fine now. thanks a lot ;-)
