### ISSUE TITLE
Display Gliederung Stufe 3

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#711]
@jb3-2: The Set Arbeitsmarktmonitoring (issue-683) has a Stufe 3 in Gliederung. Until now we only show Stufe 1 and Stufe 2 in the Set view. 
1. Can we easily change this?
2. Can we show Stufe 3 only in the Set Arbeitsmarktmonitoring?

**Comment by jb3-2** [comment]
Yes this is possible, via an url parameter, e.g. ?stufe=3, the default would be ?stufe=2, in Legislaturplan it would e.g. be ?stufe=1. 

What should the first entry in the Dropdwon be? In stufe2 it currently is "Unterkapitel". How about again "Unterkapitel"?

**Comment by jb3-2** [comment]
GUI seems to work now, see this link (you can change the stufe parameter), filtering does not work yet. 

http://issue-711--retailer-seawater-16683.netlify.com/?Indikatorenset=Cercle-Indicateurs&stufe=3

**Comment by jb3-2** [comment]
Filtering seems to work now, too. Please test Portal and Indikatorset view. Not only the cascading stufe, but also the cascading thema / Unterthema: 

http://issue-711--retailer-seawater-16683.netlify.com/?Indikatorenset=Cercle-Indicateurs&stufe=3
http://issue-711--retailer-seawater-16683.netlify.com

**Comment by jb3-2** [comment]
@JE1982 Can you please test again? Now it's better I think. 
Filtering seems to work now, too. Please test Portal and Indikatorset view. Not only the cascading stufe, but also the cascading thema / Unterthema:

http://issue-711--retailer-seawater-16683.netlify.com/?Indikatorenset=Cercle-Indicateurs&stufe=3
http://issue-711--retailer-seawater-16683.netlify.com

**Comment by JE1982** [comment]
works well, I think. Can be set live. 
@jb3-2: where do we set the stufe parameter?

**Comment by jb3-2** [comment]
No, use stufe=1. This works:

https://statabs.github.io/indikatoren/?Indikatorenset=Wanderungen&stufe=1

https://statabs.github.io/indikatoren/?Indikatorenset=Tourismus&stufe=1

**Comment by jb3-2** [comment]
Stufe=0 does not work yet. Can you please open a new issue for this?

**Comment by jb3-2** [comment]
It currently works for stufe from 1 to 3 (not less, not more).
