### ISSUE TITLE
Sort of Stufe 2 is wrong

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#712]
@jb3-2: 
the sort of Stufe 2 in the Set Arbeitsmarktmonitoring (issue-683) is correct (as in Access) at the beginning. but after choosing one chapter and then going back to the drop down the sort changes to alphabetic. Can you check this, please?

**Comment by jb3-2** [comment]
I can also reproduce this problem with other indikatorensets, e.g. http://www.statistik.bs.ch/zahlen/indikatoren/sets/cercle-indicateurs.html
