### ISSUE TITLE
date-time-stamp "zuletzt geändert"

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#717]
@jb3-2: what do you think about a date-time-stamp "zuletzt geändert" on all of our charts? So everybody could easily see when something changed and knows about the currentness of the data.

**Comment by jb3-2** [comment]
Great idea! Can you please coordinate with @grilli73 where this timestamp should be placed in the GUI?

**Comment by grilli73** [comment]
@JE Let’s check this out on Monday

**Comment by grilli73** [comment]
@jb3-2 I'll pass on the draft to Formale Redaktion and will let you know what version can be implemented ...

**Comment by grilli73** [comment]
We have a go from KB to implement the timestamp as described in the attached pdf [Umsetzung-Zeitstempel.pdf](https://github.com/StataBS/indikatoren/files/1781103/Umsetzung-Zeitstempel.pdf)

**Comment by jb3-2** [comment]
Für mich als Zusammenfassung der Umsetzung der folgende Text: Im Anschluss an die Quelle, auf einer neuen Zeile, gross geschrieben, Doppelpunkt, DD.MM.YYY, ohne Punkt am Ende: 
Zuletzt geändert: 28.02.2018

**Comment by JE1982** [comment]
Looks very good to me.

How is this date being generated? I duscussed with @lcalmbach that it could eventually be generated in Access by changing the status to „bereit für live“ and put into the json-file. Then we would have the same date in the DB and on the chart.

What do you think?

Am 22.03.2018 um 18:48 schrieb Jonas Bieri <notifications@github.com<mailto:notifications@github.com>>:


Here's the current state of implementation, check e.g. 4154: http://issue-717--retailer-seawater-16683.netlify.com/?search=Bestand%20an%20Notwohnungen

**Comment by jb3-2** [comment]
Correct, I use the date I get from the DB, if there is one. LC's idea is gret, let's do that.

**Comment by lcalmbach** [comment]
I am not entirely clear on the meaning of the "zuletzt geändert" timestamp. The way it is implemented in the mock-up zeitstempel.pdf one would assume it is the date the data source, since it is just below it. JE suggests to set the date to the set live action in the database, and this date would therefore refer to the entire plot. I think this must be very clear to the user, and I also assume the user is more interested in the last change date of the data rather than of the creation of the plot. If we refer the change date to the datasource, then each datasource must have a change date since there may be several data sources. The easiest would be to include the date string already in the list of data sources. however if you aim rather at referring the data to the last go live status change, then I would provide the data as a separate parameter "lastChangeDate" and on the chart I suggest to name it "Grafik zuletzt geändert: 3.2.2018" so there is no mix-up with the status of the data.

**Comment by JE1982** [comment]
I think this date should be something that changes from indicator to indicator, because sometimes one has to change a detail in an indicator that already live. In my opinion the "zuletzt geändert" date should change in these cases. 
I think we should take the "set-live-date" and not the date of the Datenquelle. To know when a certain Datenquelle is updated we could have a glossar with each Datenquelle on the Website and link to this page. Because this date will be equal for several different indicators.

**Comment by jb3-2** [comment]
@lcalmbach @JE1982 Do we need a meeting in order to clarify this?

**Comment by jb3-2** [comment]
As discussed with @JE1982: The timestamps should be integrated into charts except in print view.

**Comment by jb3-2** [comment]
Setname | Datum | Bemerkung | Ausnahmen
-- | -- | -- | --
Nachhaltigkeit | 03.04.2018 |   |  
Integration | 21.03.2018 |   |  
Arbeitsmarktmonitoring | 14.03.2018 |   |  
Tourismus | 15.02.2018 |   |  
Wanderungen | 19.12.2017 |   |  
Legislaturplan | 29.11.2018 |   |  
Richtplan | 27.10.2017 |   |  
Umwelt | 11.07.2018 |   |  
Wohnraum | 28.02.2018 |   |  
Wohnviertel | 28.02.2018 |   |  
Gesellschaftlicher Zusammenhalt | 21.09.2016 |   | 4722, 4863 (28.2.2017)
Cercle indicateurs | 14.11.2017 | Publikationsdatum BFS
Übrige | 21.09.2016 |   |

**Comment by jb3-2** [comment]
@JE1982 I manually checked all charts and am pretty happy about them, see the current state here: 

- Portal: http://issue-717--retailer-seawater-16683.netlify.com/
- All on one page (click chart to open details): http://issue-717--retailer-seawater-16683.netlify.com/all.html

Please tell me if ready for live, or what's missing.

**Comment by jb3-2** [comment]
@JE1982 Is this ready for live?

**Comment by JE1982** [comment]
not yet. I try to finish it today.

**Comment by JE1982** [comment]
@jb3-2: see feedback here: 4_Monitoring_Controlling\00_Gesamtsystem\Indikatorenportal\Weiterentwicklung_Portal\Zuletzt-geändert_nach-Set.xlsx

**Comment by JE1982** [comment]
das Setzen des Aktualisierungsdatums im json funktioniert noch nicht. zT wird das Feld im json gar nicht gefüllt, obwohl es im Access gefüllt ist (6623), zT wird es mit einem alten Datum gefüllt, obwohl im Access das aktuelle drin ist (4132). @lcalmbach: kannst du dem bitte nachgehen?

**Comment by JE1982** [comment]
#872
