### ISSUE TITLE
Netlify seems not to work

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#720]
Netlify does not seem to work. Can you please check tomorrow morning @jb3-2 @JE1982

**Comment by jb3-2** [comment]
Yes, the build did not run through. I manually triggered a re-build in Netlify, now it works.

**Comment by larafaelivrin** [comment]
Netlify again does not seem to work for issue-676 @jb3-2

**Comment by jb3-2** [comment]
You are right, see screenshot. Do you also have the permissions to redeploy a build? Check this link: 

https://app.netlify.com/sites/retailer-seawater-16683/deploys

![image](https://user-images.githubusercontent.com/7261044/37095413-27dc48d2-2216-11e8-903e-ff8f18487226.png)

**Comment by jb3-2** [comment]
![image](https://user-images.githubusercontent.com/7261044/37095461-526de81c-2216-11e8-8369-dab5a8fe9f47.png)

**Comment by jb3-2** [comment]
Whould work now after manual trigger of netlify build.
