### ISSUE TITLE
The paramter "pointPlacemement" is not active when deselecting elements from the legend.

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#721]
branch: 585; ID: 6042:

The paramter "pointPlacemement" is not active when deselecting elements from the legend.

**Comment by jb3-2** [comment]
Please elaborate. I don't understand the question yet. I don't see a legend: 
![screen shot 2018-03-06 at 17 08 20](https://user-images.githubusercontent.com/7261044/37043496-0640a002-2161-11e8-8a76-5666ed183662.png)

**Comment by larafaelivrin** [comment]
you are looking at the master branch and not the issue-585.

**Comment by jb3-2** [comment]
You are right, sorry. Chume grad abe ok?

**Comment by jb3-2** [comment]
OK that was hard, I had to change the pointPlacement on hide and on show of a series: 

![image](https://user-images.githubusercontent.com/7261044/37099554-e1556550-2220-11e8-82b2-f7df88a6b6a8.png)

**Comment by jb3-2** [comment]
Alternatively: Use this solution, it will also handle columns with null value: 

https://stackoverflow.com/questions/32250844/highcharts-remove-gap-column-with-zero-value
