### ISSUE TITLE
Portalansicht: Filter und Header konfigurierbar machen via URL Parameter

### ISSUE THREAD

**Issue by grilli73** [StataBS/indikatoren#722]
@jb3-2 as discussed earlier there is no hurry to implement this, but would be nice to have by mid April...
customize the portal template as in Einzelansicht with header and dynamic filter parameters.

**Comment by jb3-2** [comment]
@grilli73 I have now implemented this, see URL below. Let me know if that fits your requirements ("isch guet so?"). Just type in the values you want to filter, the browser encodes umlauts and spaces without human intervention, see screenshot. 

http://issue-722--retailer-seawater-16683.netlify.com/?showHeader=true&search=eingeb%C3%BCrg&thema=01%20Bev%C3%B6lkerung&unterthema=Einb%C3%BCrgerungen&schlagwort=Ausl%C3%A4nder&raeumlicheGliederung=Kanton 

![image](https://user-images.githubusercontent.com/7261044/37594364-34c67e24-2b75-11e8-8ed1-359ed2f36403.png)

**Comment by grilli73** [comment]
@jb3-2 As discussed earlier, we have another idea for further improvement (see attached file):
- change the navigation link description in the header section
- hide the filter options by default (only to display if URL-show-Parameter is set to true deliberately)
- as the image grid is responsive to the browser window size: is it possible to define a maximal column width (f.e. 170 px as in the classical embedded portal view) to get a better look and fool of the thumbnail display?
![filter](https://user-images.githubusercontent.com/16594644/37611555-efd66148-2ba2-11e8-9b98-eaa44ecc9ce0.jpg)

**Comment by jb3-2** [comment]
@grilli73 Could you please create and giev me the image for the link icon, like the one we already use: https://statabs.github.io/indikatoren/assets/img/icon-link.png

**Comment by jb3-2** [comment]
How about this: 
- hideSidebar=true
- hideUnterthema=true
- all filter criteria are useable despite being invisible

http://issue-722--retailer-seawater-16683.netlify.com/?showHeader=true&hideSidebar=true&hideUnterthema=true&thema=04%20Volkswirtschaft
