### ISSUE TITLE
going-live of parent-child-indicators with different templates

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#727]
@jb3-2: we should make sure that charts with an parent-child relationship and a different template (e.g. 4833 and 5120) are going live at the same time because they are linked by the "andere Darstellungsform dieser Daten"-Button. At the moment 4833 (Dotplot) is live withe data 2017 while 5120 (map) is still live with data 2016. Any ideas how to manage this?

**Comment by jb3-2** [comment]
I think this is something we must handle in the Indikatoren Application, not in the front end.
