### ISSUE TITLE
Remove Schlagworte

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#769]
several feedbacks show, that Themenverantwortliche do not like the administration of Schlagworte. We should change the process so that Schlagworte are not needed anymore and remove them completely from the portal view. @jb3-2: could you please change the process and tell me when set, so I can manage the changes in the Access-Apps with LC.

**Comment by jb3-2** [comment]
@JE1982 @lcalmbach I have now removed Schlagwort from everywhere. Please make sure Schlagwort is also removed from the database.
