### ISSUE TITLE
map: toolitp for riehen and bettingen together

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#802]
In this map the tooltip for Riehen and Bettingen should be as follows: Riehen und Bettingen: 3
How can I accomplish this?

http://issue-801--retailer-seawater-16683.netlify.com//chart-details.html?id=6601&indikatorensetView=true&suppressNumberInTitle=true

**Comment by jb3-2** [comment]
I have implemented this in 6601.js in branch issue-801: 

![image](https://user-images.githubusercontent.com/7261044/38612342-abd711c2-3d86-11e8-9973-9461b986745f.png)
