### ISSUE TITLE
downloading all *.tsv of an indicator set

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#803]
The aim is to download all *.tsv of an indicator set into a folder. How can this be achieved easily? I thought that this could be achieved via [GitZip ](https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn?hl=en) using the merge comment status. This, however, does not seem to lead to the wished result: The [number of the comment "Legislaturplan" in github](https://github.com/StataBS/indikatoren/tree/master/data) does not match the  number of indicators in the database (128 vs. 77). See: 
![image](https://user-images.githubusercontent.com/23261816/38429998-4f7aa4b2-39c0-11e8-8899-a033fa17efc4.png)

**Comment by jb3-2** [comment]
The build script now copies each tsv into a folder named after its indikatorenset (data/sets/[SetName], see screenshot. You can download this folder using a Chrome extension like the one you mentioned above, or just download the whole repository as a zip file and use the files from there. 

![screen shot 2018-04-09 at 15 35 28](https://user-images.githubusercontent.com/7261044/38500895-f5048a72-3c0b-11e8-9f5c-ba5fb678fe11.png)

![screen shot 2018-04-09 at 15 38 48](https://user-images.githubusercontent.com/7261044/38500978-2204a494-3c0c-11e8-8717-518708d0793a.png)

**Comment by larafaelivrin** [comment]
I just realized that the *.tsv files do not contain the data but the metadata:
![image](https://user-images.githubusercontent.com/23261816/38559890-854d4baa-3cd4-11e8-92eb-5fea203cf0eb.png)
@jb3-2 @JE1982

**Comment by jb3-2** [comment]
Oops sorry will fix asap...
