### ISSUE TITLE
6033: Use template stock001

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#819]
Requested by @JE1982 28.03.2018 13:41 via DB (Email)

**Comment by jb3-2** [comment]
@JE1982 Are you happy with this?
Now: http://issue-819--retailer-seawater-16683.netlify.com/chart.html?id=6033

![image](https://user-images.githubusercontent.com/7261044/38624932-961e81f8-3da9-11e8-8ce3-91507872b3a8.png)

Before: https://statabs.github.io/indikatoren/chart-details.html?id=6033
![image](https://user-images.githubusercontent.com/7261044/38624908-8b7ac4dc-3da9-11e8-9aaa-a778f7f2aa1d.png)

**Comment by JE1982** [comment]
in general - yes! In detail: 
- I think a maximum of 50 degrees would be enough. Is this possible while keeping the axis dynamic?
- when we display all years: is it possible to describe only 20 years on the X-achsis? (remember the discussion with formale Redaktion yesterday).

**Comment by jb3-2** [comment]
@JE1982 Ok if we go live with the current version of this chart? See http://issue-819--retailer-seawater-16683.netlify.com/chart.html?id=6033

**Comment by JE1982** [comment]
yes, we can go live.
