### ISSUE TITLE
4300/6033 are not shown in Portal-view. 

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#820]
@jb3-2: Why?

**Comment by jb3-2** [comment]
Mother 4300 has visibleInPortal manually set to false in DB. In the build script, when checking if a chart should be visibleInPortal, I did only check if the mother was available, not if she was available and visibleInPortal == true. I now also check this. Now 6033 is also visibleInPortal: 

![image](https://user-images.githubusercontent.com/7261044/38672142-9ff71434-3e4d-11e8-8d22-7c682c529329.png)
