### ISSUE TITLE
Setting of "verantwortlich für Indikatorenset" in Zuständigkeits-Datenbank

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#833]
Right now it is possible to set "verantwortlich für Indikatorenset" in Zuständigkeits-Datenbank and in Indikatoren-App. But only the setting in Indikatoren-App works. 

We should change this because "verantwortlich für Indikatorenset" belongs to general metadata and should be set in Zuständigkeits-Datenbank.

**Comment by lcalmbach** [comment]
in the list indikaotrenset in the indikatorenapp I changed the source for the reposonisble person to the table stata_produkte.indikaotrenset_mitarbeiter. as soon as we set this version active, we should delete the field verantwotlichid from teh indikaotrenset table, and make sure it is not used anywhere.

**Comment by JE1982** [comment]
this seems not to work properly in any case: 6619 does not have a responsible person for its set in the header (and for the indicator itself neither. see:

P:\1_Arbeitsbereiche\4_Monitoring_Controlling\Admin\Screenshots\Fehler\Header_Testindikator.png

**Comment by JE1982** [comment]
- it seems not to work properly in every case. 6776 does not have a "setverantwortliche Person".
