### ISSUE TITLE
Show the name of the pictured area in subtitle

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#837]
we need to show the pictured area of each indicator in its subtitle if it is not shown in the chart itself. Can we solve this by automation or does this lead to errors? 
@bl99, @jb3-2, @larafaelivrin: any ideas how it could be managed?

**Comment by larafaelivrin** [comment]
I am not sure if the informatino of "Räumliche Gliederung" is always filled out correctly in the database. I have the feeling that this information has not always been validated. We should check this.

**Comment by JE1982** [comment]
We solved this by manual addition to the subtitles in Access.
