### ISSUE TITLE
Legend corrections

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#842]
In this branch the following ID are corrected :
https://docs.google.com/spreadsheets/d/1wQ_XS-S13u-tUYa7UoCkCa3WEeEGMXPRrOakXxY5vGs/edit?usp=sharing

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Is this all finished? Can this go live, or is any work from my side necessary?

**Comment by larafaelivrin** [comment]
@JE1982  @jb3-2  I am honestly not so sure. I thought this went live months ago. I am a bit afraid that we overwrite things we changed since then as we got a lot of input from the formale Redaktion on other people in the meantime. But I checked and there are still some things that are not implemented in the current master branch. Eg. ID 4463: the legend is still bold.

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 I close this issue since the rules of FR have changed and we need to re-evaluate every chart anyway.
