### ISSUE TITLE
New set integration Print

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#843]
The Set "Integration" is being updated until end of July. The new PDF should be published in November 2018. The charts for the PDF are going to be produced in Highcharts. 

To get "perfect" Print-charts we need to implement some more feedback from formale Redaktion. @jb3-2: let's discuss the best way.

**Comment by JE1982** [comment]
1. Generate Print-Set (JE)
2. Produce Print-charts following the rules for Web-charts (JB)
3. Show them to formale Redaktion for review 
4. Establish general rules for Print-charts

**Comment by JE1982** [comment]
@jb3-2: we already planned how to get this one done. 
First step done, Print-Set is created in Access.

**Comment by jb3-2** [comment]
Implementation is done in branch issue-891 (https://github.com/statabs-test/indikatoren/tree/issue-891)

I therefore close this issue, we don't need 2 for the same task.
