### ISSUE TITLE
Small corrections on Indikatoren-App

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#848]
- Name Indikatorenset in Ordnerstruktur (Kurzbezeichnung) ≠ Name Indikatorenset in Liste der indikatoren, Spalte "Indikatorenset" (Bezeichnung lang)
- Feld "Aktualisierung Letzte": Da es nicht bearbeitet werden kann, sollte sich auch keine Kalenderansicht öffnen, wenn man reinklickt. 
- Status-Log Mail: Im Betreff bitte noch das Indikatorenset anzeigen.
- Tab "Daten": Feld "Basis-Indikator" etwas breiter machen.  
- "Schliessen"-Knopf in der Übersichts-Liste muss weiter nach links, damit er bei allen MA ohne Scrollen angezeigt wird.

**Comment by bl99** [comment]
![grafik](https://user-images.githubusercontent.com/20966212/39299589-5f8c725c-4949-11e8-904d-baec17ca9bba.png)

**Comment by JE1982** [comment]
Der Knopf Basis-Indikator entfernen im Reiter "Daten" zeigt keine Wirkung (Bsp. 5793, 4349 kann gelöscht werden):
grafik

**Comment by JE1982** [comment]
- Filtering "Verantwortlich", "Nächste Aktualisierung" and "Indikatorenset" all together does not work properly.
see:
![multi-filter](https://user-images.githubusercontent.com/20972660/40605854-e10b4fc8-6263-11e8-82e0-1f90cbc56705.png)

**Comment by JE1982** [comment]
- Tabs can't be closed by righ click "Schliessen" anymore. Thus we need a "Schliessen"-Button in all Tabs. Tabs like "vAnzeigeDaten" do not have a "Schliessen"-Button right now.

**Comment by JE1982** [comment]
since I pushed the button "Export set als Print" this note does not disappear anymore. 
![anzeige_printbericht-erstellen](https://user-images.githubusercontent.com/20972660/38927406-f24a0bd0-4305-11e8-9492-7cf18d4e4c56.png)

**Comment by lcalmbach** [comment]
Name Indikatorenset in Ordnerstruktur (Kurzbezeichnung) ≠ Name Indikatorenset in Liste der indikatoren, Spalte "Indikatorenset" (Bezeichnung lang)
Feld "Aktualisierung Letzte": Da es nicht bearbeitet werden kann, sollte sich auch keine Kalenderansicht öffnen, wenn man reinklickt. LC: ok
Status-Log Mail: Im Betreff bitte noch das Indikatorenset anzeigen. LC: ok
Tab "Daten": Feld "Basis-Indikator" etwas breiter machen. LC: OK
"Schliessen"-Knopf in der Übersichts-Liste muss weiter nach links, damit er bei allen MA ohne Scrollen angezeigt wird. LC: OK

**Comment by lcalmbach** [comment]
Meldung bei klicken auf Version: was da wie eine Fehlermeldung aussieht ist der Erklärungstext zur Version. Die Idee war, dass man einsehen kann, was zuletzt geändert wurde. ich sehe aber schon, dass das für den Normaluser nix wirklich bringt und habe es entfernt

**Comment by JE1982** [comment]
- Der Knopf Basis-Indikator entfernen im Reiter "Daten" funktioniert noch nicht
