### ISSUE TITLE
Update Indikatorenset Wanderungen

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#851]
**6025**: The export of the [map 6025](https://statabs.github.io/indikatoren/chart-details.html?id=6025) does not work properly. The pies are not plotted. Instead line artefacts appear: @jb3-2 is there a solutiont o this behaviour? Could you let me know until beginning of next week? We need to update this maps (web and print) and I think it would be nice to try to use this platform to create both.

![1-10](https://user-images.githubusercontent.com/23261816/39355452-9469b6aa-4a0d-11e8-8135-4c5ce5884685.png)

**6022**: The export of the [map 6022](https://statabs.github.io/indikatoren/chart-details.html?id=6022) works nicely but there is a problem with the bar width. Also in the web version. Not all bar widths are equal (e.g. the bar width for Bettingen is smaller and in St. Johann there is a gap between the bars)  @jb3-2 
![1-12](https://user-images.githubusercontent.com/23261816/39355534-c44a2378-4a0d-11e8-95c6-df297ca12e6a.png)

**60221** is the test print version of 6022 (I currently haven't figured out how to create an print indicator using the new Indikatoren-App). It looks good but has the same problems as 6221 (see above):
![1-12](https://user-images.githubusercontent.com/23261816/39364875-bae3b188-4a2f-11e8-84a1-79b458a098b5.png)

**Comment by jb3-2** [comment]
@larafaelivrin Regarding different width of columns: I have asked this question in the Highcharts forum and wait for an anser, see https://forum.highcharts.com/post140729.html#p140729

**Comment by jb3-2** [comment]
Regarding 6025: The solution is to disable animation for the pies (see screenshot). Please do this for the print template.

![image](https://user-images.githubusercontent.com/7261044/39422826-4cf9df20-4c6f-11e8-8509-4f73403b3b98.png)

**Comment by jb3-2** [comment]
6022 is OK but not perfect, column width still not equal every time. Waiting for feedback from Highcharts forum, see https://github.com/StataBS/indikatoren/issues/851#issuecomment-385341148

**Comment by larafaelivrin** [comment]
6025 (onlin) - 6774 (print)
6022 (online) - 9071 (print)

**Comment by jb3-2** [comment]
Branch #915 has been merged into this branch.
