### ISSUE TITLE
Basis-Indikatoren: optimization of GUI

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#852]
The status for the metadata and chart should not exist for "Basisindikatoren" as it confuses people:

![image](https://user-images.githubusercontent.com/23261816/39366375-0b6fbbfc-4a34-11e8-9c6a-ed38b904b5b2.png)

**Comment by JE1982** [comment]
Tab "Daten":
If "Datenquellentyp" = "DWH" then we don't need the Button "Daten erfassen".

**Comment by JE1982** [comment]
Tab "Status-Log":
"werden" anstelle von "wreden" im Erläuterungstext zum Status "Aktualisierung fällig". 
![bi-status-log](https://user-images.githubusercontent.com/20972660/39523067-adc04654-4e14-11e8-91b1-15727caefe53.png)
