### ISSUE TITLE
App: "BI entfernen" funktioniert nicht

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#866]
@lcalmbach: Der Knopf Basis-Indikator entfernen im Reiter "Daten" zeigt keine Wirkung (Bsp. 5793, 4349 kann gelöscht werden):
![grafik](https://user-images.githubusercontent.com/20966212/39619138-f6efde3e-4f86-11e8-8d0b-2f9410f762db.png)

**Comment by JE1982** [comment]
#848
