### ISSUE TITLE
Datumsfeld in json

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#872]
das Setzen des Aktualisierungsdatums im json funktioniert noch nicht. zT wird das Feld im json gar nicht gefüllt, obwohl es im Access gefüllt ist (6623), zT wird es mit einem alten Datum gefüllt, obwohl im Access das aktuelle drin ist (4132). @lcalmbach: kannst du dem bitte nachgehen?

**Comment by lcalmbach** [comment]
the date Letztesaktualisierungsdatum is defined as the date for the last chartstatus = live status for the respective indicator. the json export still used the old status field in the indicator table itself, which is not used anymore. this works correctly, however I have ssen, that the initial setting is wrong for many indicators: the show the status live (for performance reasons a field in indicator table, synchronized with the status log), however there is no entry in the status log . I need to generate the status log entries to initialize the correct setting where it has not been initialized.

**Comment by JE1982** [comment]
to be precise: the date Letztesaktualisierungsdatum should have the date for the last chart-status = "Bereit für live" and not "Live". Is the date correctly filled from this moment or do we have to wait another action from @lcalmbach to update the jsons?
