### ISSUE TITLE
Print-Indikatoren: Datenaufbereitungstyp gleich wie bei Mutter

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#876]
Bei Erstellen eines Print-Sets in der Indikatoren-App erhalten nicht alle Print-Kinder automatisch denselben Typ der Datenaufbereitung wie die Mutter. Es scheint so zu sein, dass solche mit Status "Aktualisierung fällig" den Typ der Mutter nicht übernehmen. Bsp. 6088. 
@lcalmbach: bitte kurz pürfen.

**Comment by lcalmbach** [comment]
beim kopieren im Code wird das Feld DAtenaufbereitungsprozess gesetzt. habe es mit der Mutter 6616 und Kind 2017 durchgespielt und der Datenaufbereitungsprozess wurde mitgegeben. ev. gibt es einfach noch einige records, die falsch initialisiert wurden und seither noch nie gespeichert wurden. das Paar 6088/6671 hat auch den gleichen DAtenaufbereitungstyp SAS.
