### ISSUE TITLE
Auto-mails by status

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#885]
- the status "Bereit für live" should push an email to JB but it does not. 
@lcalmbach: could you please fix this?

**Comment by JE1982** [comment]
the status "Formal überprüft" should pusch an email to JE but does not.

**Comment by JE1982** [comment]
- the status "Aktualisiert" should push an email to "Setverantworticher" but I think it does not. 
- for indicators with Thema 50 "Befragungen" or Thema 85 "Statistik" AND Unterthema "Befragungen für öffentliche Organe" the status "Aktualisert" should push an email to PTL Befragungen (currently MT) and not to "Setverantwortlicher"

**Comment by JE1982** [comment]
- we should check all automatic mails together.

**Comment by lcalmbach** [comment]
Automail was fixed for Status überprüft, formal überprüft, ready for live. This did not work before, becuase tehre was no filte rfor the newest status, so if any status was st the to required status, e.g. überprüft, the mail would fire the next day, but it should only for the chart status. also, in some cases, the recipient adress was incorrect.
The case: aktualisiert is still open and does not trigger a mail yet,

**Comment by lcalmbach** [comment]
all notification types are now implemented and executed daily. LC receives the cc and verifies if the sent mails are correct. Please control on your side, whether there are indicators status changes, that should habe triggered a mail but have not.
