### ISSUE TITLE
Indikatorenset: Integrationsindikatoren (Print)

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#891]
In this branch the print indicators for the set "Integrationsindikatoren" are created.

**Comment by jb3-2** [comment]
@larafaelivrin You are right. I have fixed the path in branch issue-891. Pleas pull from repo.

**Comment by larafaelivrin** [comment]
npm run build gives the following error:

Exception reading images/portal/6703.svg
/home/ubuntu/workspace/node_modules/svgo/lib/svgo.js:44
                callback(svgjs);
                ^

TypeError: callback is not a function

**Comment by jb3-2** [comment]
I cannot reproduce this exception on my machine. Please update all dependencies (npm run reinstall). Let me know if this helps.

**Comment by larafaelivrin** [comment]
yes, it worked. let me know if you need more help with the print indicators today or tomorrow.

**Comment by larafaelivrin** [comment]
List of IDs where the height should be bigger than usual @JE1982 

- 6746
- 6742
- 6741
- 6740
- 6739
- 6738
- 6737
- 6736
- 6735
- 6723
- 6713
- 6698
- 6697

**Comment by larafaelivrin** [comment]
I see that changes have been made on the 21.06.2018 and that the spacing has been changed in the templates. I am not sure how to continue @jb3-2

**Comment by JE1982** [comment]
@larafaelivrin, @jb3-2:  Feedback JE: 1_Arbeitsbereiche\4_Monitoring_Controlling\Indikatorensets\Integration (Print)\2018\png\Feedback_JE_20180625.xlsx

**Comment by JE1982** [comment]
@jb3-2: i have implemented the chart Format "large" in every chart that has to be large. And I have sent some Mails to you and @larafaelivrin with corrections requested by FR and me. Can you work on them tomorrow?

**Comment by jb3-2** [comment]
@JE1982 Setting the size of the chart is not yet supported in the application. I can work on it tomorrow or start right now if it is urgent.

**Comment by JE1982** [comment]
what do you mean by "is not supported"? I implemented it in the Access-DB and it is part of the json-file. 
I think working on it tomorrow should be ok I think.

**Comment by jb3-2** [comment]
I mean "I have not implemented it in Indikatorenportal yet" with that. No worries. Will do it tomorrow.

**Comment by larafaelivrin** [comment]
I am not here for the rest of the week. I can work on this indicators next Monday and hope that we can still make the deadline then.

**Comment by JE1982** [comment]
I will forward the mails I sent you to @jb3-2: then we will see what is to do on Monday.
