### ISSUE TITLE
Format of Print-Indicators in Access

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#902]
we need to have the possibility to set the format of print-indicators in the Indikatoren-App. The information should be part of the json-file. we don't need the excact width and height, we just need types like "small", "large" and "map" right now.

**Comment by lcalmbach** [comment]
I have create the new code printFormat and intitialized it with small, large, map. additional codes can be added. it is integrated in the table Indikator as well as in the GUI (tab Chart) but shown only for print indicators. example output:

{"title":"Anzahl Ausländer nach Staatsangehörigkeit",
"subtitle":"",
"kuerzel":"I.01.1.06059",
"kuerzelKunde":"A1-4",
"description":"Anzahl Ausländer nach Staatsangehörigkeit",
"id":6644,
"thema":"01 Bevölkerung",
"unterthema":"Bestand und Struktur ",
"kennzahlenset":"Integration (Print)",
"raeumlicheGliederung":["Kanton"],
"aktualisierungsdatum":"",
"stufe1":"Kapitel A Bevölkerungsstruktur",
"stufe2":"",
"stufe3":"",
"stufe4":"",
"stufe5":"", 
"lesehilfe":"Ende 2016 bildeten die Deutschen mit 16 066 Personen die grösste Bevölkerungsgruppe im Kanton. Ihre Anzahl ist seit 2002 kontinuierlich gestiegen. Diesem Anstieg steht ein Rückgang der Anzahl Italiener, Türken und Personen aus dem Balkan gegenüber, wobei die Anzahl Italiener seit 2013 wieder leicht zugenommen hat.",
"erlaeuterungen":"",
"template":"template001_print",
"printformat":"large", 
"visible":true,
"visibleInPortal":false,
"orderKey":"01_00_00_00_00_000",
"parentId":6599,
"children":[],
"renderLink":[],
"quellenangabe":["Statistisches Amt Basel-Stadt, Bevölkerungsstatistik"],
"externalLinks":[""]
}

**Comment by JE1982** [comment]
ok for me. @jb3-2: and for you?

**Comment by jb3-2** [comment]
Tip top.
