### ISSUE TITLE
Update Umwelt-Indikatoren

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#913]
@lcalmbach please run update process for Umwelt-Indikatoren and inform @jb3-2 when done

**Comment by JE1982** [comment]
@bl99: I think we need to change the responsible persons for the indicators from thema 08 "Energie" in the set "umwelt" from BL to LB. Are you ok with this?

**Comment by JE1982** [comment]
@lcalmbach: could you please run the process mentioned by @bl99? There are several indicators that need to be updated.

**Comment by bl99** [comment]
@lcalmbach anything missing from my side to run the import?

**Comment by jb3-2** [comment]
I have started working on this together with #835 in branch issue-835.
