### ISSUE TITLE
Wohnviertel: Changes in Indikator Value as line chart

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#923]
Like the one we did last year in Tableau: 

https://public.tableau.com/shared/5MYZS6NJC?:display_count=yes 

![image](https://user-images.githubusercontent.com/7261044/41398743-a28a0412-6fb8-11e8-9df5-4bdd4f1becfe.png)

**Comment by JE1982** [comment]
I would not push this, because I don't see people waiting for this. @jb3-2: Do you?
