### ISSUE TITLE
Re-organize set Umwelt

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#931]
We need to change the responsible persons for the indicators that belong to a thema managed by a member of stata, so these persons are able to take the responsibility for their indicators. 

therefor we need to do some adjustments to the update-process. these are:

- [x] define which indicators are managed by a stata-member and inform @lcalmbach : @bl99 
- [x] find a way to identify and mark these indicators in Access: @lcalmbach, @bl99  
- [x] for indicators managed by a stata-member the data should be eliminated from highcharts-code and the tsv-file from Access should be used instead: @jb3-2  
- [x] changes of responsibilities in Access: @bl99 
- [x] find a way to manage the item "Beschreibung/Definition" used in umweltbericht in Access: @bl99, @lcalmbach  
- [x] the import-process should only work for umwelt-indicators not managed by a stata-member: @lcalmbach 
- [x] umwelt-indicators not managed by a stata-member should be imported with status = "Überprüft": @lcalmbach 
- [x] auto-mails for indicators of the set umwelt should go additional to @bl99 when status = "Bereit für live": @lcalmbach

**Comment by jb3-2** [comment]
@bl99 Yes I can do that, is there a chart I can start working on?

**Comment by bl99** [comment]
@lcalmbach has already prepared TSV for Energy-Indicators, e.g. 4321 or 4322

**Comment by JE1982** [comment]
@bl99: there are several indicators in portal-view that need to be updated with "new" data from 08 Energie:
- [ ] 4229
- [ ] 4224
- [ ] 4221
- [ ] 4230
- [ ] 4322
- [ ] 4352
- [ ] 4223
- [ ] 4321
- [ ] 4225

**Comment by bl99** [comment]
@JE1982 they will be either updated:
- by @lcalmbach as soon as the complete process is implemented by him& @jb3-2 , see above
- as soon as 08 Energie is update in Umweltbericht (this tasks is pending at the AUEs)

**Comment by JE1982** [comment]
@bl99, @lcalmbach: can they yet be flagged and given to their respective "owner" for being updated?

**Comment by bl99** [comment]
@jb3-2 what is the status of: for indicators managed by a stata-member the data should be eliminated from highcharts-code and the tsv-file from Access should be used instead? 
(@lcalmbach wants to test the process with energy indicators next week)

**Comment by jb3-2** [comment]
@JE1982 I have not started implementing this yet, will start Monday. 

Todo by JB: 
- In Build: In Build:umwelt_charts: if (! datenInChartIntegriert): Create js from chart json:
1. Remove data
2. Wrap json in self-executing function
3. Save in chart/templates folder. 
- On Page: If ("datenInChartIntegriert" == false): Treat like a regular (non-umwelt) chart by loading js, tsv and json separately

**Comment by bl99** [comment]
@jb3-2 can this issue be merged to master so that @lcalmbach can test with his TSV on the local system?
