### ISSUE TITLE
New Visualization for "Sozialhilfe"

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#950]
I implemented the changes discussed with MB @JE1982 . See:

http://issue-950--retailer-seawater-16683.netlify.com//chart-details.html?id=6182&indikatorensetView=true&suppressNumberInTitle=true

http://issue-950--retailer-seawater-16683.netlify.com//chart-details.html?id=6427&indikatorensetView=true&suppressNumberInTitle=true

I am not sure weather **return this.name.slice(0, -7)** is the best solution.  Maybe @jb3-2  knows a better way. 

JB: @larafaelivrin I replaced this with **return this.name.slice(0, this.name.indexOf('(Stadt)'));**

**Comment by JE1982** [comment]
@larafaelivrin 
- 6182 looks good to me. Except the dots on the line for Total. These have to be removed due to the rules of Formale Redaktion. 
- 6427 should be a little larger I think. Because now the dots are to close to each other.

**Comment by larafaelivrin** [comment]
6182: In my opinion the legend looks better when it is placed on top (like 6427). I think it is slightly confusing when the points (2017) are followed by the legend lines as it somehow seems as if the the points are part of the legend:

![image](https://user-images.githubusercontent.com/23261816/42810719-e207ca06-89b8-11e8-87d6-ef2b41dc707a.png)

**Comment by jb3-2** [comment]
I have decreased the radius of the markers to 2 and cleaned up the config a bit, now it looks good to me.

**Comment by larafaelivrin** [comment]
@jb3-2  when disabling a country in the legend the points still appear in the plot. Do you know a way to solve this problem?

**Comment by larafaelivrin** [comment]
@JE1982 @jb3-2 I will move 6427 and 6429 to the branch issue-492.
The ID 6182 (Set: Legislaturplan) stays here. Can this ID be published?

**Comment by JE1982** [comment]
I agree with 6427 and 6429. 6182 has to be reviewed by MB, JE and formale Redaktion to be published.

**Comment by larafaelivrin** [comment]
@jb3-2 @JE1982  issue-492 does not exist?

**Comment by JE1982** [comment]
Correction: #942

**Comment by larafaelivrin** [comment]
@jb3-2 @JE1982  In this branch only 6182  should go live! All the other changes should not go live yet and have been moved to branch issue-942.

**Comment by jb3-2** [comment]
@JE1982 @larafaelivrin Please let me know if I can be of any help.

**Comment by jb3-2** [comment]
@JE1982 @larafaelivrin Please let me know if I can be of any help regarding this issue.

**Comment by JE1982** [comment]
6182 is in review at MB
