### ISSUE TITLE
Indikatoren-App: Sort by "Aktualisierungsdatum"

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#955]
@lcalmbach: according to a request by UG we would like to have the possibility to sort the indicators in "Indikatoren Liste" by the date of the next update (Aktualisierungsdatum).

**Comment by jb3-2** [comment]
@grilli73 Implementation started in branch issue-955. I plan to only allow changing sort order via URL parameter, e.g. "sort=aktualisierungsdatum_desc".
