### ISSUE TITLE
Indikatorenset Steuern

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#960]
We have to publish the new Set "Steuern" by the end of August (date is yet to be set). 
@larafaelivrin: here is data an graphs in excel: 1_Arbeitsbereiche\2_Wirtschaft_Arbeit\18_Oeffentliche_Finanzen\02-Steuern\Projekte\Steuerstatistik Basel-Stadt\Steuerstatistik Basel-Stadt 2018\Stst_Kernindikatoren_Daten.xlsx. please check if we need new templates and inform @jb3-2

**Comment by larafaelivrin** [comment]
@JE1982  DIe Indikatoren des Kapitel 2.4 sind nicht in der oben genannten Tabelle zu finden. Sind die Daten schon vorhanden?

**Comment by JE1982** [comment]
2-4-1 und 2-4-2 sind doch drin.  Oder nicht? 2-5-1 ist offenbar noch ausstehend.

**Comment by larafaelivrin** [comment]
@JE Danke, ich habe eben gemerkt, dass ich mit einera lten Version von : \\bs.ch\dfs\bs\pd\pd-stata\data\1_Arbeitsbereiche\2_Wirtschaft_Arbeit\18_Oeffentliche_Finanzen\02-Steuern\Projekte\Steuerstatistik Basel-Stadt\Steuerstatistik Basel-Stadt 2018\1___Steuerstatistik_2018.docx gearbeitet habe.

**Comment by larafaelivrin** [comment]
@jb3-2 

- [ ] 6907 & 6908: We need a new template for these plots:

![image](https://user-images.githubusercontent.com/23261816/43188826-6a129dbc-8ff5-11e8-8168-9bb4467dbb6f.png)

- [ ] 6988: I have changed the width of the plot but I do not think that this is the best solution. Can we add a dynamic axis as for [6623](https://statabs.github.io/indikatoren/chart-details.html?hideHeader=false&id=6623). Also "Zoom zurücksetzen" does not work. 

- [ ] 6912: The bars of the x-axis value "Grenzgänger aus Frankreich" should have a different colour or should somehow be highlighted. I could not accomplish this.

**Comment by JE1982** [comment]
projected date of publication: 26.9.2018
