### ISSUE TITLE
"Einbinden" soll keinen BS Header zeigen

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#963]
Im Kontext Menu kann man "Einbinden" mit und ohne Text auswählen. Die Page, die dann geöffnet wird, hat aber den BS Header, so bettet nie jemand einen Chart ein. 

Ich schlage also vor: 
- "Einbinden" umzubennenn zu "Einbetten" (English: "embed")
- Beim Einbetten den Header entfernen
- Zwei neue Menüpunkte "verlinken" mit und ohne Text, bei denen der BS Header sichtbar bleibt.

@JE1982 Einverstanden?

**Comment by jb3-2** [comment]
@JE1982 Einverstanden so? 

https://issue-963--statabs-indikatoren-test.netlify.com/ 

![screen shot 2018-07-23 at 13 08 25](https://user-images.githubusercontent.com/7261044/43073350-8623ea6a-8e79-11e8-8fe0-9df55deb7ccb.png)

**Comment by JE1982** [comment]
passt für mich.
