### ISSUE TITLE
Update Legislaturplan

### ISSUE THREAD

**Issue by JE1982** [StataBS/indikatoren#975]
@larafaelivrin: we need to change some charts in the set "Legislaturplan" due to the inputs of formale Redaktion. I think it would be good to work on them in a separate branch and then publish them all together. Could you do so? I will send you mails from access to tell you what has to be changed.

**Comment by larafaelivrin** [comment]
- [ ] 3104
- [ ] 6132
- [ ] 6147
- [ ] 5066

**Comment by jb3-2** [comment]
@larafaelivrin @JE1982 Can this go live?

**Comment by JE1982** [comment]
not yet, the charts still have to be checked
