### ISSUE TITLE
Inform SV that mail to FR was sent

### ISSUE THREAD

**Issue by bl99** [StataBS/indikatoren#976]
@lcalmbach After setting all three Status to "überprüft", it would be nice to have a feedback (e.g. pop-up window; or a hint in the text after "...und leitet ihn an die formale Redaktion weiter.") from the app that Formale Redaktion will automatically be informed by mail. Otherwise it is not clear if one has to inform FR manually.

**Comment by JE1982** [comment]
I think changing the text from "Der SV prüft den Indikator und leitet ihn an die formale Redaktion weiter." to "Der SV überprüft den Indikator. Die formale Redaktion wird automatisch informiert." should be enough.

**Comment by bl99** [comment]
Or: "Der SV überprüft den Indikator. Die formale Redaktion wird **anschliessend** automatisch informiert."

**Comment by JE1982** [comment]
![grafik](https://user-images.githubusercontent.com/20972660/44022456-ea11bdda-9ee7-11e8-9e3c-b9be303f597b.png)
