### ISSUE TITLE
Extend 6037

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#977]
Bitte auch Feedback von MSC umsetzen und Bruttolöhne M/F (siehe CSV) zusätzlich in der Grafik darstellen: 
"Ja, die Bruttolöhne können auch publiziert werden. Man könnte sie sogar in der Grafik einfügen (dafür müsste man die Grafik ein bisschen ändern)."

**Comment by larafaelivrin** [comment]
Implemented. I agree, bars look nicer than lines!

**Comment by jb3-2** [comment]
@larafaelivrin Can this go live?

**Comment by larafaelivrin** [comment]
@JE1982 Can this go live?

**Comment by JE1982** [comment]
is in review at MSC

**Comment by JE1982** [comment]
6037 is getting optimized in 975
