### ISSUE TITLE
Wohnviertel: Replace existing Tableau-based Charts

### ISSUE THREAD

**Issue by jb3-2** [StataBS/indikatoren#990]
By Nana-Mittelmaier: 
Bitte die tsv-Dateien (jeweils nur 1 Datei mit allen Wohnvierteln) erstellen für:

- [x] Alterspyramiden nach Wohnviertel und Gemeinden + Kanton Basel-Stadt
- [x] Staatsangehörigkeit 
- [x] Anzahl Zimmer pro Wohnung 

Die Ranggrafiken modifizieren, so dass immer auch der Wert für den Kanton angezeigt wird

**Comment by jb3-2** [comment]
@Nana-Mittelmaier I have implemenetd the chart for Staatsangehörigkeit, do you want to have alook at it? I still have to change the colors like used in Tableau. 
https://issue-990--statabs-indikatoren-test.netlify.com/?search=Ausl%C3%A4ndische%20Bev%C3%B6lkerung%20nach

**Comment by jb3-2** [comment]
@lcalmbach @JE1982 In order to have multiple charts based on a single tsv and/or chart js file, I have enhanced the Indikatorenportal. For example in Wohnviertel, we create a chart for Staatsangehörigkeit for each Wohnviertel, and want to reuse a single js and tsv for all 21 Wohnviertel. This works now if only one of the charts has a tsv that contains all data for all Wohnviertel, and all charts that want to use that js and tsv add 3 properties to their metadata (see screenshot below). 

Can you please implement this in the SQL backend? Should we discuss when to use this vs. mother-daughter relationships?

Example: https://issue-990--statabs-indikatoren-test.netlify.com/?search=Ausl%C3%A4ndische%20Bev%C3%B6lkerung%20nach

![screen shot 2018-08-19 at 16 54 43](https://user-images.githubusercontent.com/7261044/44310104-3192d980-a3d1-11e8-85f0-d6b6c9ddc9d6.png)

**Comment by jb3-2** [comment]
@JE1982 @Nana-Mittelmaier Ready for your review.

**Comment by JE1982** [comment]
@jb3-2: please make the pyramids look like this one 
![image](https://user-images.githubusercontent.com/20972660/48338511-2238ca80-e666-11e8-84ff-8de09568cd36.png) (5142 in issue-1178)

**Comment by jb3-2** [comment]
@Nana-Mittelmaier Nun sind auch die BS Charts für Populationspyramide und Zimmerzahl hinzugefügt. Du kannst nun mit dem setzen der Metadaten weitermachen.
