### ISSUE TITLE
map: get title directly from *.tsv

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#991]
Is it possible to get both title names of the map direct from the *.tsv @jb3-2 

Reason of this request: 
**@JE1982**:  6389: bitte in 942 die Jahreszahlen in den Legendenbeschriftungen anpassen (neu: 1998 und 2017). Kann man das dynamisch machen?

**Comment by jb3-2** [comment]
Yes, this is pretty simple and straightforward, I have implemented it for 6389 in branch issue-498, see screenshot below: 

![screen shot 2018-08-14 at 15 31 40](https://user-images.githubusercontent.com/7261044/44094703-2edf5130-9fd7-11e8-8141-fec899de3ecc.png)
